### ISSUE TITLE
Evil search bug breaks Spacemacs

### ISSUE THREAD

**Issue by NightMachinary** [syl20bnr/spacemacs#10410]
#### Description :octocat:
Evil search bug.

#### Reproduction guide :beetle: *Observed behaviour:* :eyes: :broken_heart:
- Start Emacs
- Search sth with '/'.
- Without pressing 'RET' click on the main buffer.
- The evil functionality is broken: pressing a single d deletes the line. (Essentially a lot of keys double-press.)
- By clicking on the minibuffer and pressing RET you can make evil normal.
- But if you delete the main buffer and then press RET, evil stays broken.
- You have to restart emacs for it to work normally again.

*Expected behaviour:* :heart: :smile:
The search should be canceled when the minibuffer loses focus.

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5c251f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(vimscript
 (rust :variables rust-format-on-save t)
 crystal
 (haskell :variables haskell-enable-hindent t)
 html python
 (scala :variables scala-auto-insert-asterisk-in-comments t scala-use-unicode-arrows t scala-auto-insert-asterisk-in-comments t)
 autohotkey helm auto-completion emacs-lisp
 (ibuffer :variables ibuffer-group-buffers-by 'modes)
 coq emoji
 (unicode-fonts :variables unicode-fonts-force-multi-color-on-mac t)
 git
 (java :variables java-backend 'ensime)
 markdown org
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking syntax-checking version-control osx racket clojure)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by NightMachinary** [comment]
BTW pressing <Esc> should also cancel the search and return the focus to the main buffer IMHO.

**Comment by CeleritasCelery** [comment]
I can't reproduce. But if you think you can reliably reproduce the error, file an issue upstream with evil.

**Comment by duianto** [comment]
I'm able to reproduce it:
- Start Emacs
- open `.spacemacs`: `SPC f e d`
- open the search prompt: `/`
- select the `.spacemacs` window: `M-1`

now `d` deletes the whole line, and `y` copies the whole line.

Switching back to the minibuffer `SPC w b`, and exiting `ESC` or confirming the previous search term `RET`, restores `d` and `y`'s default behaviour of waiting for a motion.

I'm unable to make the issue permanent by deleting a buffer, and confirming the search term.
If I `SPC b d` delete the `.spacemacs` buffer. Then I'm still able to switch to the minibuffer `SPC w b` and can cancel/confirm the search prompt. Now `d` and `y` have been restored to their default behaviour.

After deleting the buffer and confirming the search, then the messages buffer shows:
>Error in minibuffer-exit-hook (evil-ex-search-stop-session): (error "Selecting deleted buffer")
evil-ex-start-search: Selecting deleted buffer

**Comment by NightMachinary** [comment]
@duianto What should I do? File an issue with evil?

**Comment by duianto** [comment]
It doesn't seem to be an evil issue, because when I start Emacs, and just load `evil`, then the `/` search prompt disappears (gets canceled?), when the `.spacemacs` buffer is selected, with the mouse, or with `C-x o`. And both `d` and `y` expects a motion.

This is how I only loaded the evil package.
- Start Emacs with the `--quick` argument to not load any configurations
- Let Emacs know where the packages are located, by evaluating:
```
(setq package-user-dir "~/.emacs.d/elpa/25.3/develop/")
```
- `M-x` `package-initialize`
- `M-:` `(require 'evil)`
- `M-x` `evil-mode`

**Comment by NightMachinary** [comment]
@duianto any idea what’s wrong?

**Comment by duianto** [comment]
The evil package adds an `minibuffer-exit-hook`, when the `evil-ex-search-start-session` function is called.
```
(add-hook 'minibuffer-exit-hook #'evil-ex-search-stop-session)
```
source: https://github.com/emacs-evil/evil/blob/427cf5faa57e8794ac93f594dc3d1972e687a25a/evil-search.el#L873

I don't know what/if Spacemacs does something to negate the `minibuffer-exit-hook`.

**Comment by carloscheddar** [comment]
I've been having this issue for months and could never find out how I triggered it. I always restarted to fix it but it's good to know that I can exit the mini buffer instead.

**Comment by CeleritasCelery** [comment]
could we just add that hook back?

**Comment by codygman** [comment]
I've also been running into this recently using develop, emacs 27, and
darwin a lot when having to CTRL-G CTRL-G searches in large files, but
never could figure out reproduction steps.

It's possible i could have changed focus and inadvertently followed these
reproduction steps.

I recently disabled bidi-reordering though and come to think of it i didn't
encounter this issue before disabling it.

Can anyone see if bidi reordering matters here? I'll also test tomorrow.

**Comment by NightMachinary** [comment]
@codygman I have never heard of bidi-reordering and so I shouldn't have disabled it in my setup. BTW, where do you get emacs 27 from? Isn't emacs 26 still in beta?!

**Comment by NightMachinary** [comment]
I have found a workaround! Just set the evil-search-module to its default, 'isearch'. This might be a bug in evil itself, not in Spacemacs. @duianto Can you check if the bug exists with just evil loaded?

**Comment by duianto** [comment]
Changing the `evil-search-module` to `isearch` doesn't change anything for me.

In Spacemacs, the `/` search prompt remains in the minibuffer and `d` still deletes the current line.

With just Emacs and evil (as described in comment: https://github.com/syl20bnr/spacemacs/issues/10410#issuecomment-371083697), the `/` search prompt cancels, when a window is selected.

**Comment by NightMachinary** [comment]
@codygman @carloscheddar @CeleritasCelery Can you check this variable? https://github.com/syl20bnr/spacemacs/issues/10410#issuecomment-376956333

**Comment by NightMachinary** [comment]
@davidpasztor Do `M-x customize` like this:
![image](https://user-images.githubusercontent.com/36224762/40280236-95bfbe86-5c65-11e8-9213-777af6053f65.png)
Or put `(setq evil-search-module 'isearch)` in your user-config.

**Comment by NightMachinary** [comment]
@davidpasztor Please provide feedback, if this works, we'll need to put it in Spacemacs itself.

**Comment by davidpasztor** [comment]
@NightMachinary thanks for your help, I put that in my user-config, then reload my spacemacs, but the issue still persists :(

**Comment by NightMachinary** [comment]
Try using customize? I personally haven't tried `setq`. Some things only
work with customize.

**Comment by davidpasztor** [comment]
@NightMachinary sadly customize didn't help either

**Comment by larebsyed** [comment]
If found a temporary fix by adding these line in by .spacemacs file

`  (defun kill-minibuffer ()
    (interactive)
    (when (windowp (active-minibuffer-window))
      (evil-ex-search-exit)))

  (add-hook 'mouse-leave-buffer-hook #'kill-minibuffer)
`

**Comment by dijonkitchen** [comment]
Any updates on this? Should the temporary fix be incorporated in the latest branch?

**Comment by carloscheddar** [comment]
Another alternative is using `SPC s s` which activates helm swoop for the buffer and is similar to what I was doing with evil-search.

**Comment by levitanong** [comment]
I'm encountering this issue as well in doom-emacs[1], could it be an upstream problem?

[1] https://github.com/hlissner/doom-emacs

**Comment by togakangaroo** [comment]
I ended up in what I believe was a similar state. It seems to happen every few weeks and I didn't know how to recreate it. 

I use evil mode and sometimes I seem to enter a state across most if not all buffers where in command mode `d` is bound to `evil-delete`
not `dd`, but just `d`. So doing something like `diw` (which should delete just the word) doesn't work and instead it deletes the entire line and then hits `iw`

Bringing this up on gitter, I was directed to this issue. After reading the above I tried running `exit-minibuffer` and it fixed things.

I can confirm that the above recreation steps trigger this issue for me running on the develop branch commit `4b195ddfc9228256361e0b264fe974aa86ed51a8`

**Comment by lorenh516** [comment]
Also experienced this visual-line-select bug breaks after using `evil-ex-search-backward`. When I navigated to another window and then back to spacemacs, visual mode doesn't select as expected (only the last line of the block I selected is yanked to kill ring). `d` also behaves like `dd`.

#### To reproduce error :beetle:
- Start Emacs
- Open a file in a buffer
- Trigger evil-ex-search-backward with `?`
- Click on an external window
- Click back into spacemacs window
- Attempt to select a block of text in visual mode, yank with `y` and put in some other location with `p`.  

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0cec3d0a6)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(go yaml sql helm
    (debug :variables debug-additional-debuggers
           '("remake"))
    dap lsp javascript csv
    (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t)
    emacs-lisp evil-commentary git html markdown org
    (latex :variables latex-build-command "Make")
    bibtex graphviz
    (python :variables python-auto-set-local-pyvenv-virtualenv 'on-visit python-test-runner 'pytest python-backend 'lsp python-formatter 'black python-fill-column 80 :packages
            (not live-py-mode))
    latex spell-checking syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by sdwolfz** [comment]
I'll try to investigate this, and if I can reproduce it on my machine will try to patch it.

**Comment by brandonwillard** [comment]
> I found a temporary fix by adding these line in my .spacemacs file
> 
> ```emacs-lisp
>   (defun kill-minibuffer ()
>     (interactive)
>     (when (windowp (active-minibuffer-window))
>       (evil-ex-search-exit)))
> 
>   (add-hook 'mouse-leave-buffer-hook #'kill-minibuffer)
> ```
> 
> _edited by @syl20bnr to format the code snippet correctly_

While this may work for mouse-based window changes from the minibuffer (during `ex` searches), it doesn't account for numerous other cases (e.g. window changes starting from `C-Space` and the like). 

Something along the lines of the following should account for general window changes&mdash;and close more than just the `ex` search:
```elisp
(defun spacemacs//close-unfocused-minibuffer (window-or-frame)
  "Close the minibuffer/recursive-edit when leaving it for another window."
  (when (and (minibuffer-window-active-p (previous-window nil t))
             (not (minibufferp)))
    ;; Just some debugging
    (let ((inhibit-message t))
      (message "close-unfocused-minibuffer: depth %s, minibuffer-depth %s, window %s"
               (recursion-depth) (minibuffer-depth) (previous-window nil t))
      (message "close-unfocused-minibuffer: closing recursive edit"))
    ;; There are a few ways to close the minibuffer/recursive edit, but we want the/a one
    ;; that gracefully calls clean-up code (if any).
    ;; (exit-minibuffer)
    ;; (abort-recursive-edit)
    (exit-recursive-edit)))

(add-hook 'window-selection-change-functions #'spacemacs//close-unfocused-minibuffer)
```
It seems like this situation requires even more careful consideration, but the code in that snippet has yet to break normal minibuffer usage (e.g. `ex` completion).  I'm not saying it won't, though!

**Comment by ryanpeach** [comment]
Having this problem too, just chiming in for updates.

**Comment by hjorvari** [comment]
This is the most annoying thing ever but TIL you can just do `<spc> <spc> exit-minibuffer` and it will fix it. Should be in the FAQ imo.

**Comment by duianto** [comment]
https://github.com/syl20bnr/spacemacs/issues/10410#issuecomment-376956333 ☝️ 
>I have found a workaround! Just set the evil-search-module to its default, 'isearch'. This might be a bug in evil itself, not in Spacemacs.

@NightMachinary You seem to be right.

The issue also occurs without Spacemacs (just Emacs and https://github.com/emacs-evil/evil), when:
```elisp
(setq evil-search-module 'evil-search)
```
is defined in `init.el` before:
```elisp
(require 'evil)
(evil-mode 1)
```
### In Spacemacs
I retested adding:
```elisp
(setq evil-search-module 'evil-search)
```
to either the user-init or user-config sections, but the issue still occurs.

However the issue stops happening when: `evil-search-module`
is set to `isearch` with: `M-x customize`

(As you said in a later comment: https://github.com/syl20bnr/spacemacs/issues/10410#issuecomment-390489504 ☝️)

**Comment by NightMachinary** [comment]
@duianto What is very weird is that I regularly lose my customized settings. I don’t know exactly how it happens, but every once in a while I notice something I had customized has reset. That’s why I’ve been avoiding customizing settings and use direct setq commands.

**Comment by duianto** [comment]
There's an issue about customizations here:
spacemacs forgets all customizations made through `customize` / `org-customize` #10504

It's marked as `fixed in develop`, and at least for me, `bmags` reproduction steps: https://github.com/syl20bnr/spacemacs/issues/10504#issuecomment-464848111
of adding a custom `fill-column` setting, remains after restarting Emacs and installing a package.

Maybe there's some side case that the fix didn't catch. You could post a comment there that your still losing customizations.

**Comment by NightMachinary** [comment]
@duianto I don't know when exactly was the last time I lost a customization. I noticed this one because it causes an annoying bug when using the mouse with evil search, but it's possible that the lost was for before the bug got fixed. I'll be sure to comment if I notice a new customization resetting though.

**Comment by allentiak** [comment]
@NightMachinary Could you try reproducing this on current `develop`?  _(So we can verify this bug is still relevant.)_

**Comment by NightMachinary** [comment]
@allentiak I have switched to Doom, and have workarounds in my Spacemacs config regardless. Feel free to close the issue, someone will just comment if the issue still persists.

**Comment by allentiak** [comment]
@duianto It seems this one can be safely closed :-)

**Comment by duianto** [comment]
Instead of closing this, let's fix it 😄 

A PR has been opened upstream:
Exit search prompt on mouse leave minibuffer https://github.com/emacs-evil/evil/pull/1330

**Comment by allentiak** [comment]
Cool!
_(In any case, fixing it would also close it ;-)_

**Comment by nwilleyltk** [comment]
I can confirm that the issue still exists for me on the develop branch.   The mini-buffer will stick with the search term, and while it is stuck, typing c or d will delete the entire line.   Once the mini-buffer is closed using `exit-minibuffer`, it behaves normally.

**Comment by mabdh** [comment]
> I can confirm that the issue still exists for me on the develop branch. The mini-buffer will stick with the search term, and while it is stuck, typing c or d will delete the entire line. Once the mini-buffer is closed using `exit-minibuffer`, it behaves normally.

This works for me. Thanks!

**Comment by lebensterben** [comment]
@duianto 
Since there's no update from upstream, we should can use `advice-add` to add a `:after` advice to for now.

**Comment by duianto** [comment]
A PR with a possible fix has been opened:
Fix evil search prompt on mouse leave #15002

**Comment by lebensterben** [comment]
Just merged the fix and updating the label to 'Fixed in develop' now.

**Comment by lebensterben** [comment]
closing since it's fixed in upstream.
