### ISSUE TITLE
update breaks clojure layer

### ISSUE THREAD

**Issue by cpaulik** [syl20bnr/spacemacs#1071]
The new update procedure deleted the highlight package which was not reinstalled after restart. This leads to `cider-eval-sexp-fu` not being loaded correctly. 

This can be fixed by adding `cider-eval-sexp-fu` to the clojure packages since it is now available on melpa but I don't know if there are any differences between the melpa and the spacemacs version.

**Comment by syl20bnr** [comment]
Argh I see.
I pushed on develop the modifications to use the MELPA version of `cider-eval-sexp-fu` but the bug you got is deeper than this.

I let the issue open until I fixed the new update.

**Comment by cpaulik** [comment]
This issue still persists because even with `cider-eval-sexp-fu` in the list the `highlights` package is not installed. But this is probably what you meant with the bug being deeper than the original problem I had.

**Comment by syl20bnr** [comment]
I fixed the issues in 3107d5d9f85c05f8d76f7115a0e065e1acdc9d48
Thank you for the reports !

**Comment by syl20bnr** [comment]
Duplicate of #1085
