### ISSUE TITLE
Errors on startup with exec-path-from-shell in dotspacemacs-excluded-packages

### ISSUE THREAD

**Issue by marienz** [syl20bnr/spacemacs#10842]
#### Description :octocat:

Commit 7944ed2634f7f136c701942a4e9800d2d5308739 moved environment cleanup from `spacemacs|use-package-add-hook exec-path-from-shell` to a new function that always calls `exec-path-from-shell-copy-env`. That breaks when `exec-path-from-shell` is in `dotspacemacs-excluded-packages`. It would be nice if it did not.

See #8537 for why someone might exclude `exec-path-from-shell`.

Note having these variables unset is perfectly fine for the Go variables (they have sane defaults) and probably also ok for the Rust one (but I'm less familiar with that one).

Also note #8537 mentions "Layers should avoid calling exec-path-from-shell-copy-env multiple times" (because it's slow). The new function calls `exec-path-from-shell-copy-env` three times for Go, while the old code did not.

I'm not sure what that commit fixed (the commit message doesn't say), but maybe there's a better way?

#### Reproduction guide :beetle:
- Have the rust or go layer enabled, exec-path-from-shell in dotspacemacs-excluded-packages
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
The `*Warnings*` buffer pops up, showing:
```
Error (use-package): go-mode/:init: Symbol’s function definition is void: exec-path-from-shell-copy-env
Error (use-package): rust-mode/:init: Symbol’s function definition is void: exec-path-from-shell-copy-env
```

*Expected behaviour:* :heart: :smile:
No errors.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 6d0b4c4c6)
- Graphic display: t
- Distribution: spacemacs-base
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(spacemacs-base spacemacs-completion spacemacs-layouts spacemacs-editing spacemacs-editing-visual spacemacs-evil spacemacs-language spacemacs-misc spacemacs-modeline spacemacs-navigation spacemacs-org spacemacs-project spacemacs-purpose spacemacs-visual ivy
                (auto-completion :variables auto-completion-idle-delay nil)
                better-defaults
                (ibuffer :variables ibuffer-group-buffers-by nil)
                c-c++ emacs-lisp
                (go :variables go-tab-width 4)
                html
                (javascript :variables javascript-backend nil)
                lua markdown nginx perl5 protobuf
                (python :variables python-backend 'lsp)
                rust shell-scripts sql systemd yaml git github
                (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
                syntax-checking version-control lsp)
```
- System configuration features: XAW3D XPM JPEG TIFF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS LUCID X11 THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by jasminpatry** [comment]
I'm also getting getting this on Windows, and **don't** have exec-path-from-shell excluded.
#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 86b4e6f)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(asciidoc sql helm
          (auto-completion :variables auto-completion-tab-key-behavior 'complete auto-completion-return-key-behavior 'complete auto-completion-complete-with-key-sequence "jk" auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
          (c-c++ :variables c-c++-default-mode-for-headers 'c++-mode)
          csv
          (colors :variables colors-colorize-identifiers 'all colors-enable-nyan-cat-progress-bar nil)
          emacs-lisp git go gtags html javascript latex markdown perforce python
          (org :variables org-enable-github-support t)
          ranger syntax-checking windows-scripts yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by syl20bnr** [comment]
Can you try again with last develop ? I think the recent changes should fix this.

**Comment by Chream** [comment]
Still getting this on develop. Wrapping in (eval-after-load 'exec-path-from-shell ...) fixes it.

**Comment by marienz** [comment]
Thanks, that fixed my setup (with exec-path-from-shell explicitly in dotspacemacs-excluded-packages).

**Comment by jasminpatry** [comment]
I'm now getting:
 `Error (use-package): go-mode/:init: Cannot open load file: No such file or directory, exec-path-from-shell`. 

Is there something that prevents exec-path-from-shell from being installed on Windows (where AFAICT it's not supported unless you're running a unix-like shell)? The only trace of that package that I see on my system is `~/.emacs.d/.cache/quelpa/melpa/recipes/exec-path-from-shell`. FWIW I'm running MSYS2, so exec-path-from-shell would probably work, but I can't seem to convince spacemacs to install the package.

**Comment by marienz** [comment]
I think this bit of spacemacs-bootstrap/packages.el is what pulls it in, but only on mac, linux or under X:

```
        (exec-path-from-shell :step bootstrap
                              :toggle (or (spacemacs/system-is-mac)
                                          (spacemacs/system-is-linux)
                                          (eq window-system 'x)))
```

I don't know what `window-system` is for you, but I'm guessing it's not `x`?

I don't know what `configuration-layer/package-used-p` does with such packages (referenced from a layer but with `:toggle nil`). If it still returns t, that'd explain the failure you get.

**Comment by jasminpatry** [comment]
Thanks @marienz . `window-system` is `w32` for me, and `(configuration-layer/package-used-p 'exec-path-from-shell)` indeed returns `t`.

**Comment by DoaneAS** [comment]
Just noting that putting `exec-path-from-shell` in `dotspacemacs-excluded-packages` fixed issue where ESS package was not able to see R as defined in `$PATH`.

**Comment by marienz** [comment]
Thanks for the reminder, github-actions bot!

The issue as I reported it (with exec-path-from-shell explicitly in dotspacemacs-excluded-packages) is fixed, so I'll click the "close" button.

Issues involving exec-path-from-shell on platforms where it is toggled off are probably best reported separately. Issues involving $PATH fixed by adding or removing exec-path-from-shell are generally local (by design exec-path-from-shell changes $PATH, depending on your local setup it can make it better or worse).
