### ISSUE TITLE
pyenv mode no longer mapped to keys

### ISSUE THREAD

**Issue by sebhahn** [syl20bnr/spacemacs#10898]
#### Description :octocat:
Pyenv mode no longer mapped

#### Reproduction guide :beetle:
- Start Emacs
- Open Python file
- 'SPC m v s`

*Observed behaviour:* :eyes: :broken_heart:
'SPC m v s` is undefined

*Expected behaviour:* :heart: :smile:
Selection of pyenv Python env.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. d28990537)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(ansible
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory "~/.spacemacs.d/snippets/" auto-completion-complete-with-key-sequence "jk" auto-completion-enable-help-tooltip nil)
 bibtex c-c++ colors csv custom-org-config dash emacs-lisp
 (elfeed :variables rmh-elfeed-org-files
         (list "~/ownCloud/org/elfeed.org")
         elfeed-db-directory "~/ownCloud/org/.elfeed")
 elixir erc erlang ess games
 (git :variables git-gutter-use-fringe t)
 github gnus helm html ipython-notebook
 (latex :variables font-latex-fontify-script nil latex-enable-auto-fill t latex-enable-folding t)
 lua markdown mu4e-config
 (org :variables org-enable-reveal-js-support t)
 pandoc plantuml
 (python :variables python-enable-yapf-format-on-save nil python-test-runner 'pytest)
 python-config ranger research-config ruby search-engine semantic
 (shell :variables shell-default-shell 'term shell-default-term-shell "/bin/zsh")
 speed-reading spell-checking syntax-checking tmux version-control yaml)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by syl20bnr** [comment]
I think it was a regression with our issues with env. vars this week due to the refactoring of their import. Can you try again with last develop ?

The cause of this was surely this check: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/python/packages.el#L224

**Comment by syl20bnr** [comment]
MMmmh the commit seems to show that you had already the changes...
What does `(getenv "PATH")` say ? And what is the value of `exec-path` ?

**Comment by syl20bnr** [comment]
I just pushed a commit that should fix your issue.

**Comment by sebhahn** [comment]
I pulled the latest commit from develop (f1f8db002) but it still doesn't work, pyenv-mode seems not to be activated either

**Comment by sebhahn** [comment]
I think something is not loaded correctly, because after an update of elpa packages it worked. However, another restart of spacemacs and the issue is back

**Comment by songpeng** [comment]
@sebhahn 
When I update spacemacs  dev branch, I suffer from the problem of anaconda error (pointed to eldoc error: wrong type stringp)
I roll back to the commit before you mentioned, it's OK now. Thanks.

**Comment by chwrtlprmft** [comment]
I have this problem. I installed pyenv-mode with `M-x package install pyenv-mode" and I can activate pyenv-mode manually (so it seems to find the pyenv installation), but the keybinding does nothing.

Has this been fixed?
