### ISSUE TITLE
wrong text background color in a Term mode buffer

### ISSUE THREAD

**Issue by orialb** [syl20bnr/spacemacs#11306]
#### Description :octocat:
text background color in a Term mode buffer does not match that of
chosen color theme. (note that I am referring to running a term buffer from
within emacs GUI, and not running emacs itself in the terminal)

#### Reproduction guide :beetle:
- Start Emacs
- change to "zenburn" theme.
- open a buffer in term mode (e.g run term command)

*Observed behaviour:* :eyes: :broken_heart:
the text background color is bluish, similar to solarized dark
(not sure how this color is called,see screenshot)
![image](https://user-images.githubusercontent.com/1208196/45287279-2ae71600-b4e8-11e8-873e-2c38887f0d3d.png)

*Expected behaviour:* :heart: :smile:
text background should be black matching that of chosen editor theme

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. be93ed91a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown html python lsp julia helm auto-completion bibtex emacs-lisp git org latex themes-megapack spell-checking)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by orialb** [comment]
Following some older stack exchange post I tried adding:
`lisp
(custom-set-faces
   '(term-color-black ((t (:foreground "#3F3F3F" :background "#2B2B2B"))))
   '(term-color-red ((t (:foreground "#AC7373" :background "#8C5353"))))
   '(term-color-green ((t (:foreground "#7F9F7F" :background "#9FC59F"))))
   '(term-color-yellow ((t (:foreground "#DFAF8F" :background "#9FC59F"))))
   '(term-color-blue ((t (:foreground "#7CB8BB" :background "#4C7073"))))
   '(term-color-magenta ((t (:foreground "#DC8CC3" :background "#CC9393"))))
   '(term-color-cyan ((t (:foreground "#93E0E3" :background "#8CD0D3"))))
   '(term-color-white ((t (:foreground "#DCDCCC" :background "#656555"))))

   '(term-default-fg-color ((t (:inherit term-color-white))))
   '(term-default-bg-color ((t (:inherit term-color-black))))

   )`
to my dotfile but it didn't do anything.

**Comment by drewLo** [comment]
I had this same issue, [here's how I fixed it](https://lough.tech/ansi-term-colors/):

1.  M-x customize
2.  search term: term color
3.  set the term color variables from here.
  3a. you can also go into M-x customize-group and search for ansi-color-names-vector and edit them there. some color variable's values are pulled from here.

**Comment by orialb** [comment]
@drewLo  Thanks for the tip. I tried to follow this and changed "Bg color" to #3F3F3F  which is supposed to be zenburn BG-color, but it is still not looking the same as the editor background.
Did you make it work specifically with zenburn? 
If so could you share the specific settings that worked for you?

**Comment by justinlime** [comment]
I know this is a dead issue, but in case it might help someone, here's a workaround I found from solaire-mode.el, works great for me:


```lisp
(add-hook 'term-mode-hook #'(lambda()

  (defface term-background
  '((t (:inherit default :background "#11111B")))
  "Term mode background"
  :group 'basic-faces)

  (setf (elt ansi-term-color-vector 0) 'term-background)

))
```
