### ISSUE TITLE
Autocomplete is broken when trying to switch to new folder in neotree.

### ISSUE THREAD

**Issue by phoe** [syl20bnr/spacemacs#11368]
#### Description :octocat:
Autocomplete is broken when trying to switch to new folder in neotree.

#### Reproduction guide :beetle:
- Start Emacs
- SPC f t (to open up Neotree)
- C-c c (to open its switch-folder dialog)
- Start typing a folder name (for example, "Pro")
- Hit TAB

*Observed behaviour:* :eyes: :broken_heart:
Name is autocompleted, for example, `/home/phoe/Pro` to `/home/phoe/Projects/`

*Expected behaviour:* :heart: :smile:
Minibuffer says "Cannot split side window or parent of side window". `*Messages*` buffer says, "split-window: Cannot split side window or parent of side window".

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript sql html markdown helm auto-completion common-lisp emacs-lisp git org
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by phoe** [comment]
![28 Days Later logo](http://static1.squarespace.com/static/58fa32fc37c5811f91ba2ccf/5a330558e2c483629641b4af/5a3305e0085229e36d8bee20/1513312644119/?format=200w)

**Comment by d12frosted** [comment]
I actually like the joke. Sorry for the long silence. Apparently, everyone is too busy to fix this.

As usual - PR is welcome ;)

**Comment by phoe** [comment]
I could try fixing it myself, but I am completely unaware of how to get any debug logs or stack traces. Is there any kind of manual for debugging Spacemacs?

**Comment by sdwolfz** [comment]
@phoe see this wiki page: https://github.com/syl20bnr/spacemacs/wiki/Debugging

And if you feel like anyhting is missing let us know and we will try to clarify.

**Comment by phoe** [comment]
I cannot copypaste the contents of `*Backtrace*` buffer because I cannot select text from it while the lower window is open, and once I close that window, the contents of that window disappear. The best I can give is a screenshot of my Emacs showing the backtrace.

![zrzut ekranu z 2018-12-23 17-47-34](https://user-images.githubusercontent.com/15045546/50385771-35b26900-06db-11e9-9626-cca94eafcdab.png)

**Comment by sdwolfz** [comment]
I tried to debug this a while ago to see what what going on and it looks like helm tries to split a window, but none is available to be split so it gives that error... Now, the reason why helm tries to split that window is unknown to me. I tried playing around with the code to see if I can fix this but I was not able to come up with a solution.

You could try posting this upstream at helm's issue tracker, they might be able to get to the bottom of this.

**Comment by phoe** [comment]
I just noticed that the Tab button works just fine unless neotree is open. After I open and then close it, tab button works normally.

**Comment by phoe** [comment]
The upstream issue https://github.com/emacs-helm/helm/issues/2120 was closed - @sdwolfz mentioned that the issue is not in helm but fully in spacemacs.

**Comment by sdwolfz** [comment]
We'll need to implement a fix in the `spacemacs//display-helm-window` function: https://github.com/syl20bnr/spacemacs/blob/c7a103a772d808101d7635ec10f292ab9202d9ee/layers/+spacemacs/spacemacs-completion/packages.el#L29

**Comment by sdwolfz** [comment]
OK so after debugging this for a while I'm back to pointing out at helm, there might be a bug with the way helm decides which window to split, and accidentally using the next window instead of the previous one.

@phoe I'm going to open a PR to helm and see if my investigation indeed correct (this bug is a nasty annoying UX anomaly that I really want to see gone).

**Comment by phoe** [comment]
Thanks! Please link the PR here once it's posted.

**Comment by sdwolfz** [comment]
Upstream PR: https://github.com/emacs-helm/helm/pull/2122

**Comment by sdwolfz** [comment]
The problem should be fixed now.

**Comment by sdwolfz** [comment]
Start spacemacs and from the home buffer press `SPC f e U`, confirm the update and restart.

**Comment by phoe** [comment]
After switching to develop and executing `SPC f e U` the issue still exists on my machine. How do I continue debugging it?

**Comment by sdwolfz** [comment]
Make sure you have the latest version of helm. You could rty deleting the helm package from the melpa cache directory and restarting, this should download it again. 

In terms of debugging, turn on `debug-on-error` with `SPC t D` and look at the stacktrace.

**Comment by phoe** [comment]
`helm-20181222.848` gets installed. I don't think it's fresh enough.

**Comment by phoe** [comment]
The stacktrace seems the same.

![zrzut ekranu z 2019-01-03 15-46-32](https://user-images.githubusercontent.com/15045546/50643561-c48e7380-0f6e-11e9-9f09-94ef843b4694.png)

**Comment by sdwolfz** [comment]
My change was merged on 24th of december and this package is 2 days older. Do you have it pinned to be installed from melpa stable?

**Comment by phoe** [comment]
I don't think I do. Where do I check it?

**Comment by sdwolfz** [comment]
it should be in your `.spacemacs`, make sure you have `dotspacemacs-use-spacelpa nil` or check if you push melpa-stable in `configuration-layer-elpa-archives`.

Anyway since you updated from master just now make sure you bring your `.spacemacs` up to date with `SPC f e D`.

**Comment by phoe** [comment]
I completely disposed of my `~/emacs.d/` and `~/.spacemacs` - a freshly installed Spacemacs develop seems to have the same issues.

Has helm ever released a new MELPA version? https://melpa.org/#/helm shows the following:

![zrzut ekranu z 2019-01-03 16-38-13](https://user-images.githubusercontent.com/15045546/50646293-fc4ce980-0f75-11e9-89e4-f26595d1079c.png)

**Comment by phoe** [comment]
Huh!

```
┌─[phoe][phoetower][±][develop → origin ✓][~/.emacs.d]
└─▪ grep -r -n -i "(previous-window (selected-window) 1)" .
./elpa/25.2/helm-core-20181225.639/helm.el:6223:                    (setq prev-win (previous-window (selected-window) 1)))
./elpa/25.2/develop/helm-core-20181225.639/helm.el:6223:                    (setq prev-win (previous-window (selected-window) 1)))
```

I *do* have the code in question downloaded.

I use the default emacs home directory.

I'll update emacs from 25.2.2, clean everything once again and see if this persists. Are there any additional cache directories that I should take care of while cleaning?

**Comment by phoe** [comment]
Nope, I have removed `~/.emacs.d/`, `~/.spacemacs/`, updated to emacs 26.1, and the error persists on the vanilla installation for me.

![zrzut ekranu z 2019-01-03 19-44-20](https://user-images.githubusercontent.com/15045546/50655320-0da2ef80-0f90-11e9-9f86-9d7fa1c04025.png)

**Comment by phoe** [comment]
I seem to get the same stacktrace no matter if I change `previous-window` back to `next-window` and load the modified function.

**Comment by sdwolfz** [comment]
There's probably some weird caching issue on your machine. Try starting with a new `.spacemacs` configuration, and slowly move your changes over to the new file. Or try running in a VM or container.

**Comment by phoe** [comment]
Yes, it's crazy. I manually evaluated the modified function in emacs on a completely clean .spacemacs and .emacs.d - no cigar yet.

**Comment by sdwolfz** [comment]
I was able to reproduce this. With the cursor inside the treemacs buffer, pressing `SPC f f` and trying to `C-l` a directory gives the error. Not able to reproduce when the cursor is outside treemacs when pressing `SPC f f`. I'll see what I can do...

**Comment by sdwolfz** [comment]
OK I found another fix, It's related to the same function as in https://github.com/emacs-helm/helm/pull/2122/files but a level down.

Honestly I don't understand that code, and why it needs to split windows... I'll try to get a patch in this evening and maybe get some information on what it's purpose is.

**Comment by sdwolfz** [comment]
Opened a PR upstream: https://github.com/emacs-helm/helm/pull/2200.

**Comment by duianto** [comment]
@sdwolfz The helm fix seems to be working when pressing `C-l` in `SPC f f` with Treemacs as the active window.

But there's another occurrence of the "cannot split ..." message that wasn't fixed by that PR.
If the help buffer is open.

Reproduction steps:
- Open a `*Help*` buffer: `SPC h d k j`
- Open HELM Find Files: `SPC f f`
- Select a directory and press `C-l` (l = lower case L)

>split-window: Cannot split side window or parent of side window

**Comment by sdwolfz** [comment]
OK, looks like I still have work to do 😅.

I really have to dig deep and understand the code to solve this one... might take a while.

**Comment by sdwolfz** [comment]
@duianto For your case I have:
```elisp
(window-list) ; (#<window 10 on *helm find files*> #<window 2 on  *Minibuf-1*> #<window 4 on  *Treemacs-Framebuffer-1*> #<window 1 on *spacemacs*> #<window 6 on  *popwin-dummy*> #<window 8 on *Help*>)
(selected-window) ; #<window 10 on *helm find files*>
(previous-window (selected-window) 1) ; #<window 8 on *Help*>
(next-window (selected-window) 1) ; #<window 4 on  *Treemacs-Framebuffer-1*>
```

Evaluated for:
```elisp
((window-dedicated-p
    (setq prev-win (previous-window (selected-window) 1)))
  (with-helm-after-update-hook
    (and (window-live-p helm-persistent-action-display-window)
            (delete-window helm-persistent-action-display-window)))
  (split-window))
```

For a proper fix I need to understand https://github.com/emacs-helm/helm/issues/2050 and find a way to fix it without requiring splits.

**Comment by invsblduck** [comment]
Without looking at any code, this certainly is an interesting and intermittent bug.

Before finding this thread, it simply felt like it would get into a "wedged" state where it was just broken all the time, no matter what.

After reading this thread and toggling neotree window (closed/open), I am coincidentally not experiencing the symptom at all--I don't experience the problem whether neotree is focused or not, nor whether it's even open or not. And in this currently-working state, I don't experience the problem when a Help window is open either, as nicely detailed by @duianto above (following his reproduction steps exactly).

Very curious behavior. 

I am running spacemacs master from Aug 2019 (40024fe) on emacs 26.1-2 on Arch Linux. Just FYI.

**Comment by duianto** [comment]
I'm not able to reproduce the `cannot split window ...` issue when a help buffer is open. Maybe it's been fixed upstream.

### System info:
<details><summary>
Pop!_OS 19.10
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 08fdb02d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion c-c++ emacs-lisp git helm lsp markdown multiple-cursors org php
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>

<details><summary>
Windows 1903
</summary>
<pre>
#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 08fdb02d7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion c-c++ emacs-lisp git helm lsp markdown multiple-cursors org php
                 (shell :variables shell-default-height 30 shell-default-position 'bottom)
                 spell-checking syntax-checking treemacs version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG SOUND DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS FREETYPE XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS
</pre>
</details>

**Comment by lpsmith** [comment]
I just ran across this bug myself,  but

1.  I don't normally experience this bug
2.  When in helm `C-x C-f` it only effected directories, not files
3.  Restarting emacs managed to "fix" the problem.

**Comment by invsblduck** [comment]
@sdwolfz You kicked butt working on this issue. I followed all resulting PRs and linked issues (resulting in ~10 tabs); just wanted to say thank you for your help on that so far. 👍
