### ISSUE TITLE
Julia REPL editing errors

### ISSUE THREAD

**Issue by whilo** [syl20bnr/spacemacs#11821]
#### Description :octocat:

When typing `plo` in the Julia REPL the following messages show up in the
`*Messages*` buffer. @non-Jedi

#### Reproduction guide :beetle:
- Start Emacs with the julia layer enabled
- Open a Julia REPL
- type "plo" into the REPL

*Observed behaviour:* :eyes: :broken_heart:

The following shows up in the *Messages* buffer.

~~~
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (void-variable mode-line) [3 times]
Error during redisplay: (jit-lock-function 8462) signaled (invalid-regexp "Unmatched ) or \\)")
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (void-variable mode-line) [2 times]
Error during redisplay: (jit-lock-function 8462) signaled (invalid-regexp "Unmatched ) or \\)")
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (void-variable mode-line) [2 times]
Error during redisplay: (jit-lock-function 8462) signaled (invalid-regexp "Unmatched ) or \\)")
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (void-variable mode-line) [2 times]
Error during redisplay: (jit-lock-function 8462) signaled (invalid-regexp "Unmatched ) or \\)")
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (void-variable mode-line) [4 times]
~~~

At the same time when deleting characters in visual mode they pop up again once
we insert characters in insert mode after `plo` again. This happens in lock step with the above messages.

*Expected behaviour:* :heart: :smile:
Editing works and no errors show up in *Messages*.

#### System Info :computer:
- Julia 1.0.3
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 2c28c7d21)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(fsharp javascript html helm auto-completion better-defaults emacs-lisp git markdown
        (org :variables org-enable-reveal-js-support t)
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        shell-scripts spell-checking syntax-checking version-control clojure python latex bibtex go ess julia display)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

**Comment by gdkrmr** [comment]
I can confirm this, the numbers in `(jit-lock-function *)` are different and it happens when you type anything into the repl.

**Comment by gdkrmr** [comment]
I got a traceback applying the trick from [here](https://lists.gnu.org/archive/html/emacs-devel/2013-01/msg00166.html):

```
Debugger entered--entering a function:
* #f(compiled-function () #<bytecode 0xa49719>)()
  compilation--ensure-parse(456)
  font-lock-fontify-keywords-region(447 456 nil)
  font-lock-default-fontify-region(454 456 nil)
  font-lock-fontify-region(454 456)
  font-lock-after-change-function(454 455 0)
  term-emulate-terminal(#<process julia> "s")
```

**Comment by gdkrmr** [comment]
this should be fixed now

**Comment by whilo** [comment]
Hmm, I have updated everything, installed LanguageServer and reinitialized spacemacs and I still get the weird REPL editing behaviour without auto-comple and also "Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (void-variable mode-line)".

**Comment by gdkrmr** [comment]
this one is probably not the fault of the julia layer. How old is your .spacemacs file? Try diffing it with the reference one (`SPC f e D`) maybe you missed some changes.
