### ISSUE TITLE
Spacemacs installation is broken

### ISSUE THREAD

**Issue by AkashGanesan** [syl20bnr/spacemacs#12633]
I did a clone of spacemacs and it errors out on 

Package undo-tree is unavailable. Is the package name misspelled?

Emacs version : 26.1
Operating system: Ubuntu 19.04

**Comment by albru123** [comment]
This happened to me with broken Emacs Windows build, you could try running the latest official Emacs version from here: https://www.gnu.org/software/emacs/emacs.html

**Comment by duianto** [comment]
It's a problem with the current version of Emacs, it's marked as fixed for the next version 26.3+ (not released yet).

This issue has the current workaround:
Failed to download 'gnu' archive. Bad request. (Solution included) #12535

**Comment by albru123** [comment]
Interesting, I had this issue while on on 25.3, but on 26.2 everything works just fine.

**Comment by Great-Li-Xin** [comment]
Package undo-tree is unavailable, broke mine installation too.

**Comment by syl20bnr** [comment]
Going to fix it for everyone.

**Comment by syl20bnr** [comment]
Should be fixed in develop.

**Comment by syl20bnr** [comment]
Re-open as it was auto-closed when pushing the fix to master.

**Comment by syl20bnr** [comment]
I pushed a new fix to develop branch which should work for everybody.

**Comment by AkashGanesan** [comment]
I tried the develop branch but still get errors like below

===
--> installing package: async@spacemacs-bootstrap... [1/107]
Package async is unavailable. Is the package name misspelled?
--> installing package: bind-key@spacemacs-bootstrap... [2/107]
Package bind-key is unavailable. Is the package name misspelled?
--> installing package: bind-map@spacemacs-bootstrap... [3/107]
Package bind-map is unavailable. Is the package name misspelled?
--> installing package: diminish@spacemacs-bootstrap... [4/107]
Package diminish is unavailable. Is the package name misspelled?
--> installing package: dotenv-mode@spacemacs-bootstrap... [5/107]
Package dotenv-mode is unavailable. Is the package name misspelled?
--> installing package: evil@spacemacs-bootstrap... [6/107]
Package evil is unavailable. Is the package name misspelled?
--> installing package: hydra@spacemacs-bootstrap... [7/107]
Package hydra is unavailable. Is the package name misspelled?
∑
===

**Comment by duianto** [comment]
@AkashGanesan Have you pulled the latest commit on the develop branch?
https://github.com/syl20bnr/spacemacs/commits/develop

**Comment by AkashGanesan** [comment]
Yes.  I see the latest one.  Just did it now.

**Comment by duianto** [comment]
Does the messages buffer show any error messages before the package installation attempts start?

**Comment by AkashGanesan** [comment]
No. It does not.

**Comment by duianto** [comment]
What Emacs version are you using?

The last commenters problem in this issue:
Package emacs (yes, emacs) unavailable #10983
seems to have been caused by an old version of Emacs still running even though a newer version was installed.

**Comment by AkashGanesan** [comment]
I checked that as well. It's 26.1

**Comment by duianto** [comment]
Maybe a mirror will work:
https://github.com/d12frosted/elpa-mirror#usage-with-spacemacs
or
https://www.reddit.com/r/emacs/comments/cdei4p/failed_to_download_gnu_archive_bad_request/ettq00i/

**Comment by AkashGanesan** [comment]
This one doesn't work as well.  That's really strange.  I stuck this in init.el right in the beginning of the file.

**Comment by zaynetro** [comment]
The following fixed my Emacs 26.2

* Clone https://github.com/d12frosted/elpa-mirror
* Modify `dotspacemacs/user-init`

```lisp
(defun dotspacemacs/user-init ()
  "Initialization for user code:
This function is called immediately after `dotspacemacs/init', before layer
configuration.
It is mostly for variables that should be set before packages are loaded.
If you are unsure, try setting them in `dotspacemacs/user-config' first."
  ;; (setq configuration-layer-elpa-archives
  ;;         '(("melpa"    . "melpa.org/packages/")
  ;;           ("org"      . "orgmode.org/elpa/")))
  (setq configuration-layer-elpa-archives
          '(("melpa"    . "melpa.org/packages/")
            ("org"      . "orgmode.org/elpa/")
            ("gnu"      . "/Users/bond/Code/spacemacs-elpa-mirror/gnu")))
  )
```

**Comment by duianto** [comment]
Emacs 26.3 has been released, it might fix this issue.

**Comment by AkashGanesan** [comment]
I can confirm that I don't see the errors for emacs26.3. Closing this issue.

**Comment by Migacz85** [comment]
Hi, im not quite sure why but even when I have version 26.3, spacemacs don't see treemacs, multiple-cursor, and web-beautify packages. Even in help -> layers. And on main buffer I have error stating: 
                            Warnings:
                                - An error occurred while applying the theme "gruvbox-dark-soft", fallback on
                                  theme "spacemacs-dark". Error was: (file-missing Cannot open load file No such
                                  file or directory autothemer)      
                                - Please check the value of "dotspacemacs-themes" in your dotfile or open an issue
                                  so we can add support for the theme "gruvbox-dark-soft".      
                                - Unknown layer web-beautify declared in dotfile.      
                                - Unknown layer epub declared in dotfile.      
                                - Unknown layer multiple-cursors declared in dotfile.      
                                - Unknown layer treemacs declared in dotfile.      
                            
It don't see this packages even with fresh .spacemacs config file. Hm...

**Comment by duianto** [comment]
@Migacz85 It looks like your on the `master` branch.

The `multiple-cursors`, `treemacs`, and `web-beautify` layers are only available on the `develop` branch at the moment.

The `epub` layer is on the `master` branch but it's been moved on the `develop` branch from `layers/+misc/epub` to `layers/+readers/epub`

I'm not sure why it's shown as an unknown layer for you.

`gruvbox` theme issues seem to also have been fixed on the `develop` branch.

It's adviced to use the `develop` branch until the next Spacemacs version is released. But if you want to use the `master` branch then this comment might work to enable `gruvbox` themes on the `master` branch.
https://github.com/syl20bnr/spacemacs/issues/8871#issuecomment-308822752
