### ISSUE TITLE
Clean installed spacemacs cannot start with font-lock error

### ISSUE THREAD

**Issue by qqldd** [syl20bnr/spacemacs#13813]
#### Description :octocat:
user-error: Cannot enable hl-todo-mode without font-lock

#### Reproduction guide :beetle:
- Clean install spacemacs
- Start Emacs
- The Message buffer shows `user-error: Cannot enable hl-todo-mode without font-lock`

*Observed behaviour:* :eyes: :broken_heart:
The highlight doesn't work. If I do `C-SPC` and select some text, no highlight is there.

*Expected behaviour:* :heart: :smile:
The highlight should work.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.3
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 04b80d610)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(emacs-lisp helm multiple-cursors treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS JSON LCMS2

**Comment by NicholasKirchner** [comment]
Can confirm.  My system info:
* MacOS 10.15.6
* Emacs 26.3
* Spacemacs 0.200.13 (current master branch)
* vim editing style
* helm completion

**Comment by NicholasKirchner** [comment]
Things seem to be working for me now.  The PR request on the hl-todo repo has been reverted.

**Comment by cheese** [comment]
Met the same issue. One way to work around is to delete hl-todo and reinstall it from melpa-stable.

**Comment by qqldd** [comment]
This should be resolved as hl-todo repo reverted the change.

**Comment by pharpend** [comment]
I am still having this issue on a clean install of spacemacs. As a reference for others who aren't spacemacs gurus, this fixed it for me

```
$ cd .emacs.d
$ git fetch origin develop
$ git checkout develop
```

**Comment by rogermparent** [comment]
@pharpend I also encountered the same issue and fixed it the same way. Seemingly this issue also completely prevented me from using `emacsclient` as I'd have an issue with the message `error getting input from stdin` issue when trying to use a feature that takes input.

**Comment by erathorus** [comment]
Same issue for me too. But when I checked out to the `develop` branch the C/C++ layer was failed to load.

**Comment by rogermparent** [comment]
> Same issue for me too. But when I checked out to the `develop` branch the C/C++ layer was failed to load.

@erathorus I had to remove/reset my `.spacemacs` and reinstall everything when switching to `develop`, unfortunately. Thankfully Spacemacs makes it pretty painless to do so with the "suggest a layer on unidentified files" feature.

You may have already done this, but if not I hope it helps fix your problem.

**Comment by erathorus** [comment]
Thank you @rogermparent but unfortunately I tried that but nothing changes 😢 . I have raised the issue to `hl-todo-mode`. Hope it will work out somehow.
