### ISSUE TITLE
Showing only 8 colors in remote terminal

### ISSUE THREAD

**Issue by gdkrmr** [syl20bnr/spacemacs#14473]
The same spacemacs configuration works fine on my local computer but shows only 8 colors in the terminal on a remote machine. 
- I have `TERM=xterm-256color` set on both machines. 
- If I run `emacs -q` on the remote machine it can show the whole range of colors

**Comment by lebensterben** [comment]
Does any other programs show 256 colors?

**Comment by alexey0308** [comment]
@gdkrmr check the value of TERM in .spacemacs.env file (`SPS f e e`).

**Comment by lebensterben** [comment]
Also checks `TERMINFO` environment variable.
It's possible `TERM` Is correctly set but `TERMINFO` points to a wrong search path.

**Comment by gdkrmr** [comment]
`TERM=xterm-256color` in .spacemacs.env and `(getenv "TERM")` also returns the same. `TERMINFO` is unset, both on my local machine and on the remote machine. Not sure if related but `.spacemacs.env` shows `COLORTERM=truecolor`.

**Comment by lebensterben** [comment]
> Not sure if related but .spacemacs.env shows COLORTERM=truecolor.

It shouldn't. You can test it by commenting out the function that sources .spacemacs.env

**Comment by gdkrmr** [comment]
I have deleted `.spacemacs.env` and removed the line that loads that file from `.spacemacs` and nothing changed, still only 8 colors.

**Comment by gdkrmr** [comment]
Fixed it: I just copied the config from my personal computer where I am using `org-roam`. There was no `org-roam` directory and after removing
```
          org-enable-roam-support t
```
from the the `org` config layer it seems to work fine. `spacemacs` doesn't seem to handle missing org directories very gracefully, see also https://github.com/syl20bnr/spacemacs/issues/11263#issuecomment-531591170 and

**Comment by lebensterben** [comment]
>`spacemacs` doesn't seem to handle missing org directories very gracefully, see also https://github.com/syl20bnr/spacemacs/issues/11263#issuecomment-531591170.

So this is still an unfixed bug, though your issue is solved.

**Comment by gdkrmr** [comment]
> > `spacemacs` doesn't seem to handle missing org directories very gracefully, see also [#11263 (comment)](https://github.com/syl20bnr/spacemacs/issues/11263#issuecomment-531591170).
> 
> So this is still an unfixed bug, though your issue is solved.

Well, technically I solved my issue but you are right, the bug is still there. I have opened an issue for the bug.
