### ISSUE TITLE
Errors at startup: Required feature `popwin' was not provided

### ISSUE THREAD

**Issue by JJJollyjim** [syl20bnr/spacemacs#1475]
On a brand new Spacemacs install (exactly the command from the `README.md`) I'm getting errors on startup (after relaunching post-installation):

```
Error (use-package): guide-key-tip :init: Required feature `popwin' was not provided
Error (use-package): popwin :init: Symbol's function definition is void: popwin-mode
```

### Screenshot
![screenshot_2015-05-03_16-00-21](https://cloud.githubusercontent.com/assets/691552/7443598/859d4940-f1ad-11e4-87b9-a21baa9863d8.png)

### System info
```
$ emacs --version
GNU Emacs 24.5.1
[...]
```
```
$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```
```
$ uname -a
Linux jamiearch 4.0.1-1-ARCH #1 SMP PREEMPT Wed Apr 29 12:00:26 CEST 2015 x86_64 GNU/Linux
```

--

Happy to provide any more information to help resolve this. Thanks!

**Comment by syl20bnr** [comment]
Seems that popwin is not installed properly. I tried on my macbook with the homebrew version (24.4) and I don't have this issue.
Can you check your `~/.emacs.d/elpa` folder for a popwin folder ?

**Comment by JJJollyjim** [comment]
@syl20bnr Looks like its there

```
[~/.emacs.d/elpa/popwin-20150315.600]$ ls
popwin-autoloads.el  popwin.el	popwin.elc  popwin-pkg.el  popwin-pkg.elc
```

**Comment by syl20bnr** [comment]
oh that's it. If you wipeout the popwin folder and relaunch emacs, is it empty again ?

**Comment by JJJollyjim** [comment]
@syl20bnr It's not, and spacemacs launches successfully!

...but if I delete `.emacs.d`+`.spacemacs` and reinstall, the problem returns, so not just a fluke :cry:

**Comment by JJJollyjim** [comment]
```
[jamie@jamiearch Misc]$ diff -q popwin-post-rm popwin-pre-rm
Files popwin-post-rm/popwin-autoloads.el and popwin-pre-rm/popwin-autoloads.el differ
Files popwin-post-rm/popwin.el and popwin-pre-rm/popwin.el differ
Files popwin-post-rm/popwin.elc and popwin-pre-rm/popwin.elc differ
```

**Comment by syl20bnr** [comment]
That's really weird, maybe a bug in `packages.el`. It would be surprising that spacemacs causes this kind of download issue.

**Comment by tuhdo** [comment]
Yesterday a user also had this problem after I convinced him to switch to Spacemacs. After trying various methods awhile, I told him to checkout the `develop` branch and he said it fixed the issue. So maybe you should  try `develop` branch.

**Comment by JJJollyjim** [comment]
@tuhdo Can confirm that develop fixes things

**Comment by tuhdo** [comment]
Great to hear that. So, this can be labeled as `fixed in develop` :D

**Comment by syl20bnr** [comment]
mmmmh but why it is fixed in develop ? :-) I don't like when bugs magically disappear.

**Comment by JJJollyjim** [comment]
Hmm...


Is there an elisp function I can pass as an argument to emacs to setup Spacemacs, installing the packages (and have it exit when finished)? If so, I should be able to do an automatic `git bisect`.

**Comment by Jeel-Shah** [comment]
I'm still having this problem. I just checked out the develop branch and it continues to say `Required feature 'popwin' was not provided.` There is a popwin folder in my elpa but as another user said, popwin.el is empty. Any help would be very much appreciated.

**Comment by er1cwan** [comment]
@Jeel-Shah It's working to me. Thanks!

**Comment by acenode** [comment]
solved after remove 'popwin-xxxx' folder and restart emacs

**Comment by cars10w** [comment]
Had the same problem after a fresh installation (under Win 7).   Solved by deleting the elpa/popwin-* folder and restarting emacs. Thanks for the hint!

**Comment by DuanTzXavier** [comment]
@Jeel-Shah I think it's download error.After we delete that folder ,restart emacs ,it downloads that folder again.

Anyway,it works ,thanks

**Comment by ghwokai** [comment]
@Jeel-Shah thanks!It's work in win7

**Comment by rgb-24bit** [comment]
I encountered a similar bug in the develop branch, due to the use of the previous master, I did not find the develop branch of the package stored in the `elpa \ develop` folder, so ........

**Comment by xamenrax** [comment]
Try to delete wipeout the popwin folder, then launch Emacs with `emacs --insecure` to disable downloading packages through HTTPS and update.
