### ISSUE TITLE
Symbol’s value as variable is void: treemacs--buffer-name-prefix

### ISSUE THREAD

**Issue by jia-j-chen** [syl20bnr/spacemacs#17076]
When I try to use ranger with SPC a t r r, I got an message saying "Error (use-package): treemacs/:config: Symbol’s value as variable is void: treemacs--buffer-name-prefix", and ranger fails to start.

#### Reproduction guide
- Start Emacs
- SPC a t r r

*Observed behaviour:*
An message shows up, saying "Error (use-package): treemacs/:config: Symbol’s value as variable is void: treemacs--buffer-name-prefix", and ranger fails to start.

*Expected behaviour:*
ranger successfully starts.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 30.1
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. ec74a24d6)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(csv auto-completion better-defaults ess
     (chinese :variables chinese-enable-fcitx t chinese-fcitx-use-dbus t
              pyim-default-scheme 'microsoft-shuangpin
              chinese-enable-youdao-dict t)
     latex emacs-lisp ranger pdf git helm markdown multiple-cursors
     (org :variables org-startup-indented t org-indent-mode t)
     (shell :variables shell-default-height 30 shell-default-position 'bottom)
     spell-checking syntax-checking version-control python ipython-notebook
     (colors :variables colors-colorize-identifiers 'all))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NATIVE_COMP NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (void-variable treemacs--buffer-name-prefix)
  (member treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes)
  (if (member treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes) spacemacs-window-split-ignore-prefixes (setq spacemacs-window-split-ignore-prefixes (cons treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes)))
  (progn (spacemacs/define-evil-state-face "treemacs" "MediumPurple1") (if (eq treemacs-use-follow-mode t) (treemacs-follow-mode t) (treemacs-follow-mode -1)) (if (eq treemacs-use-follow-mode 'tag) (treemacs-tag-follow-mode t) (treemacs-tag-follow-mode -1)) (if treemacs-use-filewatch-mode (treemacs-filewatch-mode t) (treemacs-filewatch-mode -1)) (if (memq treemacs-use-git-mode '(simple extended deferred)) (treemacs-git-mode treemacs-use-git-mode) (treemacs-git-mode -1)) (if (member treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes) spacemacs-window-split-ignore-prefixes (setq spacemacs-window-split-ignore-prefixes (cons treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes))) (run-hooks 'use-package--treemacs--post-config-hook))
  (if (run-hook-with-args-until-failure 'use-package--treemacs--pre-config-hook) (progn (spacemacs/define-evil-state-face "treemacs" "MediumPurple1") (if (eq treemacs-use-follow-mode t) (treemacs-follow-mode t) (treemacs-follow-mode -1)) (if (eq treemacs-use-follow-mode 'tag) (treemacs-tag-follow-mode t) (treemacs-tag-follow-mode -1)) (if treemacs-use-filewatch-mode (treemacs-filewatch-mode t) (treemacs-filewatch-mode -1)) (if (memq treemacs-use-git-mode '(simple extended deferred)) (treemacs-git-mode treemacs-use-git-mode) (treemacs-git-mode -1)) (if (member treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes) spacemacs-window-split-ignore-prefixes (setq spacemacs-window-split-ignore-prefixes (cons treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes))) (run-hooks 'use-package--treemacs--post-config-hook)))
  (progn (if (run-hook-with-args-until-failure 'use-package--treemacs--pre-config-hook) (progn (spacemacs/define-evil-state-face "treemacs" "MediumPurple1") (if (eq treemacs-use-follow-mode t) (treemacs-follow-mode t) (treemacs-follow-mode -1)) (if (eq treemacs-use-follow-mode 'tag) (treemacs-tag-follow-mode t) (treemacs-tag-follow-mode -1)) (if treemacs-use-filewatch-mode (treemacs-filewatch-mode t) (treemacs-filewatch-mode -1)) (if (memq treemacs-use-git-mode '(simple extended deferred)) (treemacs-git-mode treemacs-use-git-mode) (treemacs-git-mode -1)) (if (member treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes) spacemacs-window-split-ignore-prefixes (setq spacemacs-window-split-ignore-prefixes (cons treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes))) (run-hooks 'use-package--treemacs--post-config-hook))) t)
  (condition-case err (progn (if (run-hook-with-args-until-failure 'use-package--treemacs--pre-config-hook) (progn (spacemacs/define-evil-state-face "treemacs" "MediumPurple1") (if (eq treemacs-use-follow-mode t) (treemacs-follow-mode t) (treemacs-follow-mode -1)) (if (eq treemacs-use-follow-mode 'tag) (treemacs-tag-follow-mode t) (treemacs-tag-follow-mode -1)) (if treemacs-use-filewatch-mode (treemacs-filewatch-mode t) (treemacs-filewatch-mode -1)) (if (memq treemacs-use-git-mode '(simple extended deferred)) (treemacs-git-mode treemacs-use-git-mode) (treemacs-git-mode -1)) (if (member treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes) spacemacs-window-split-ignore-prefixes (setq spacemacs-window-split-ignore-prefixes (cons treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes))) (run-hooks 'use-package--treemacs--post-config-hook))) t) ((debug error) (funcall use-package--warning189 :config err)))
  #f(lambda () :dynbind (condition-case err (progn (if (run-hook-with-args-until-failure 'use-package--treemacs--pre-config-hook) (progn (spacemacs/define-evil-state-face "treemacs" "MediumPurple1") (if (eq treemacs-use-follow-mode t) (treemacs-follow-mode t) (treemacs-follow-mode -1)) (if (eq treemacs-use-follow-mode 'tag) (treemacs-tag-follow-mode t) (treemacs-tag-follow-mode -1)) (if treemacs-use-filewatch-mode (treemacs-filewatch-mode t) (treemacs-filewatch-mode -1)) (if (memq treemacs-use-git-mode '(simple extended deferred)) (treemacs-git-mode treemacs-use-git-mode) (treemacs-git-mode -1)) (if (member treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes) spacemacs-window-split-ignore-prefixes (setq spacemacs-window-split-ignore-prefixes (cons treemacs--buffer-name-prefix spacemacs-window-split-ignore-prefixes))) (run-hooks 'use-package--treemacs--post-config-hook))) t) ((debug error) (funcall use-package--warning189 :config err))))()
  eval-after-load-helper("/home/chenj/.emacs.d/elpa/30.1/develop/treemacs-20250729.1429/treemacs.elc")
  run-hook-with-args(eval-after-load-helper "/home/chenj/.emacs.d/elpa/30.1/develop/treemacs-20250729.1429/treemacs.elc")
  do-after-load-evaluation("/home/chenj/.emacs.d/elpa/30.1/develop/treemacs-20250729.1429/treemacs.elc")
  #<subr require>(treemacs)
  apply(#<subr require> treemacs)
  require(treemacs)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\207" [require treemacs hl-line dired pcase] 2)
  treemacs-icons-dired-mode()
  run-hooks(change-major-mode-after-body-hook dired-mode-hook)
  apply(run-hooks change-major-mode-after-body-hook dired-mode-hook)
  run-mode-hooks(dired-mode-hook)
  dired-mode("~/Fun/Research/IdeasSurveys/Trunk/" "-alhF")
  dired-internal-noselect("~/Fun/Research/IdeasSurveys/Trunk/" nil)
  dired-noselect("/home/chenj/Fun/Research/IdeasSurveys/Trunk/")
  ranger-dir-buffer("/home/chenj/Fun/Research/IdeasSurveys/Trunk/" nil)
  ranger-make-parent((("/home/chenj/Fun/Research/IdeasSurveys/Trunk/Thoughts/" . "/home/chenj/Fun/Research/IdeasSurveys/Trunk/") . 1))
  ranger-setup-parents()
  ranger-setup()
  ranger-mode()
  ranger-find-file("/home/chenj/Fun/Research/IdeasSurveys/Trunk/Thoughts/")
  ranger()
  funcall-interactively(ranger)
  call-interactively(ranger nil nil)
  command-execute(ranger)
```

**Comment by sunlin7** [comment]
Should be fixed in https://github.com/syl20bnr/spacemacs/commit/af9c044e0900446d49b2b557286dcd73c01b0caf.

**Comment by jia-j-chen** [comment]
> Should be fixed in [af9c044](https://github.com/syl20bnr/spacemacs/commit/af9c044e0900446d49b2b557286dcd73c01b0caf).

Thanks! I have updated all packages with SPC f e U, and the problem is still there.

If I remove the treemacs files with `rm -fr .emacs.d/elpa/30.1/develop/treemacs-20250729.1429/` and restart emacs, then treemacs gets re-installed. Then, I can use ranger without a problem.

But, if I re-start emacs without removing the treemacs files, then the reported problem will appear again after the restart.

**Comment by fnussbaum** [comment]
> I have updated all packages with SPC f e U, and the problem is still there.

You also need to update Spacemacs itself via `git pull`. The revision in your system information above is from last year:

> Spacemacs branch: develop (rev. https://github.com/syl20bnr/spacemacs/commit/ec74a24d6ad1ed74917f6eed32136715781e3f37)

**Comment by jia-j-chen** [comment]
> > I have updated all packages with SPC f e U, and the problem is still there.
> 
> You also need to update Spacemacs itself via `git pull`. The revision in your system information above is from last year:

Great!, I did that, and the problem is gone. Thanks!

> 
> > Spacemacs branch: develop (rev. [ec74a24](https://github.com/syl20bnr/spacemacs/commit/ec74a24d6ad1ed74917f6eed32136715781e3f37))
