### ISSUE TITLE
emacs --daemon weird behaviour

### ISSUE THREAD

**Issue by CestDiego** [syl20bnr/spacemacs#1894]
Hello, I share this to know if other people are having the same issue:

when running emacs as daemon I get this:
![alt](https://i.imgur.com/5SA3hII.png)

And when opening an emacsclient sth feels off (note the coloring on the window numbers)
![alt](https://i.imgur.com/Ocy5IyD.png)

And then when running something that takes input (such as helm-projectile) I get the prompt at the terminal where the daemon is running >very weird:
![alt](https://i.imgur.com/UsCemWq.png)

Also, `SPC :` doesn't seem to be defined, etc, etc I don't know if this is a problem with spacemacs but it looks as if spacemacs is not fully loading while being called as a daemon.

**Comment by tuhdo** [comment]
Could you reproduce with stock Spacemacs?

**Comment by CestDiego** [comment]
No I can't ;_; which means...I'm the problem right? dayum ;_;

**Comment by tuhdo** [comment]
Not necessary. To find out, you can remove your personal config and private layer, and only leave the pre-configured layers active. Maybe there's a problem with a layer. If not, then, you now know where to look at :)

**Comment by CestDiego** [comment]
:) ye, I'm gonna disable all my layers. then I'll se what's up with that.

**Comment by CestDiego** [comment]
This is very weird, so I disable all my layers and just stay with spacemacs' ones, and then the problem rises again D: I know it stops after `keybindings`. And what's after that is
```
Loading /home/io/.emacs.d/.cache/recentf...done
Start checking for new version...
Open the quickhelp.

```

**Comment by CestDiego** [comment]
ok So I deleted the nyan-cat stuff that checked if emacs was running as a graphical system. and now I don't see the prompt at the terminal and `SPC :` is defined, buuuut still 

![alt](https://i.imgur.com/baYHN3A.png)

Shows that there is sth wrong in the modeline.

**Comment by syl20bnr** [comment]
@CestDiego what does the screenshot show ?

**Comment by CestDiego** [comment]
@syl20bnr normally I would be able to have the numbers in black background, what I feel here, is that when I make a new frame after running as a daemon, none of the graphical features work, (spacemacs logo doesn't show, nyancat, etc)

**Comment by robbyoconnor** [comment]
Affected by this -- just wanna be included

**Comment by mistnim** [comment]
my spacemacs when running as daemon can't find source code pro, there are problems and the mode-line doesn't have fancy graphic.

**Comment by CestDiego** [comment]
@mistnim unfortunately, running emacs as daemon spawns it as a service, and so all the loading is done as service of that :(

**Comment by syl20bnr** [comment]
I merged #2652 but I'm not sure it fixes completely this issue, does it ?

**Comment by CestDiego** [comment]
@syl20bnr initial report: Fonts are still a problem: 

[![alt](https://i.imgur.com/ny9qyyO.png)](https://i.imgur.com/ny9qyyO.png)

**Comment by CestDiego** [comment]
Also, how do we customize the variable `colors-enable-nyan-cat-progress-bar`?
if before its value was: 

```
 `,(display-graphic-p)
```

**Comment by CestDiego** [comment]
I get this when spawning `emacs --daemon`

```
Warning: due to a long standing Gtk+ bug
http://bugzilla.gnome.org/show_bug.cgi?id=85715
Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
Loading /home/jarvis/.emacs.d/core/core-load-paths.el (source)...
Loading /home/jarvis/.emacs.d/core/core-load-paths.el (source)...done
Loading /home/jarvis/.spacemacs.d/init.el (source)...
Loading /home/jarvis/.spacemacs.d/init.el (source)...done
(Spacemacs) Warning: Cannot find font "Knack PNFT Plus Font Awesome Plu"!
Loading /home/jarvis/.emacs.d/.cache/spacemacs-buffer.el (source)...
Loading /home/jarvis/.emacs.d/.cache/spacemacs-buffer.el (source)...done
Open the quickhelp.
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs-base/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs-base/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs-base/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs-base/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs-base/keybindings.el (source)...
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs-base/keybindings.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+window-management/spacemacs-layouts/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/+window-management/spacemacs-layouts/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+window-management/spacemacs-layouts/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+window-management/spacemacs-layouts/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs/config.el (source)...done
Loading /home/jarvis/.spacemacs.d/no-dots/funcs.el (source)...
Loading /home/jarvis/.spacemacs.d/no-dots/funcs.el (source)...done
Loading /home/jarvis/.spacemacs.d/blog/funcs.el (source)...
Loading /home/jarvis/.spacemacs.d/blog/funcs.el (source)...done
Loading /home/jarvis/.spacemacs.d/blog/config.el (source)...
Loading /home/jarvis/.spacemacs.d/blog/config.el (source)...done
Loading /home/jarvis/.spacemacs.d/utils/funcs.el (source)...
Loading /home/jarvis/.spacemacs.d/utils/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+tools/elfeed/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+tools/elfeed/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/nixos/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/nixos/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+tools/dash/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+tools/dash/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+source-control/version-control/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/+source-control/version-control/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+source-control/version-control/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+source-control/version-control/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+source-control/version-control/keybindings.el (source)...
Loading /home/jarvis/.emacs.d/layers/+source-control/version-control/keybindings.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+source-control/git/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+source-control/git/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+source-control/github/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+source-control/github/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/colors/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/colors/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+irc/erc/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+irc/erc/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+irc/rcirc/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/+irc/rcirc/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+irc/rcirc/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+irc/rcirc/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/org/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/org/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/auto-completion/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/auto-completion/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/auto-completion/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/auto-completion/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/spell-checking/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/spell-checking/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/spell-checking/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/spell-checking/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/syntax-checking/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/syntax-checking/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/syntax-checking/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/syntax-checking/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/shell/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/shell/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+window-management/eyebrowse/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+window-management/eyebrowse/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/clojure/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/clojure/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/clojure/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/clojure/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/emacs-lisp/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/emacs-lisp/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+config-files/ansible/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/+config-files/ansible/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+config-files/ansible/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+config-files/ansible/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/markdown/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/markdown/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/html/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/html/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/latex/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/latex/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/latex/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/latex/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/c-c++/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/c-c++/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/c-c++/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/c-c++/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/python/funcs.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/python/funcs.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/python/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/python/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/haskell/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/haskell/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/javascript/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/javascript/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+frameworks/react/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+frameworks/react/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/ruby/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/ruby/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+fun/games/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/+fun/games/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/spotify/config.el (source)...
Loading /home/jarvis/.emacs.d/layers/spotify/config.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/yaml/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/yaml/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+window-management/spacemacs-layouts/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+window-management/spacemacs-layouts/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs-base/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs-base/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+distribution/spacemacs/packages.el (source)...done
Loading /home/jarvis/.spacemacs.d/no-dots/packages.el (source)...
Loading /home/jarvis/.spacemacs.d/no-dots/packages.el (source)...done
Loading /home/jarvis/.spacemacs.d/appearance/packages.el (source)...
Loading /home/jarvis/.spacemacs.d/appearance/packages.el (source)...done
Loading /home/jarvis/.spacemacs.d/blog/packages.el (source)...
Loading /home/jarvis/.spacemacs.d/blog/packages.el (source)...done
Loading /home/jarvis/.spacemacs.d/org-cestdiego/packages.el (source)...
Loading /home/jarvis/.spacemacs.d/org-cestdiego/packages.el (source)...done
Loading /home/jarvis/.spacemacs.d/presentations/packages.el (source)...
Loading /home/jarvis/.spacemacs.d/presentations/packages.el (source)...done
Loading /home/jarvis/.spacemacs.d/soundcloud/packages.el (source)...
Loading /home/jarvis/.spacemacs.d/soundcloud/packages.el (source)...done
Loading /home/jarvis/.spacemacs.d/twitter/packages.el (source)...
Loading /home/jarvis/.spacemacs.d/twitter/packages.el (source)...done
Loading /home/jarvis/.spacemacs.d/utils/packages.el (source)...
Loading /home/jarvis/.spacemacs.d/utils/packages.el (source)...done
Loading /home/jarvis/.spacemacs.d/utils/extensions.el (source)...
Loading /home/jarvis/.spacemacs.d/utils/extensions.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+email/gnus/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+email/gnus/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+tools/elfeed/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+tools/elfeed/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/nixos/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/nixos/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+tools/dash/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+tools/dash/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+source-control/version-control/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+source-control/version-control/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+source-control/git/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+source-control/git/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+source-control/github/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+source-control/github/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/prodigy/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/prodigy/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/colors/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/colors/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/colors/extensions.el (source)...
Loading /home/jarvis/.emacs.d/layers/colors/extensions.el (source)...done
Loading /home/jarvis/.emacs.d/layers/chrome/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/chrome/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+irc/erc/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+irc/erc/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+irc/erc/extensions.el (source)...
Loading /home/jarvis/.emacs.d/layers/+irc/erc/extensions.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+irc/rcirc/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+irc/rcirc/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+irc/rcirc/extensions.el (source)...
Loading /home/jarvis/.emacs.d/layers/+irc/rcirc/extensions.el (source)...done
Loading /home/jarvis/.emacs.d/layers/restclient/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/restclient/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/org/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/org/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/org/extensions.el (source)...
Loading /home/jarvis/.emacs.d/layers/org/extensions.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+fun/emoji/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+fun/emoji/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+tools/wakatime/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+tools/wakatime/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/auto-completion/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/auto-completion/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/spell-checking/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/spell-checking/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/syntax-checking/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/syntax-checking/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/shell/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/shell/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+window-management/eyebrowse/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+window-management/eyebrowse/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/clojure/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/clojure/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/scheme/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/scheme/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+config-files/ansible/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+config-files/ansible/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/markdown/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/markdown/packages.el (source)...done
Loading /home/jarvis/.spacemacs.d/cp2k/extensions.el (source)...
Loading /home/jarvis/.spacemacs.d/cp2k/extensions.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/html/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/html/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/latex/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/latex/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/c-c++/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/c-c++/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/python/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/python/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/python/extensions.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/python/extensions.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/ipython-notebook/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/ipython-notebook/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/sql/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/sql/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/sql/extensions.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/sql/extensions.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/haskell/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/haskell/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/javascript/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/javascript/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+frameworks/react/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+frameworks/react/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/ruby/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/ruby/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+lang/extra-langs/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+lang/extra-langs/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+tools/ranger/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+tools/ranger/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+fun/selectric/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+fun/selectric/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/search-engine/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/search-engine/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+fun/xkcd/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+fun/xkcd/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+fun/games/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+fun/games/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+fun/games/extensions.el (source)...
Loading /home/jarvis/.emacs.d/layers/+fun/games/extensions.el (source)...done
Loading /home/jarvis/.emacs.d/layers/spotify/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/spotify/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/spotify/extensions.el (source)...
Loading /home/jarvis/.emacs.d/layers/spotify/extensions.el (source)...done
Loading /home/jarvis/.spacemacs.d/Monfoku/packages.el (source)...
Loading /home/jarvis/.spacemacs.d/Monfoku/packages.el (source)...done
Loading /home/jarvis/.emacs.d/layers/+tools/vagrant/packages.el (source)...
Loading /home/jarvis/.emacs.d/layers/+tools/vagrant/packages.el (source)...done
elfeed-org is set up to handle elfeed configuration.
(Spacemacs) Warning: Auto-evilication could not remap these functions in map `elfeed-search-mode-map':
   - `elfeed-search-fetch' originally mapped on `G'
Loading /home/jarvis/.emacs.d/elpa/mustache-20131117.1407/mustache-render.el (source)...
Loading /home/jarvis/.emacs.d/elpa/mustache-20131117.1407/mustache-lex.el (source)...
Loading /home/jarvis/.emacs.d/elpa/mustache-20131117.1407/mustache-lex.el (source)...done
Loading /home/jarvis/.emacs.d/elpa/mustache-20131117.1407/mustache-parse.el (source)...
Loading /home/jarvis/.emacs.d/elpa/mustache-20131117.1407/mustache-parse.el (source)...done
Loading /home/jarvis/.emacs.d/elpa/mustache-20131117.1407/mustache-render.el (source)...done
Error (use-package): ob :config: Invalid function: org-babel-header-args-safe-fn
Truncate long lines enabled

Starting new Ispell process /run/current-system/sw/bin/aspell with default dictionary...
Spacemacs is ready.
Restarting server
```

**Comment by CestDiego** [comment]
http://emacs.stackexchange.com/a/2564/5193 given this I can say that this fixes the issue using `~/.Xresources` I don't know how might it work in OSX, @syl20bnr do you have trouble with this?

**Comment by syl20bnr** [comment]
@CestDiego Can you test the last develop branch, I think I nailed it except for the window number and persp number, the rest should be consistent:
- font should be right
- spaceline separator should be right
- theme color should be right

@travisbhartwell thanks you for your wonderful macro :+1: 

@TheBB I'm not sure how I can fix the window number and persp number since they are handled by spaceline. For the unicode diminished lighter of minor modes I use a trick with:

```elisp
(unicodep (dotspacemacs|symbol-value dotspacemacs-mode-line-unicode-symbols))```

We could port this hack to spaceline although this feel awkward to bring spacemacs specific code in a stand alone package...

**Comment by CestDiego** [comment]
@syl20bnr  I get this:

[[!alt](https://i.imgur.com/jlKoI1r.png)](https://i.imgur.com/jlKoI1r.png)

Good job on the font, but now `nyan-mode` is not being used. Probably it has to do with the display-graphic-p condition? also the logo is not the spacemacs logo, but the text banner :(

**Comment by syl20bnr** [comment]
Let me try something for the logo :-)
I don't use the cat anymore, looking into it.

**Comment by CestDiego** [comment]
The cat and the logo might be related. I don't use the cat either, I just have it in case I want to show it, i disable it at startup with:

```elisp
  (when (configuration-layer/package-usedp 'nyan-mode)
    (nyan-mode -1))
```

Also note that the color in the workspace numbers is off, but I think that was pointed out already

**Comment by syl20bnr** [comment]
The logo should be OK with last develop.

**Comment by CestDiego** [comment]
that was fast omg

**Comment by syl20bnr** [comment]
@justbur thanks for the possibility to easily recreate the home buffer ;-)

**Comment by CestDiego** [comment]
> all the pieces start to come together

**Comment by syl20bnr** [comment]
I'm looking into the cat now, I hope we can do something about it.

**Comment by CestDiego** [comment]
Logo works! but there is a flash....

**Comment by CestDiego** [comment]
But now terminal Emacs is affected:

[![alt](https://i.imgur.com/Z1Flwo5.png)](https://i.imgur.com/Z1Flwo5.png)

**Comment by CestDiego** [comment]
it's hard because the home buffer has to be shared among EmacsClients D: D: Maaaaybe Having also a second *spacemacs-term*? :P Also I propose to change the default banner to the ascii version of the logo :P

**Comment by syl20bnr** [comment]
Ok should be good for the cat, remove the code that disable the cat and relaunch a daemon with a GUI and/or terminal client.

**Comment by syl20bnr** [comment]
Basically I only re-enable the cat for the first GUI client... don't know if it will be robust enough.

**Comment by syl20bnr** [comment]
There are still some issues with italic and some colors (helm for instance) but maybe we cannot do much about it...

**Comment by syl20bnr** [comment]
> But now terminal Emacs is affected

I don't mind having no logo in terminal client. If one use both GUI and terminal client, chances are that terminal ones are for quick edit so a missing banner is not such a big deal :-)

**Comment by CestDiego** [comment]
:) I'm so happy with this.. the only problem I have is the number color, and also I haven't really used terminal Emacs before, is the color of the evilified state cursor supposed to have trouble? it looks just the same as the normal state one

**Comment by syl20bnr** [comment]
Yes the cursor color is always the same, we had a package to change the shape of the cursor but it was buggy so we had to remove it.
For the window and workspace numbers color I suppose this is the same kind of issue as the helm source header. For the unicode window and workspace numbers this might be fixed in spaceline, not really sure how to fix this for now.

**Comment by syl20bnr** [comment]
> I'm so happy with this

Me too, thanks again @travisbhartwell :-)

**Comment by CestDiego** [comment]
I say after the number thing is fixed we can close this issue. But great job on this! :)

**Comment by CestDiego** [comment]
What problem is in helm with italics?

**Comment by syl20bnr** [comment]
I have underlines, but this is also the case with regular emacs GUI so I guess this is my emacs built/font.

**Comment by TheBB** [comment]
> @TheBB I'm not sure how I can fix the window number and persp number since they are handled by spaceline.

Well, first we need to find out which code needs to be run post-GUI. I'm sure that setting those variables won't change anything, since they are set in a hook and so should be even more up to date than they strictly speaking need to be.

**Comment by alcinos** [comment]
Hi,
Sorry to reopen this, but apparently I'm still getting issues with the powerline when starting in daemon mode.
The weird thing is that it looks normal on the *spacemacs* buffer, but in a regular file buffer it looks weird, as reported by the previous screenshots. Any thoughts ?

**Comment by TheBB** [comment]
It's not definite but since there has been a wide variety of issues reported here, and since many of them have been fixed in develop now, I am labeling as such. If there are still problems please open more specific issues.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.
