### ISSUE TITLE
Auto-completion misbehaving in Elixir

### ISSUE THREAD

**Issue by koudelka** [syl20bnr/spacemacs#1898]
When confirming one of the auto-completion suggestions, the entire statement is replaced by the suggestion.

![elixir_broken_auto_completion](https://cloud.githubusercontent.com/assets/30394/8045134/27dada5c-0de6-11e5-888d-27d8b257ba08.gif)

**Comment by koudelka** [comment]
My config layers:

```lisp
dotspacemacs-configuration-layers
'(
  syntax-checking
  (company-mode :variables
                company-idle-delay nil)
  erlang-elixir
  auto-completion
  dockerfile
  html
  javascript
  (ruby :variables
        ruby-version-manager `rbenv
        ruby-enable-ruby-on-rails-support t)
  osx
)
```

**Comment by koudelka** [comment]
I think this has something to do with alchemist starting my Mix application. If I comment out the `mod` key in my `mix.exs`'s application config, the completion works as expected. Maybe there's a timeout somewhere that's being hit?

If you clone https://github.com/koudelka/elixir-riemann, and just play around in `mix.exs`, you should be able to reproduce the bug.

cc @tonini, @st23am

**Comment by koudelka** [comment]
I think this is related to https://github.com/tonini/alchemist.el/issues/87.

**Comment by syl20bnr** [comment]
Have you updated your packages ?

**Comment by st23am** [comment]
After changing my config to match yours and running update on my packages from the *spacemacs* buffer I got some initial weirdness in the form of compile errors in Alchemist: https://gist.github.com/st23am/368a40fb30ba9894cded

After that I reordered my configuration layer to look like this
```
 dotspacemacs-configuration-layers '(editorconfig
                                     syntax-checking
                                     auto-completion
                                     (company-mode :variables
                                                   company-idle-delay nil)
                                     erlang-elixir
                                     (ruby :variables
                                           ruby-version-manager `rbenv
                                           ruby-enable-ruby-on-rails-support t)
                                     clojure
                                     javascript
                                     haskell
                                     git
                                     dash
                                     osx
                                     html
                                     org
                                     colors
                                     themes-megapack)
````
I then closed and reopened Emacs, created a foo.ex file. I had to enable company-mode for some reason but, I was able to get completion to work. I'm curious if what @syl20bnr suggests above fixes the issue or if you've already tried that. Also I don't think the order of the layers there should matter but maybe give it a try  ¯\_(ツ)_/¯ . Hope this helps and you are able to get this working!

**Comment by syl20bnr** [comment]
@koudelka can you get the latest develop and update your packages ? I fixed the auto-completion activation mentioned by @st23am.
**IMPORTANT** I split the layer `erlang-elixir` into 2 layers:
- elrang
- elixir
Be sure to replace `erlang-elixir` by `elixir` in your dotfile.

Also in your dotfile remove the line:
```elisp
(company-mode :variables
                company-idle-delay nil)
```
And move it to your `dotspacemacs/config`
```elisp
(setq  company-idle-delay nil)
```

**Comment by larshesel** [comment]
I just want to mention I've experienced something similar to what @koudelka is experiencing. Basically my autocomplete would exhibit exactly the same behaviour and I traced it so far as that I found it depends on the code that I'm looking at. For instance I had a phoenix project and in which the completion was broken. If I moved the file I was trying to edit outside of the project into say /tmp/ then completion would work.

**Comment by koudelka** [comment]
@st23am I've tried rejigging the order of the layers, no go.

@syl20bnr At c969555 the problem remains with my layers config as:
```
dotspacemacs-configuration-layers
'(
    syntax-checking
    company-mode
    elixir
    auto-completion
    dockerfile
    html
    javascript
    (ruby :variables
        ruby-version-manager `rbenv
        ruby-enable-ruby-on-rails-support t)
    osx
)
```

I may have discovered a clue. It seems that when my application uses Elixir's `Logger` module at startup, completion behaves in that odd manner. I've tried printing to both stdout and stderr with `IO.puts/2`, thinking that it could be console output that's interfering, but that doesn't seem to be the case.

You can recreate the issue with a tiny elixir project, like so:

`mix new test`

in lib/test.ex:
```elixir
defmodule Test do
  require Logger
  use Application

  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    Logger.warn "break"

    Supervisor.start_link([], strategy: :one_for_one)
  end
end
```

in mix.exs, change the `application` function to:
```elixir
  def application do
    [
      mod: {Test, []},
      applications: [:logger]
    ]
  end
```

**Comment by tonini** [comment]
@koudelka @larshesel Thanks for reporting to this issue.

Alchemist v1.0 will fix these kinds of issues because it will use a separated server for functionality like completion outside of the project. 

There is already a [Alpha branch](https://github.com/tonini/alchemist.el/pull/102) where you could test it out. 

Thans for the patience and support :heart:

**Comment by syl20bnr** [comment]
@tonini Thanks to the heads up :+1:

**Comment by koudelka** [comment]
@tonini thanks dude :)

**Comment by larshesel** [comment]
I'm happily using the alchemist-v1.0 alpha branch and so far it rocks. It's really, really fast! And so far I haven't experienced any completion problems.

@tonini is doing some great work there!

**Comment by benjamintanweihao** [comment]
Sweet! Slightly stupid question: how do you specify the branch to be 1.0?

**Comment by larshesel** [comment]
@koudelka Sorry for going off-topic here!

@benjamintanweihao if you do a git clone of the alchemist repo you can afterward do a `git checkout alchemist-v1.0`. if you need more help you can find me as `larshesel` on the #elixir-lang irc channel :)

**Comment by koudelka** [comment]
this is fixed in alchemist 1.0, thanks @tonini! <3
