### ISSUE TITLE
spacemacs/ace-buffer-links: Symbol's function definition is void: ali-generic

### ISSUE THREAD

**Issue by QiBaobin** [syl20bnr/spacemacs#1924]
When I called spacemacs/ace-buffer-links in *Spacemacs* buffer, the error was raised.

**Comment by QiBaobin** [comment]
Duplicated with #1538

**Comment by QiBaobin** [comment]
Not fixed.

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2015-05-21

Commits in HEAD
5363922 * HEAD -> develop origin/develop checkversion/develop Move desktop-mode config to `:config`
c9fe922 * Change default desktop save location.
4c79f5e * Give titles for documents in SPC f e h
173894f * Move file encoding code into a function

**Comment by syl20bnr** [comment]
I have it too but not on all my boxes. I'm pretty sure that wiping out the elpa directory should fix it though.

**Comment by QiBaobin** [comment]
I removed elpa directory and cleaned the repo directory, still not work.
