### ISSUE TITLE
magit-next create branch the powerline mode line branch name doesn't update

### ISSUE THREAD

**Issue by zilongshanren** [syl20bnr/spacemacs#2172]
When create a new branch and switch to the branch with `b B` after magit-status popup, the powerline git branch name doesn't update.

**Comment by syl20bnr** [comment]
For reference, this was already the case with previous commit.

**Comment by PierreR** [comment]
:+1: 

Actually whenever you use `magit-checkout´ to switch from one branch to another, the powerline won't refresh and it will give you misleading information.

Tested with
##### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.0
- Spacemacs branch: develop (rev. cd7bf33)

This is quite annoying.

**Comment by StreakyCobra** [comment]
I just reproduced it on `develop`. @TheBB it is something to do on spaceline, or to report upstream?

**Comment by TheBB** [comment]
It's not really a spaceline bug, it's somewhere in the integration between magit and vc. But of course we can provide a workaround either in Spacemacs or in Spaceline (probably Spacemacs).

I think @justbur found something that worked in Emacs 25. I can't find it :-(

**Comment by justbur** [comment]
There's a function that's called something like vc-refresh-state (name changes between 24 and 25) that needs to be called. I think magit should probably do it but maybe there's a hook that can be used.

**Comment by StreakyCobra** [comment]
Should we report to magit then, or do we do it on our side?

**Comment by justbur** [comment]
Maybe it's not technically a magit issue actually because it doesn't affect
magit functionality. Just deal with it here I'd say.

**Comment by TheBB** [comment]
Try setting `auto-revert-check-vc-info` to `t`.

Seems this might be caused when changing the branch doesn't cause the content of the file to change. Then `auto-revert` won't do anything.

**Comment by synic** [comment]
Just a note.  `auto-revert-check-vc-info` did work to fix this issue for me.  However, the next few days were spent with me trying to debug why emacs was constantly taking up 20+% of my cpu.  

This was the setting that caused it, for sure.

**Comment by maple-leaf** [comment]
@TheBB yes. The branch name will not update if file content has not diff between two branch.

**Comment by ZzAntares** [comment]
In the mean time if anyone is interested I have a key binding to call this function:

```
;; Source: http://www.emacswiki.org/emacs-en/download/misc-cmds.el
(defun revert-buffer-no-confirm ()
    "Revert buffer without confirmation."
    (interactive)
    (revert-buffer t t))
```

It will update the branch name displayed in the powerline, but be careful if you have unsaved changes in the buffer those will be gone.

**Comment by tarsius** [comment]
The costs of keeping this information up-to-date are very high and the benefit is very small. I therefore suggest that you stop worrying and start to love the outdated information. Or if it continues to bother you too much, that you simply remove it. Then at least it won't be *outdated*.

There is a [Magit FAQ entry](https://github.com/magit/magit/blob/master/Documentation/magit.org#the-mode-line-information-isnt-always-up-to-date) and I also just added [a new page](https://github.com/magit/magit/wiki/magit-update-uncommitted-buffer-hook) to the Magit wiki for those users who care deeply about this part of the mode-line being up-to-date and are willing to make the necessary investment.

----

If I were you I would probably close this issue.

**Comment by tarsius** [comment]
I might eventually do something about this, see magit/magit#2687.

**Comment by osenvosem** [comment]
The issue still persists.

**Comment by shae128** [comment]
I still have the same issue.

**Comment by damien-biasotto** [comment]
I'm not using Spacemacs (for now) but  I fixed this behaviour by advising some magit functions:

`;;Magit advice
(require 'magit)
(defun refresh-vc-state (&rest r) (message "%S" (current-buffer))(vc-refresh-state))
(advice-add 'magit-checkout-revision :after 'refresh-vc-state '((name . "magit-refresh-on-checkout-revision")))
(advice-add 'magit-branch-create :after 'refresh-vc-state '((name . "magit-refresh-on-branch-create")))
(advice-add 'magit-branch-and-checkout :after 'refresh-vc-state '((name . "magit-refresh-on-checkout-and-branch")))
(advice-add 'magit-branch-or-checkout :after 'refresh-vc-state '((name . "magit-refresh-on-branch-or-checkout")))`


And now if you're checking out or creating a branch,  the git modeline will be refreshed..

**Comment by roeeyn** [comment]
@damien-biasotto where should I put that function? I'm using spacemacs, and the issue still persists 😢

**Comment by duianto** [comment]
@roeeyn damien-biasotto's suggestion (modified), can be added to the `dotspacemacs/user-config` section in your `.spacemacs`.

#### Before
https://gist.github.com/damien-biasotto/b26f47bdfc7a8a7c76107e2160f57591
```elisp
;;Trigger a refresh of vc-modeline  on some magit functions

(require 'magit)
(defun refresh-vc-state (&rest r) (message "%S" (current-buffer))(vc-refresh-state))
(advice-add 'magit-checkout-revision :after 'refresh-vc-state '((name . "magit-refresh-on-checkout-revision")))
(advice-add 'magit-branch-create :after 'refresh-vc-state '((name . "magit-refresh-on-branch-create")))
(advice-add 'magit-branch-and-checkout :after 'refresh-vc-state '((name . "magit-refresh-on-checkout-and-branch")))
(advice-add 'magit-branch-or-checkout :after 'refresh-vc-state '((name . "magit-refresh-on-branch-or-checkout")))
```
This might be where damien-biasotto got the suggestion from:
https://www.reddit.com/r/emacs/comments/d2j8n3/advising_some_magit_functions_to_trigger/

#### After
```elisp
  ;; Trigger a refresh of vc-modeline  on some magit functions
  (with-eval-after-load 'magit
   (defun refresh-vc-state (&rest r) (message "%S" (current-buffer))(vc-refresh-state))
   (advice-add 'magit-checkout :after 'refresh-vc-state '((name . "magit-refresh-on-checkout")))
   (advice-add 'magit-branch-create :after 'refresh-vc-state '((name . "magit-refresh-on-branch-create")))
   (advice-add 'magit-branch-and-checkout :after 'refresh-vc-state '((name . "magit-refresh-on-checkout-and-branch")))
   (advice-add 'magit-branch-or-checkout :after 'refresh-vc-state '((name . "magit-refresh-on-branch-or-checkout"))))
```

#### Modifications:
- The `(require 'magit)` line was changed to: `with-eval-after-load 'magit`
I don't know if there's a difference but other package specific configurations have used `with-eval-after-load` to load them after a package has loaded.
- Changed:
`(advice-add 'magit-checkout-revision :after 'refresh-vc-state '((name . "magit-refresh-on-checkout-revision")))`
to:
`(advice-add 'magit-checkout :after 'refresh-vc-state '((name . "magit-refresh-on-checkout")))`
because there doesn't seem to be a function with the name: `magit-checkout-revision`
maybe it's been renamed.

With the advice above evaluated, the mode line branch name updates in the current buffer, when:
- An existing branch is checked out `SPC g m b b`
- Or when a new branch is created and checked out `SPC g m b c`
(`SPC g m` calls `magit-dispatch`, which opens the Magit `Transient and dwim commands popup`, where `b` opens the Magit Branch popup.

<details><summary>
Windows 10, System Info (Click to expand)
</summary>
<pre>
#### System Info :computer:
- OS: windows-nt
- Emacs: 27.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. b83eb11e3)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(autohotkey command-log emacs-lisp git haskell helm
            (javascript :variables javascript-backend 'lsp)
            lsp multiple-cursors org
            (python :variables python-backend 'lsp python-lsp-server 'mspyls)
            shell version-control treemacs)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY W32NOTIFY ACL GNUTLS LIBXML2 HARFBUZZ ZLIB TOOLKIT_SCROLL_BARS MODULES THREADS JSON PDUMPER LCMS2 GMP

</pre>
</details>

**Comment by lebensterben** [comment]
Is this still a bug?
