### ISSUE TITLE
Clojure navigation in evil-lisp-state

### ISSUE THREAD

**Issue by jdwaterson** [syl20bnr/spacemacs#2307]
Still new to Spacemacs, and many thanks for the excellent work on it, but it seems to me that evil-lisp-state has a fairly big weakness when dealing with Clojure. Is this an issue, or just a design decision that I'm unaware of?

The problem is that the structural navigation (on the j and k keys in evil-lisp-state) doesn't treat square brackets or curly braces as significant and just skips right over them. Unlike in most other Lisps, these characters (especially square brackets) are fundamental to the way that Clojure is organised, and so lisp-state becomes difficult to use.

For example, if I want to slurp something into an argument list (delimited with square brackets) then I frequently end up hopping between modes several times just to get my cursor into the right place. It's very fiddly.

Is this something that's been observed before, and is it likely to be addressed?

**Comment by sooheon** [comment]
AFAIK evil-lisp-state is still a work in progress, and elisp seems to be the main target, rather than clojure. The movement paradigm has changed once or twice. I assume @syl20bnr would be open to PRs, or for a more feature complete (currently) package with good clojure support, try [lispy](https://github.com/abo-abo/lispy). It's another "mode" to learn, and it's not quite vi-keys, but it's extremely well thought out and flows very well.

**Comment by jdwaterson** [comment]
Thanks for the tip about Lispy, I'll look into it. Would still love to hear whether improved Clojure support for evil-lisp-state is already in planning somewhere?

**Comment by axsk** [comment]
I totally agree jdwaterson. There is the clojure config in contrib/!lang/clojure.
Can't one add the desired brackets in there as delimiter characters for clojure state?

**Comment by syl20bnr** [comment]
Should be fixed in version 8.2 of `evil-lisp-state`.

**Comment by vendethiel** [comment]
The problem still exists for `[]` for e.g. `SPC k J` (won't join `[[foo bar]]` when cursor is on the inner `[`.

Should I open another issue for that?
