### ISSUE TITLE
develop - anaconda-mode issue

### ISSUE THREAD

**Issue by kdheepak89** [syl20bnr/spacemacs#2917]
I'm getting the following issue when using the latest develop branch 

```
error in process sentinel: apply: Setting current directory: No such file or directory, /Users/$USERNAME/.emacs.d/anaconda-mode/0.1.1
error in process sentinel: Setting current directory: No such file or directory, /Users/$USERNAME/.emacs.d/anaconda-mode/0.1.1
```

**Comment by TheBB** [comment]
https://github.com/proofit404/anaconda-mode/issues/104

**Comment by cpaulik** [comment]
I'm working on adapting the layer. For me completion is working but the commands have changed.

**Comment by cpaulik** [comment]
For me setting `python-shell-interpreter` to `python` from `ipython` solved this problem. As did switching to a virtualenv for some reason.

**Comment by tuxador** [comment]
same issue here, it's my first attempt to use (emacs) spacemacs in a daily basis, i thought that it was a **pbkac** ^_^

**Comment by syl20bnr** [comment]
Does it happen only on develop or is it also an issue on master ?

**Comment by cpaulik** [comment]
I would guess that this happens on both branches since it is related to the big anaconda-mode update.

**Comment by synic** [comment]
How are you setting it?  In spacemacs, having the following in my `user-config`:

```lisp
(setq python-shell-interpreter 'python)
```

does *not* fix the problem for me

**Comment by cpaulik** [comment]
I've set it manually after loading a python file. It was only necessary to set this once because as soon as the `~/.emacs.d/anaconda-mode...` stuff is there it worked for me regardless of the setting.

`(setq python-shell-interpreter "python")` should to the trick. But make sure you do this after the python layer is loaded, otherwise it will be overwritten

**Comment by synic** [comment]
Ah, setting it after worked, though I had to install anaconda-mode into the virtualenv.   I am now getting the following error:

```
[TerminalIPythonApp] WARNING | File not found: u'anaconda_mode.py'
[TerminalIPythonApp] WARNING | File not found: u'anaconda_mode.py'
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'anaconda_mode.py': [Errno 2] No such file or directory
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'anaconda_mode.py': [Errno 2] No such file or directory
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'anaconda_mode.py': [Errno 2] No such file or directory
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'anaconda_mode.py': [Errno 2] No such file or directory
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'anaconda_mode.py': [Errno 2] No such file or directory
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'anaconda_mode.py': [Errno 2] No such file or directory
```

**Comment by synic** [comment]
Doing the following fixes that last error:

```elisp
  (add-hook 'python-mode-hook
    (lambda ()
        (setq python-shell-interpreter "python")
        (setq anaconda-mode-server-script
              "/usr/local/lib/python2.7/site-packages/anaconda_mode.py")))
```

**Comment by beardedprojamz** [comment]
I *think* this is working now - on latest version of the package. https://github.com/proofit404/anaconda-mode/issues/104#issuecomment-138557779

**Comment by cpaulik** [comment]
It is not yet working for me. I still have to set `python-shell-interpreter` to `python` for the first time.

**Comment by beardedprojamz** [comment]
Yeah, i'm not getting the originally reported error, but autocomplete is hosed for sure.

**Comment by mbertheau** [comment]
Can we use quelpa to use an earlier, working version of anaconda-mode until this is sorted out?

**Comment by cpaulik** [comment]
This should be fixed in the latest version. At least it works for me now with both `python` and `ipython`

**Comment by pedrovanzella** [comment]
Still broken for me.

Running the latest (as of 09/23) version of Develop.

**Comment by cpaulik** [comment]
@pedrovanzella Are you also running the latest anaconda-mode?

**Comment by pedrovanzella** [comment]
@cpaulik yes, I should be. Just to be sure, I deleted everything inside `elpa` and restarted emacs, to reinstall everything. Still, the same behaviour.

**Comment by cpaulik** [comment]
hmm. Do you get the exact same error messages as OP?

What is the value of your `python-shell-interpreter`?

**Comment by pedrovanzella** [comment]
I never changed `python-shell-interpreter`.

I get
    eldoc error: (error 127.0.0.1%3anil/80 nodename nor servname provided, or not known) [2 times]

Which is the message reported in #2915, which is marked as a dupe of this one.

**Comment by cpaulik** [comment]
Ok, I do get the same error message but autocompletion works fine. So if autocompletion does not work for you then I will have to check where this error message comes from. I've never bothered since it only spams the messages buffer in my case.

**Comment by pedrovanzella** [comment]
Autocomplete doesn't work for me.

I've checked and I have anaconda-mode 0.1.1 installed both on Python3 and Python2, both provided by homebrew. The iPython on my path is Python 3.5's.

Would any other log help you?

**Comment by cpaulik** [comment]
Normally you do not need to install the anaconda-mode python package. It should be automatically installed into the value of `anaconda-mode-server-directory` which should be `~/.emacs.d/.cache/anaconda-mode/0.1.1`

I've just tested on Python 3.5 and it works. You also need a working pip but that should be a given in python 3.5

**Comment by pedrovanzella** [comment]
> which should be `~/.emacs.d/.cache/anaconda-mode/0.1.1`

That's interesting. There's no such directory. There is an `anaconda-mode` inside `~/.emacs.d`, with a directory named `0.1.1` inside of it, but it's empty. Could that be why?

**Comment by cpaulik** [comment]
The directory for anaconda mode was changed with https://github.com/syl20bnr/spacemacs/commit/c505fde5e4799c701826c260782df0631e04f4cd 20 hours ago. Are you sure you have this commit?

I would try to uninstall the anaconda mode packages that you installed manually and also delete the `anaconda-mode` folder in `.emacs.d`.

After a spacemacs restart and opening a python file anaconda mode should install all the packages it needs. 

You can follow what anaconda mode does in the `*anaconda-mode*` buffer. So please post the contents of this buffer if the problems persist.

**Comment by pedrovanzella** [comment]
Yes, I have that commit, and four or five that came after it.

I closed emacs, deleted the `anaconda-mode` folder, ran `pip uninstall anaconda-mode` and `pip3 uninstall anaconda-mode`, and opened emacs again.

This is what I get on my `*anaconda-mode*` buffer:

```
[TerminalIPythonApp] WARNING | File not found: 'anaconda_mode.py'
Collecting anaconda-mode==0.1.1
Collecting jedi>=0.9.0 (from anaconda-mode==0.1.1)
  Using cached jedi-0.9.0-py2.py3-none-any.whl
Collecting service-factory>=0.1.2 (from anaconda-mode==0.1.1)
Collecting six (from service-factory>=0.1.2->anaconda-mode==0.1.1)
  Using cached six-1.9.0-py2.py3-none-any.whl
Installing collected packages: jedi, six, service-factory, anaconda-mode
[31mException:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 242, in move_wheel_files
    name, user=user, home=home, root=root, isolated=isolated
  File "/usr/local/lib/python3.5/site-packages/pip/locations.py", line 192, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install.py", line 247, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both")
distutils.errors.DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both[0m
```

**Comment by cpaulik** [comment]
This might be an error with some combination of python and your Mac OS X or something.

The shell command that anaconda mode runs to install its dependencies is:

`python -c "import pip; pip.main(['install', '-t', '.', 'anaconda-mode == 0.1.1'])"`

Can you try this in a folder into which you don't mind a few python packages installed if it works.

The above command works with Python 3.5/2.7/3.3 etc. on Ubuntu 14.04. Please raise this upstream if this fails.

**Comment by pedrovanzella** [comment]
That doesn't work either. Seems to be a problem either with my system or upstream.

Thanks for taking the time to figure this out (:

**Comment by cpaulik** [comment]
In the meantime can you try running `pip install -t . anaconda-mode==0.1.1` in your `.emacs.d/.cache/anaconda-mode/0.1.1/` folder? It this works then maybe autocompletion will work

**Comment by pedrovanzella** [comment]
I found a solution for this problem here: http://stackoverflow.com/questions/24257803/distutilsoptionerror-must-supply-either-home-or-prefix-exec-prefix-not-both

So `python -c "import pip; pip.main(['install', '-t', '.', 'anaconda-mode == 0.1.1'])"` runs fine now.

My `*anaconda-mode*` buffer now reads `anaconda_mode port 9000`.

Still, for some reason, a `anaconda-mode` folder is created inside `~/.emacs.d`, not `~/.emacs.d/.cache`.

Also, autocomplete doesn't work.

**Comment by cpaulik** [comment]
I don't know what else to try. if anaconda mode is running on port 9000 then autocompletion should work.

**Comment by pedrovanzella** [comment]
I deleted the `anaconda-mode`  folder, as well as the `elpa` folder and started emacs again.

My `*anaconda-mode*` buffer, when opening a python file for the first time, is this:

```
Collecting anaconda-mode==0.1.1
Collecting service-factory>=0.1.2 (from anaconda-mode==0.1.1)
Collecting jedi>=0.9.0 (from anaconda-mode==0.1.1)
  Using cached jedi-0.9.0-py2.py3-none-any.whl
Collecting six (from service-factory>=0.1.2->anaconda-mode==0.1.1)
  Using cached six-1.9.0-py2.py3-none-any.whl
Installing collected packages: six, service-factory, jedi, anaconda-mode
Successfully installed anaconda-mode jedi-0.9.0 service-factory-0.1.2 six-1.9.0
[0;31mOut[[1;31m1[0;31m]: [0m0
anaconda_mode port 9000
127.0.0.1 - - [24/Sep/2015 12:44:40] ================================================================================
Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt_with_whitespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '__parser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'ParserNode' object has no attribute '_remove_last_newline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 100, in apply
    result = method(**params)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/anaconda_mode.py", line 59, in complete
    return script.completions()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 409, in _parse
    self.current_node.remove_last_newline()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 228, in remove_last_newline
    self.parser.remove_last_newline()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/__init__.py", line 374, in remove_last_newline
    newline = newline.get_previous()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/tree.py", line 182, in get_previous
    i = c.index(self)
ValueError: <Whitespace: > is not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "<string>", line 2, in raise_from
service_factory.exceptions.ServiceException: (500, '{"error": {"message": "Server error", "code": -32000, "data": "ValueError(\'<Whitespace: > is not in list\',)"}, "jsonrpc": "2.0", "id": 1}')
127.0.0.1 - - [24/Sep/2015 12:44:41] ================================================================================
Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt_with_whitespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '__parser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'ParserNode' object has no attribute '_remove_last_newline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 100, in apply
    result = method(**params)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/anaconda_mode.py", line 59, in complete
    return script.completions()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 409, in _parse
    self.current_node.remove_last_newline()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 228, in remove_last_newline
    self.parser.remove_last_newline()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/__init__.py", line 374, in remove_last_newline
    newline = newline.get_previous()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/tree.py", line 182, in get_previous
    i = c.index(self)
ValueError: <Whitespace: > is not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "<string>", line 2, in raise_from
service_factory.exceptions.ServiceException: (500, '{"error": {"message": "Server error", "code": -32000, "data": "ValueError(\'<Whitespace: > is not in list\',)"}, "jsonrpc": "2.0", "id": 1}')
127.0.0.1 - - [24/Sep/2015 12:44:47] ================================================================================
Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt_with_whitespace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '_user_stmt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'UserContextParser' object has no attribute '__parser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 141, in wrapper
    return getattr(self, name)
AttributeError: 'ParserNode' object has no attribute '_remove_last_newline'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 100, in apply
    result = method(**params)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/anaconda_mode.py", line 59, in complete
    return script.completions()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 185, in completions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 303, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 293, in user_stmt
    module = self.module()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 409, in _parse
    self.current_node.remove_last_newline()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/fast.py", line 228, in remove_last_newline
    self.parser.remove_last_newline()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/__init__.py", line 374, in remove_last_newline
    newline = newline.get_previous()
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/jedi/parser/tree.py", line 182, in get_previous
    i = c.index(self)
ValueError: <Whitespace: > is not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/Users/pedrovanzella/dotfiles/lib/spacemacs/.cache/anaconda-mode/0.1.1/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "<string>", line 2, in raise_from
service_factory.exceptions.ServiceException: (500, '{"error": {"message": "Server error", "code": -32000, "data": "ValueError(\'<Whitespace: > is not in list\',)"}, "jsonrpc": "2.0", "id": 1}')
```

Still no autocomplete.

**Comment by pedrovanzella** [comment]
Well, that's weird: autocomplete started working after that.

So I guess the solution is to delete everything and let emacs sort itself out after a restart.

Thanks for the help!

**Comment by cpaulik** [comment]
Strange, I know that anaconda mode takes a little time the first time after everything is installed. But I have never seen a such a stacktrace. 

Glad it works now.

**Comment by voltecrus** [comment]
Is reinstalling everything a solution that works on both branches?

**Comment by nixmaniack** [comment]
@voltecrus Might not work on master as anaconda_mode package had major upgrade recently. (that's why things are still broken!)

**Comment by TheBB** [comment]
What's the status on this issue?

**Comment by pedrovanzella** [comment]
@TheBB it's been working fine for me for the past week or so. Seems to have been fixed upstream.

**Comment by TheBB** [comment]
I'm closing this then. Please open a new issue if something else happens!

**Comment by dvcrn** [comment]
I am having the same issue. Tried updating to latest everything but it still persists. How did you guys fix it?

**Comment by collenjones** [comment]
I am also having this issue after upgrading to 0.104.5

**Comment by kissgyorgy** [comment]
> I found a solution for this problem here: http://stackoverflow.com/questions/24257803/distutilsoptionerror-must-supply-either-home-or-prefix-exec-prefix-not-both
> 
> So python -c "import pip; pip.main(['install', '-t', '.', 'anaconda-mode == 0.1.1'])" runs fine now.
> 
> My *anaconda-mode* buffer now reads anaconda_mode port 9000.
> 
> Still, for some reason, a anaconda-mode folder is created inside ~/.emacs.d, not ~/.emacs.d/.cache.
> 
> Also, autocomplete doesn't work.

This worked for me!

**Comment by mandarvaze** [comment]
I am still having similar issues (on version 0.104.8)
I can not use the SO solution, as the SO comments say that it breaks the virtualenv (Can't risk that)
I had empty `~/.emacs.d/.cache/anaconda-mode/0.1.1` Removing that and restarting spacemacs didn't help

**Comment by cpaulik** [comment]
If you are using homebrew then this is a homebrew bug in my opinion since it breaks a standard pip Command line Argument. Can you try using e.g. pyenv to install a fully working Python Installation? Or maybe the anaconda Python distribution ( not to be confused with anaconda mode)

**Comment by drets** [comment]
https://github.com/syl20bnr/spacemacs/issues/2917#issuecomment-142709358
This worked for me, thanks!

**Comment by mandarvaze** [comment]
I was able to get the anaconda mode working using the instructions from here : http://www.marinamele.com/2014/07/install-python3-on-mac-os-x-and-use-virtualenv-and-virtualenvwrapper.html

Once my ``pyenv`` was setup, anaconda mode started working in terminal mode.
Since my ``WORKON_HOME`` is set into ``.zshrc`` (which is used only by interactive shells), I need to set this up into ``.profile`` (BTW, I was told this by spacemacs itself. Very cool.)

**Comment by woonchao** [comment]
Hi, I have the same problems when I add python layer to my dotfile, when I open a python file, anaconda-mode get error log like this.
```
Traceback (most recent call last):
  File "/usr/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 45, in <module>
    from .config.loader import Config
  File "/usr/lib/python2.7/dist-packages/IPython/config/__init__.py", line 16, in <module>
    from .application import *
  File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 32, in <module>
    from IPython.config.configurable import SingletonConfigurable
  File "/usr/lib/python2.7/dist-packages/IPython/config/configurable.py", line 32, in <module>
    from .loader import Config, LazyConfigValue
  File "/usr/lib/python2.7/dist-packages/IPython/config/loader.py", line 34, in <module>
    from IPython.utils.path import filefind, get_ipython_dir
  File "/usr/lib/python2.7/dist-packages/IPython/utils/path.py", line 22, in <module>
    import tempfile
  File "/usr/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
ImportError: cannot import name Random
```
The messages are as follows
```
error in process sentinel: anaconda-mode-ensure-directory-sentinel: Can't create /home/wen/.emacs.d/.cache/anaconda-mode/0.1.1 directory
error in process sentinel: Can't create /home/wen/.emacs.d/.cache/anaconda-mode/0.1.1 directory
```
But I didn't do anything to import random.
Anyone have idea to this?

**Comment by mandarvaze** [comment]
Based on the error, it would seem there may be permissions issue.
Can you manually create ``/home/wen/.emacs.d/.cache/anaconda-mode/0.1.1`` and make sure it is writable, and then restart spacemacs ?
About ``import random``, don't worry. I think ``tempfile.py`` is trying to create some random number/filename for internal usage.

**Comment by woonchao** [comment]
However, the directory `/home/wen/.emacs.d/.cache/anaconda-mode/0.1.1` is already exist, and it's empty. I make sure it is writable, but error still there. Is there something wrong with my Ipython? I found something about Ipython in the messages.

**Comment by zengfengbo** [comment]
when the cursor stay on a function, the the *eldoc* flashed, show the function arguments just a second.
