### ISSUE TITLE
Major mode leader key doesn't work in Clojure files

### ISSUE THREAD

**Issue by malchmih** [syl20bnr/spacemacs#3000]
On `,` I get No previous search. `SPC m` works.

**Comment by TheBB** [comment]
I'm looking at this now. I suspect moving all the mode-specific evil-leader bindings to `:init` blocks instead of `:config` blocks will help.

The major mode leader key is not robust in my experience, but this is the first time I've seen the problem reliably reproducible.

**Comment by malchmih** [comment]
Hmm, it doesn't work in project.clj, but works in any other clj/cljs file.
In project.clj I get `File mode specification error: (error "No active nREPL connections")`

**Comment by darker0n** [comment]
yes, it doesn't work only in project.clj :confused:

**Comment by TheBB** [comment]
Congratulations on the 3000th issue or PR, by the way. :-)

**Comment by malchmih** [comment]
Thank you :joy: My pleasure!

**Comment by justbur** [comment]
@malchmih when you have this problem I assume you're in normal mode and using vim keybindings? What's the value of `major-mode`? (`SPC h d v major-mode RET`)

**Comment by mbertheau** [comment]
In my experience <kbd>,</kbd> doesn't work in the first clojure buffer, in the 2nd and following it works. Intuitively I'd guess that the error message about nREPL prevents a complete mode startup, which is why the leader doesn't work. Further, the nREPL checking code throws that error only once per session, which is why the leader works in subsequently opened buffers.

**Comment by justbur** [comment]
That actually makes perfect sense because , is bound in an "after" major mode hook. The failure is probably preventing that hook from firing.

**Comment by malchmih** [comment]
Right now it doesn't work only in project.clj. With messages I mentioned above. Doesn't depend on the order of buffers.

**Comment by mbertheau** [comment]
Ok, still makes sense though: project.clj is special, and the nREPL thing is apparently checked only for project.clj.

**Comment by cpaulik** [comment]
In the past we had this problem of `,` not working on the first buffer because of faulty integration of `sematic-mode`. Do you have the `semantic` layer enabled?

**Comment by malchmih** [comment]
No, I don't

**Comment by justbur** [comment]
We could make setting the major mode leader keys independent of the mode hooks running successfully but the proper thing to do would be to track down this error and fix it. 

Has anyone produced a backtrack for the error?

**Comment by justbur** [comment]
#3002 should fix the inconsistency between `SPC m` working and `,` not.

**Comment by malchmih** [comment]
Thank you, `,` works now! Although I still get `File mode specification error: (error "No active nREPL connections")`. Is it Spacemacs or CIDER?

**Comment by mbertheau** [comment]
@malchmih I don't know why that error message comes at this point in time, but you can use <kbd>, s i</kbd> to start up a REPL. I don't know exactly what the supposed workflow is with CIDER. It works for me if I just start up a REPL after opening a clojure file.

The original bug has been resolved, so this issue can be closed.

**Comment by malchmih** [comment]
Sure, will try to investigate myself

**Comment by justbur** [comment]
I can't comment on the proper way to set up this layer, but I was able to narrow down the problem to [this line](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Blang/clojure/packages.el#L33). When cider-mode loads it ends up checking for an active repl, which throws an error if it can't find one. Here's the backtrace (note the call to `cider-ensure-connected` when "project.clj" is opened for the first time). 

You could probably remove that hook and find another way to start cider-mode to stop the error

```
Debugger entered--Lisp error: (error "No active nREPL connections")
  signal(error ("No active nREPL connections"))
  error("No active nREPL connections")
  cider-ensure-connected()
  cider-current-connection()
  cider-current-ns()
  cider-refresh-font-lock()
  cider-mode()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook clojure-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook clojure-mode-hook))
  run-mode-hooks(clojure-mode-hook)
  clojure-mode()
  set-auto-mode-0(clojure-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer project.clj> "~/project.clj" nil nil "~/project.clj" (1125899907078791 2221746863))
```

**Comment by malchmih** [comment]
Thank you, will take a look at this :+1:
