### ISSUE TITLE
Font changes in dotspacemacs-default-font not getting applied (OS X) (Workaround in comments)

### ISSUE THREAD

**Issue by calebmeyer** [syl20bnr/spacemacs#3477]
Emacs Version: GNU Emacs 24.5.1 (x86_64-apple-darwin14.5.0, Carbon Version 157 AppKit 1348.17)
.spacemacs file: https://github.com/calebmeyer/dotfiles/blob/master/spacemacs
messages buffer after launch: https://gist.github.com/calebmeyer/28630f6695723f430f7b

<img width="1917" alt="default font" src="https://cloud.githubusercontent.com/assets/3342777/10590026/26a36ea0-7674-11e5-80a6-6d35626add4c.png">

Let me know if you need any more information to debug this. I love spacemacs, and I really want to use it as my default. I have checked, I do have Source Code Pro installed.

**Comment by syl20bnr** [comment]
I cannot see Source Code Pro on your screenshot but I trust you that you have it installed :-)
Honestly I have no idea why it does not work, what does `SPC h d c` on a character output ?

**Comment by calebmeyer** [comment]
<img width="2032" alt="spc h d c" src="https://cloud.githubusercontent.com/assets/3342777/10609301/a495dbba-7708-11e5-9c49-9bf9cb442aed.png">

**Comment by d12frosted** [comment]
I am probably blind, but... are you in terminal or gui? :smile:

**Comment by calebmeyer** [comment]
I'm in the gui, @d12frosted. Terminal emacs respects my terminal settings (inconsolata-g for powerline, 14pt)

**Comment by d12frosted** [comment]
Ah sorry, @calebmeyer. I am blind indeed :smile: 

> Terminal emacs respects my terminal settings

Yeah, this is exactly why I asked about terminal vs GUI - cause terminal emacs respects only terminal settings.

**Comment by calebmeyer** [comment]
No problem. I appreciate your help. Emacs so far is a series of small frustrations, alongside a series of big wins. The layer concept is a fantastic way of pulling together packages and good defaults.

**Comment by StreakyCobra** [comment]
What does `SPC : describe-font RET` give you for `Source Code Pro`? If you try manually to call `SPC : set-frame-font` to Source Code Pro, does it work?

I also noticed you have [an old `.spacemacs`](https://gist.github.com/calebmeyer/28630f6695723f430f7b#file-gistfile1-txt-L62):
```
(Spacemacs) Warning: `dotspacemacs/config' is deprecated, please rename your function to `dotspacemacs/user-config'
```
Maybe try to update it (hint: `SPC f e D`).

**Comment by calebmeyer** [comment]
Updated my .spacemacs file.

Output of describe-font:
```
name (opened by): -*-Monaco-normal-normal-normal-*-12-*-*-*-m-0-iso10646-1
       full name: Monaco:pixelsize=12:weight=normal:slant=normal:width=normal:spacing=100:scalable=true
            size: 12
          height: 16
 baseline-offset:  0
relative-compose:  0
```

Yes, calling set frame font to source code pro switched the font. It kept the size at 12 though.

**Comment by calebmeyer** [comment]
Per conversation on the gitter chat, I uninstalled and reinstalled emacs-mac via this sequence of commands:
```
brew uninstall emacs
brew uninstall emacs-mac
brew tap railwaycat/emacsmacport
brew install emacs-mac --with-spacemacs-icon
```

This didn't solve the issue, and I still don't have the beautiful spacemacs icon.

**Comment by calebmeyer** [comment]
I was able to work around the official settings via this code in my user-config:
```emacs-lisp
  (set-face-attribute 'default nil :family "Source Code Pro")
  (set-face-attribute 'default nil :height 165)
```

**Comment by kostajh** [comment]
Same problem for me, same diagnostics, on the latest stable Spacemacs release. Workaround posted by @calebmeyer works for me.

**Comment by nixmaniack** [comment]
Not sure if it's related, but setting up font using `dotspacemacs-default-font` had some quirks.
Following went in my `user-config` some time back.
```elisp
(when (display-graphic-p)
    (set-face-attribute 'default nil :font "Input Mono Condensed-13" :weight 'ultralight))
```

**Comment by kostajh** [comment]
For me anyway, this issue is fixed in `develop`.

**Comment by calebmeyer** [comment]
I am on develop (0.105.0) and can confirm that this is not fixed. Without the workaround mentioned above staying in my user-config, I still get monaco.

I am able to set the font without the hack on a ubuntu vm, so this appears to be a mac related issue.

**Comment by calebmeyer** [comment]
So, I figured I'd look through the code for spacemacs to see if I could do some more debugging myself. I made this change:
```emacs-lisp
diff --git a/core/core-fonts-support.el b/core/core-fonts-support.el
index 5f9b07b..c16375d 100644
--- a/core/core-fonts-support.el
+++ b/core/core-fonts-support.el
@@ -27,6 +27,7 @@ PLIST has the form (\"fontname\" :prop1 val1 :prop2 val2 ...)"
                       :powerline-offset))
          (fontspec (apply 'font-spec :name font font-props)))
     (spacemacs-buffer/message "Setting font \"%s\"..." font)
+    (spacemacs-buffer/warning "Setting fontspec \"%s\"..." fontspec)
     (set-frame-font fontspec nil t)
     (setq-default powerline-scale scale)
     (setq-default powerline-height (spacemacs/compute-powerline-height))
(END)
```

And just logging out the font spec to my messages buffer has fixed the bug. I verified by unmaking the change, it went back to monaco.

`#heisenbug`?

**Comment by jalehman** [comment]
I ran into this issue as well, and the above fix by @calebmeyer fixed the issue for me as well. Running OS X 10.11.2, Spacemacs 0.105.9, emacs 24.5.1 installed as per instructions [here](https://github.com/syl20bnr/spacemacs#os-x).

**Comment by lehoff** [comment]
Same issue here. @calebmeyer's solution did the trick for me.

**Comment by strickinato** [comment]
Confirmed worked for me-
```
  (set-face-attribute 'default nil :family "Source Code Pro")
  (set-face-attribute 'default nil :height 165)
```

**Comment by brettbates** [comment]
FYI: seems osx does not have "source code pro" installed by default, you can pick it up here:

https://github.com/adobe-fonts/source-code-pro

This solved the issue for me. Could be helpful to have an error show up if it doesn't exist?

**Comment by calebmeyer** [comment]
Could be even more helpful if we could somehow distribute source code pro with spacemacs. It's licensed under the [SIL open font license](https://en.wikipedia.org/wiki/SIL_Open_Font_License) which the FSF says is kosher.

Might be a nightmare to get fonts installed cross platform though.

**Comment by Q-Tran** [comment]
My problem was that I was loading a saved desktop after loading the changes to the font, making the previous desktop's font appear. 

remember to reload your desktop!

**Comment by d12frosted** [comment]
> Could be even more helpful if we could somehow distribute source code pro with spacemacs.

There is no need to distribute Source Code Pro. I just realised that there is no mention of Source Code Pro in installation guide inside of README file. This is what we should do - post a link to Source Code Pro download page.

**Comment by ajimu** [comment]
I've been playing around with this on Arch Linux. After making the change mentioned by @calebmeyer, the first emacsclient instance uses the correct font, but future instances don't

**Comment by StreakyCobra** [comment]
@ajimu Can you try the `develop` branch without any tweak for the font, i.e. just customizing `dotspacemacs-default-font`? The first emacsclient having a different font than subsequent clients should have been fixed there. I'm not sure about what you are saying because the first frame was the **wrong** font and subsequens were using the **right** font, so maybe it's not the font you are expecting.

**Comment by ajimu** [comment]
@StreakyCobra thanks, it is fixed on `develop`. I was actually using the same font but different sizes and I just got them confused. Bad info on my part.

**Comment by StreakyCobra** [comment]
@calebmeyer Can you also try last `develop` without other hack, just `dotspacemacs-default-font`? The change for user in daemon mode could also have solved this one.

**Comment by calebmeyer** [comment]
<img width="1271" alt="screen shot 2016-05-03 at 8 16 24 am" src="https://cloud.githubusercontent.com/assets/3342777/14984268/67a70eb0-1107-11e6-96f0-c16254960c33.png">

Alas, still not fixed for me on develop. I am on El Capitan (OS X 10.11) now, but still seeing menlo instead of Source Code Pro unless I manually set it.

**Comment by StreakyCobra** [comment]
Ok :-(

**Comment by ajimu** [comment]
If I make changes that result in having `(custom-set-faces ...)` in my `~/.spacemacs`, my font goes back to being too small

**Comment by glimmercn** [comment]
my system is ubuntu 15.4, emacs 24.5, spacemacs develop. 

even @calebmeyer 's tweak can't help me.

**Comment by danielwuz** [comment]
I had the same problem. I was able to fix it by resetting `custom-set-variables` back to default.

```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.)
 )
```

**Comment by marcoslhc** [comment]
Before doing something crazy with your `.spacemacs` make sure you have the font installed in `/Library/Fonts` not `~/Library/Fonts` or force Emacs to search for the fonts also in `~/Library/Fonts`
You can install fonts with `brew cask` by doing
```
$ brew tap caskroom/fonts
$ brew cask install font-source-code-pro --fontdir=/Library/Fonts
```

**Comment by iesahin** [comment]
Can this be related with `dotspacemacs-themes` ? 

Yesterday I set it to 
```
   dotspacemacs-themes (append
                         (cookie-shuffle-vector
                          [adwaita
                           alect-dark-alt
                           ample
                           ample-zen
                           apropospriate-dark
                           apropospriate-light
                           badwolf
                           birds-of-paradise-plus
                           cherry-blossom
                           colorsarenice-light
                           darkburn
                           dichromacy
                           minimal-light
                           farmhouse-dark
                           espresso
                           flatland
                           gandalf
                           hemisu-dark
                           hemisu-light
                           inkpot
                           leuven
                           junio
                           material-light
                           minimal
                           mccarthy
                           spacemacs-dark
                           misterioso
                           naquadah
                           noctilux
                           occidental
                           pastels-on-dark
                           reverse
                           purple-haze
                           sanityinc-tomorrow-bright
                           soft-morning
                           spolsky
                           subatomic
                           tango
                           tango-2
                           tango-dark
                           tango-plus
                           tao-yang
                           tao-yin
                           toxi
                           tsdh-light
                           wheatgrass
                           wombat
                           wilson
                           whiteboard
                           zen-and-art
                           zenburn
                           spacemacs-light]) nil)
```
and it didn't read the font settings. (It was only increasing the font size to 30.) I checked out `develop (afcef9e)` to no avail. But then I changed the above setting to 
```
 dotspacemacs-themes '(spacemacs-light
                         spacemacs-dark
                         leuven
                         wombat
                         monokai
                         solarized-light)
 ```
and it's resolved both in `develop` and `master (8e1af14)` now.  

This is on Ubuntu 17.04 with Emacs 24.5.1, on Turkish language locale. This is my third day in Spacemacs, so I'm not fully equipped to dig in but one of the themes seems to be misbehaving.

**Comment by vegertar** [comment]
I'm in windows 10 with spacemacs 0.200.9@25.2.1 , this issue is fixed by `user-config` mentioned by @calebmeyer.

**Comment by jb55** [comment]
I fixed this by deleting:

` '(default ((t (:background nil)))`

from `custom-set-faces`

¯\_(ツ)_/¯

**Comment by wiskey5alpha** [comment]
> I fixed this by deleting:
> '(default ((t (:background nil)))
> from custom-set-faces

Fixed this for me, windows 10 spacemacs 0.200.9@25.2.1

**Comment by CarstenKoenig** [comment]
@jb55 solution fixed the issue for me too (on Linux Mint - 0.200.9@25.3.2 (spacemacs) )
thank you

**Comment by well1791** [comment]
Thanks @jb55, your solution worked for me! 👏  
- macOS High Sierra 10.13.3
- Emacs 25.3.1

**Comment by netcrave** [comment]
I actually needed menu-set-font to change the font of the text in the powerline bar 
![image](https://user-images.githubusercontent.com/35227254/44293107-fe6c1100-a23d-11e8-9b08-05489948df69.png)

**Comment by non-Jedi** [comment]
I was having an issue similar to this one today, but it seems to have been caused by the `themes-megapack` layer. Went back to behaving as expected when that layer was removed.

**Comment by jerome-diver** [comment]
april 2019 .... 4 years after, same problem.... just use a font is a mess.

**Comment by collector1871** [comment]
@jerome-diver 
yes, in develop i have also problem
but i can confirm that this is working as expected:

` (set-face-attribute 'default nil :family "Source Code Pro")`
` (set-face-attribute 'default nil :height 165)`

(you can manipulate height and font type here)

**Comment by lukad** [comment]
This is still broken on a fresh spacemacs install on GNU Emacs 26.2 + macOS 10.14.5.

**Comment by mjsteinbaugh** [comment]
I can confirm that this is still a bug for Emacs GUI window system on a MacBook Pro with a retina display running macOS 10.14.6, Emacs 26.3, and spacemacs 0.200.13.

Adding this to `dotspacemacs/user-config` in my [`.spacemacs` config](https://github.com/acidgenomics/dotfiles/blob/master/spacemacs) fixes the issue:

```
  (if (eq system-type 'darwin)
      (set-face-attribute 'default nil :height 165))
```

**Comment by pavloo** [comment]
Had the same problem on latest develop. What helped me was I switched back to master branch, launched Emacs, then switched back to develop branch and restarted it - it began to respect font settings in .spacemacs after all this gymnastics.

**Comment by torfjelde** [comment]
I'm currently trying out spacemacs and ran into the same issue as described here.

Spacemacs would _not_ respect `dotspacemacs-default-font`, but instead fall back to using the font I used for my _previous_ Emacs configuration (which I've moved to `~/.emacs.d.bak`).

So somehow it's being overwritten by my Emacs config located in `~/.emacs.d.bak`? I dunno; it's very weird to me.

**Comment by tigerjack** [comment]
For me, the problem was in `custom-set-variable`, where I had
```
 '(ispell-program-name "/usr/bin/hunspell")
```
Deleting this line fixed the issue.

To note that the same configuration was working (in the sense of the font size) on the master branch.

**Comment by alexandergogl** [comment]
Thanks @jb55, your solution worked for me too! 👏

macOS Mojave 10.14.6
Emacs 28.0.5
Spacemacs v.0.300.0 dev branch

**Comment by lebensterben** [comment]
Closing since this doesn't seem to be a Spacemacs bug.
See discussion above for possible fixes.
