### ISSUE TITLE
"(Bootstrap) Installing s..." eachtime I open emacs

### ISSUE THREAD

**Issue by SrinivasDJ** [syl20bnr/spacemacs#3534]
When I open emacs I see the below message each time:

(Bootstrap) Installing s...
Found 1 orphan package(s) to delete...
--> deleting s... [1/1]

My emacs version is 24.4.1 (debian jessie)

**Comment by TheBB** [comment]
This has apparently been fixed in the development version of Spacemacs.

**Comment by freebroccolo** [comment]
I am still seeing this behavior on the `develop` branch.

**Comment by justbur** [comment]
@freebroccolo are you excluding any packages in .spacemacs?

**Comment by freebroccolo** [comment]
@justbur nope. I've seen it on two different machines (OS X) with fresh installs of spacemacs (no existing `.spacemacs` or `.emacs.d`).

**Comment by justbur** [comment]
Never mind we figured out the problem #3663

**Comment by justbur** [comment]
@TheBB this should be fixed now

**Comment by ptxmac** [comment]
I'm still seeing this issue with the `erlang` layer.

OS X, emacs 24.5.1, clean develop branch
