### ISSUE TITLE
Error using flycheck

### ISSUE THREAD

**Issue by wallacewinfrey** [syl20bnr/spacemacs#4138]
When enabling flycheck-mode, and opening up a supported file, I get the following error:

`Error while checking syntax automatically: (void-function seq-find)`

enabling toggle-debug-on-error gives me:

``` elisp
Debugger entered--Lisp error: (void-function seq-find)
  signal(void-function (seq-find))
  flycheck-buffer()
  flycheck-buffer-automatically(idle-change)
  flycheck-handle-idle-change()
  apply(flycheck-handle-idle-change nil)
  timer-event-handler([t 22121 46591 432833 nil flycheck-handle-idle-change nil nil 283000])
```

Steps to reproduce:
1. Install fresh copy of spacemacs
2. `M-x package-install flycheck`
3. `M-x flycheck-global-mode`
4. Open supported file (I tried shell, ruby and perl)

**Comment by synic** [comment]
You might have better luck not installing flycheck manually, and, instead,
installing the appropriate layer for the language you're working on.

Try putting `syntax-checking` and `ruby` in
`dotspacemacs-configuration-layers`.  That should install flycheck for you,
and configure things how they need to be.

**Comment by wallacewinfrey** [comment]
No change. I restarted emacs, let it orphan flycheck, enabled the syntax-checking and ruby layers, got the same seq-find error, this time with an additional error from enabling the ruby layer:

`Error (use-package): enh-ruby-mode :config: Symbol's function definition is void: sp-with-modes`

**Comment by StreakyCobra** [comment]
@wallacewinfrey This `sp-with-modes` is a know bug with a pending PR: #4132 and #4098

**Comment by syl20bnr** [comment]
> Error (use-package): enh-ruby-mode :config: Symbol's function definition is void: sp-with-modes

Should be fixed in develop.

**Comment by ahyatt** [comment]
About seq-find: this is a common problem with use-package, if you use it, or you may find a similar situation:
https://github.com/jwiegley/use-package/issues/275

Short version: something is loading the seq library before package-initialize is called in spacemacs
(which changes the load-path to bring in the elpa seq).  I'm having the same issue, but haven't traced it down yet.  Ideally in Spacemacs, nothing should be allowed to happen before package-initialize happens.

**Comment by wallacewinfrey** [comment]
It doesn't appear to be fixed in develop, either. Still encountering the same error/lack of flycheck functionality after switching to the develop branch.

**Comment by naseer** [comment]
This started happening for me today(on stable) after I updated packages.

**Comment by siegfried** [comment]
Putting ruby in dotspacemacs-configuration-layers will cause this issue, while it's ok to just leave ruby-on-rails in it.

**Comment by JAremko** [comment]
**← Total Emacs n00b here**  
I have the same problem with the go(golang), I use spell-checking layer.   
Also I noticed that the `seq-find` thingy is a part of  [`seq.el`](https://github.com/NicolasPetton/seq.el/blob/master/seq.el)   from the readme:
 *seq.el provides Sequence manipulation functions that complement basic functions provided by subr.el. The library is included in Emacs 25.*   
I'm using Emacs 24.  Can It be the reason?

**Comment by wallacewinfrey** [comment]
> Putting ruby in dotspacemacs-configuration-layers will cause this issue, while it's ok to just leave ruby-on-rails in it.

Replacing:

`(setq-default dotspacemacs-configuration-layers '(ruby))`

with:

`(setq-default dotspacemacs-configuration-layers '(ruby-on-rails))`

didn't seem to make a difference in [spacemacs-develop](https://github.com/syl20bnr/spacemacs/tree/develop). Additionally, removing:

`(setq-default dotspacemacs-configuration-layers '(ruby))`

didn't seem to make a change with flycheck in other language modes.

> Might it be because seq.el is Included in Emacs 25 ?

Interesting. I suppose I should have mentioned earlier I'm using `GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.4.0, NS appkit-1348.17 Version 10.10.4 (Build 14E46)) of 2015-07-10`

**Comment by ahyatt** [comment]
AFAIK, as long as you run package-initialize to set up the load-path before
anything else, there shouldn't be an issue with seq.el.  The issues are, in
Emacs 25, when some package is initialized that needs it before
package-initialize - the later packages that depend on the later version
will never get that later version.

**Comment by StreakyCobra** [comment]
I'm not closing this one as it doesn't seems to be really fixed in develop.

**Comment by whizzzkid** [comment]
This seems to be an issue with JSON and JS as well. Still does not work for me.

**Comment by ElessarWebb** [comment]
Same issue with latex files since I've updated spacemacs.

**Comment by syl20bnr** [comment]
Is everybody here having the issue is using Emacs 25 ?

**Comment by JAremko** [comment]
Yes. Also i tested it in 24 and it works fine.

**Comment by cpjolicoeur** [comment]
I'm on emacs 24 and having the same issue.

**Comment by wallacewinfrey** [comment]
> Is everybody here having the issue is using Emacs 25 ?

As mentioned above, I've been using `GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.4.0, NS appkit-1348.17 Version 10.10.4 (Build 14E46)) of 2015-07-10` but to test the "it-works-on-24" hypothesis I downloaded `GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org`.

I copied my spacemacs directory from .confmacs/configs/spacemacs to .confmacs/config/spacemacs-emacs24, switched to the new config, [removed all of the compiled emacs lisp files](https://github.com/syl20bnr/spacemacs/issues/3129) and flycheck now works without issue.

I guess for the time being I'm gonna have to downgrade to 24; flycheck was a major part of my workflow and it's been painful not having it.

**Comment by dxnn** [comment]
I'm having this issue on emacs 24 and spacemacs develop branch.

**Comment by justbur** [comment]
If you're having this issue, please give the output of the following which might help track it down 

  1. `M-x locate-library RET seq RET`
  2. `M-x pkg-info-library-version RET seq RET`

**Comment by dxnn** [comment]
1. ~/.emacs.d/elpa/seq-20150709.1040/seq.elc
2. 20150709.1040

**Comment by syohex** [comment]
`seq-find` was introduced at 2015/SEP/18(https://github.com/NicolasPetton/seq.el/commit/4c14ba0c9edacf412a1bcb7921bb1f88db1c4fbe). So you need to update `seq.el` package.

**Comment by wallacewinfrey** [comment]
Using `GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.4.0, NS appkit-1348.17 Version 10.10.4 (Build 14E46)) of 2015-07-10` with spacemacs master branch
- Library is file ~/.emacs.d/elpa/seq-1.11/seq.elc
- 1.11

**Comment by cpjolicoeur** [comment]
For Emacs `GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)`

* Library is file ~/.emacs.d/elpa/seq-20150709.1040/seq.elc
* 20150709.1040

**Comment by justbur** [comment]
@wallacewinfrey 1.11 is the minimum required version for flycheck, so you should not have this problem. 

@cpjolicoeur like @dxnn you need to update your packages.

**Comment by StreakyCobra** [comment]
> you need to update your packages. 

i.e. Click `[Update packages]` on `*spacemacs*` buffer.

**Comment by dxnn** [comment]
I've updated my packages, and updated to v.0.105.5 for good measure, but the `seq` package version information hasn't changed. 

Is there a log I should check to see if the update is breaking for some reason?

**Comment by StreakyCobra** [comment]
@dxnn You can try to remove the `.emacs.d/elpa/seq…` directory and restart Spacemacs, the last version of the package should be downloaded.

**Comment by dxnn** [comment]
@StreakyCobra Yep, that did the trick. Thanks!

**Comment by JAremko** [comment]
I tested both 24 and 25 on Debian and both are working fine. 
Looks like something wrong with the [emacs package](https://pkgs.alpinelinux.org/package/testing/x86_64/emacs-xorg) or my setup.

**Comment by whizzzkid** [comment]
Updating emacs from 25.0 to 25.1 seems to have resolved the problem.

**Comment by justbur** [comment]
@syl20bnr If I read these reports correctly, this is a problem with managing dependencies. flycheck requires seq v1.11 and people are not getting it when they install flycheck. Is this because emacs is comparing the version in date format to 1.11?

**Comment by newhook** [comment]
This happens to me with a fresh install a week ago. I tried reinstalling seq-1.11, but no dice. Any help?

**Comment by syl20bnr** [comment]
What is your Emacs version ?

Le mardi 19 janvier 2016, Matthew Newhook <notifications@github.com> a
écrit :

> This happens to me with a fresh install a week ago. I tried reinstalling
> seq-1.11, but no dice. Any help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/syl20bnr/spacemacs/issues/4138#issuecomment-172835343>
> .
>


-- 
-syl20bnr-

**Comment by newhook** [comment]
25.0.50.1 - latest for OSX in the brew tap.

**Comment by JAremko** [comment]
I created a Docker images that reproduces this bug  https://github.com/JAremko/spacemacs-issues-4138-test 
It's running on my server  ssh root@93.74.50.63  -p 4138  
I'll keep it running for a day or so.

**Comment by justbur** [comment]
@newhook can you do this? https://github.com/syl20bnr/spacemacs/issues/4138#issuecomment-169862150

**Comment by newhook** [comment]
M-x locate-library RET seq RET
~/.emacs.d/elpa/seq-1.11/seq.elc

M-x pkg-info-library-version RET seq RET
1.11

**Comment by andrew-kennedy** [comment]
I'm also getting this issue, super fresh install of spacemacs from like 2 days ago, only enabled the racket mode layer. Running emacs 25.0.50.1 on OS X from homebrew. I get the exact same output as @newhook . Any resolution?

**Comment by sickill** [comment]
What worked for me was to remove `~/.emacs.d/elpa/seq-*` and restarting Emacs (to make it download latest version). `seq-find` was introduced at the end of 2015.

**Comment by newhook** [comment]
Yeah, well I tried that and it didn't work.

**Comment by justbur** [comment]
@newhook since you're using emacs 25, seq library is included in emacs. Somehow you are not loading the right version, so maybe you have an old version of seq bundled with your emacs distribution. Can you check for an update to emacs itself? There's a pretest available now. My version string is "25.0.91.1" for example. 

A workaround until the release of 25 is final is to force the right library to load no matter what, which you could do with 
```elisp
(load "~/.emacs.d/elpa/seq-1.11/seq.elc")
```
if that is where you have the right version on your system.

**Comment by PierreR** [comment]
I have the same problem using emacs Emacs 24.5.1

Fresh install. I have completely removed my `.emacs.d` and even ~/.spacemacs.

Note that I need to use `--insecure` because without it have got a "Failed connect, connection refused".

**Comment by JAremko** [comment]
@PierreR  Emacs repository is down ╯°□°）╯︵ ┻━┻

**Comment by PierreR** [comment]
@JAremko  Thanks for the info. I will wait for it to go up again.

**Comment by rgrinberg** [comment]
@PierreR Is this still a problem?

**Comment by d12frosted** [comment]
Closing for inactivity.

Thanks @rgrinberg for pinging!

**Comment by tarjeiba** [comment]
I still get this issue running Emacs 25.0.50.1 on Windows, with seq located in
    ~/.emacs.d/elpa/seq-2.19/seq.elc

I am trying to run syntax checking in a python buffer.

**Comment by benozol** [comment]
Any ideas on how to help debugging this issue?

I am also still running into it using `syntax-check` in python-mode (emacs-25.0, after nuking `~/.emacs.d/elpa/`, Library is file `~/.emacs.d/elpa/seq-2.19/seq.elc`, and `pkg-info-library-version` of `seq` is 2.19).

**Comment by impca** [comment]
FWIW, I had the same problem when using Emacs 25.0.50.1 and seq-2.19 on Ubuntu (I got my emacs package from Ubuntu Emacs Lisp ppa, it was the latest version available). 

I solved it by removing the current emacs (apt-get remove emacs-snapshot --purge) and upgrading to the latest Emacs version from git (26.0.50), which can be done relatively easily using the following workflow:
```
git clone https://git.savannah.gnu.org/git/emacs.git
cd emacs
autoreconf -if
./configure (if it fails, apt-get install failing dependencies and run ./configure again)
make
sudo checkinstall
```

This will create and install a .deb file with the latest emacs that can be easily and cleanly installed/uninstalled. 

You may also need to do this: https://github.com/syl20bnr/spacemacs/pull/7676

**Comment by benozol** [comment]
Thanks, @impca! Flycheck is now working in Python with an upgraded Emacs (25.2).
