### ISSUE TITLE
Freeze and CPU 100% related to auto-completion layer

### ISSUE THREAD

**Issue by phinicota** [syl20bnr/spacemacs#4139]
I work launching "emacs --daemon" and then multiple emacsclient -t to optimize speed and manage windows with i3wm. I do not know if the problem persists in other mode. The programs stays running for some days in a row sometimes (As I have to leave the PC on for other tasks).
So sometime after working for a while, when I use SPC b b it just completely freezes (C-g multiple times not working) and I have to run killall emacs to restart.

Don't know if related, but could it be that I press SPC b b too fast or something?
My system: 
Ubuntu 12.04 running on i3wm
Spacemacs:
* Release 0.104.x
** 0.104.4 (2015/11/04)

It *seems* to be only happening in C++ mode, as I usually work on that mode.
It has already happened 4 times today.
I attached my .spacemacs just in case.

[.spacemacs.txt](https://github.com/syl20bnr/spacemacs/files/58624/default.spacemacs.txt)

**Comment by tuhdo** [comment]
What's your Emacs version? Have you upgraded to latest packages? `helm-mini` should not cause any lock-up. When you press `C-g`, does the screen go complete blank or you still see the GUI?

**Comment by phinicota** [comment]
Emacs version: GNU Emacs 24.5.1
Immediately after the freeze I can see the freeze but if I wait or spam C-g it goes blank sometimes.
I'm going to try upgrading, I thought I was on the latest stable branch.

**Comment by jb55** [comment]
I fixed this recently by `rm -rf helm*` in the elpa directory

**Comment by phinicota** [comment]
So, I've been experimenting. Doing a pull didn't solve it.
And this rm -rf helm* in the elpa directory didn't solve it either.
Today I got this error during a compilation. The client window I'm using does not go blank. Once I change to other client windows, they go blank, does that mean anything?
So now I'm guessing it has nothing to do with helm but rather another one of the layers I have? any suggestions?

**Comment by taiansu** [comment]
Happens on me too.

In my case it's when editing a elixir file, spacemacs try to complete the function names by alchemist, and it freezes immediately, everytime.

My Environment:
OS X 10.11.2
emacs: railwaycat/emacsmacport 24.5
spacemacs: 0.14.7 && 0.15.0 (development)

**Comment by phinicota** [comment]
After reading the update from taiansu I disabled auto-completion completely and it's been 2 days without problems. So I'm guessing the issue would be related to that layer.
Should this be renamed?

**Comment by StreakyCobra** [comment]
but auto-completion related to c/c++ mode if I understand correctly?

**Comment by phinicota** [comment]
taiansu encountered the issue using editing an elixir file.

**Comment by StreakyCobra** [comment]
Right

**Comment by stormpat** [comment]
Having the same issue with elixir files.

**Comment by taiansu** [comment]
@phinicotat, @stormpat 
Glad it helps. :smile:  Just mention that I don't turn off the auto-complete completely. Instead have setting like this solve my problem:

```
dotspacemacs-configuration-layers
'(
  (auto-completion :variables
                   auto-completion-enable-snippets-in-popup nil)
)
```

Don't know what's your original setting, but if this works you don't have to sacrifice all the completion features until it fixed.

**Comment by StreakyCobra** [comment]
@taiansu `auto-completion-enable-snippets-in-popup` is set to `nil` by default, so it's probably not the problem as @phinicota doesn't set it in his `.spacemacs`.

@phinicota Can you try in some other modes to see if it happens there too?

**Comment by phinicota** [comment]
I don't remember my config, I might have had this though, could it be it?:
```elisp
(setq-default dotspacemacs-configuration-layers
  '(auto-completion :variables
                    auto-completion-enable-sort-by-usage t))
```

**Comment by phinicota** [comment]
Yes, I actually just copied default configs from the page. I'm activating it now without defining any variables now to see what happens.

**Comment by StreakyCobra** [comment]
Ok, what will help is to know if the problem is with C/C++ only, or if it is more general. Let us know if you find more information about this.

**Comment by phinicota** [comment]
I'm now using the develop branch.
Haven't found the same issue so far, closing it for now.
