### ISSUE TITLE
An error with spaceline on 0.105.0

### ISSUE THREAD

**Issue by 877381872** [syl20bnr/spacemacs#4413]
Here is an error with spaceline on 0.105.0.
"Error during redisplay: (eval (spaceline--prepare spaceline-left spaceline-right)) signaled (void-variable spacemacs-mode-line-new-version-lighterp) "
When I open the emacs, the error appeared.And the spaceline was invalid。
How I can do something to fix it ??
thanks a lot 
Just now, I found when I use split screen function. The error appeared.

**Comment by TheBB** [comment]
A workaround for now is to do `(defvar spacemacs-mode-line-new-version-lighterp t)` in your dotfile.

**Comment by TheBB** [comment]
Fixed in https://github.com/syl20bnr/spacemacs/commit/de17125e6d0ab4e6c03d024790aaaac064f2b233

Unfortunately this is an error that only shows up on the master branch when there's a new version available, which is why this one slipped through the cracks in testing. :-(

**Comment by syl20bnr** [comment]
Thanks @TheBB, going to release a hotfix at lunch time.

**Comment by 877381872** [comment]
Thanks a lot !!
I update the version to 0.105.1 and the error was fixed.
plz close the iuuse.And I like the spacemacs very much :)

**Comment by TheBB** [comment]
It's not fixed, it'll come back once we release 0.105.2. It only shows up **when there's a new version available.**

**Comment by 877381872** [comment]
OK.I know it. thank you  :)

**Comment by TheBB** [comment]
Closing as fixed, now.
