### ISSUE TITLE
Spacemacs no longer starting up correctly

### ISSUE THREAD

**Issue by ankhers** [syl20bnr/spacemacs#4486]
Commit f39033afdb77bba3170c547dcf396ea7927ef94c seems to have changed startup behaviour for me.

When starting emacs, I no longer get the `*spacemacs*` buffer, I now get `*scratch*`.

This is how I start emacs.

```
$ emacsclient --alternate-editor="" -c -n
```

my emacs version is 24.5

Let me know if there is any more information that may be useful. I will try to look into making a fix.

**Comment by StreakyCobra** [comment]
@ankhers This change was made to allow people run `emacs FILENAME` to edit a file directly, and indeed it make `emacsclient` starts with the `*scratch*` buffer now (I have the same problem). I'll try to look for a solution.

**Comment by StreakyCobra** [comment]
@ankhers As a temporary workaround, you can copy the old-line to your `dotspacemacs/user-config`:

```elisp
(setq initial-buffer-choice (lambda () (get-buffer spacemacs-buffer-name)))
```

**Comment by syl20bnr** [comment]
@ankhers This bug should be fixed in last releases, can you confirm ?

**Comment by ankhers** [comment]
I'm actually still having this issue on current master and develop branches. Let me know what you need from me to help figure this out.

**Comment by ankhers** [comment]
Can I ask why this was closed? I am still having this issue on master and current develop

**Comment by TheBB** [comment]
Because it was marked as fixed. What we need from you are system information (`SPC h I`) and precise reproduction steps.

**Comment by ankhers** [comment]
#### Description :octocat:
Taken to `*scratch*` buffer instead of `*spacemacs*` buffer when emacs starts

#### Reproduction guide :beetle:
I have an alias for emacs
`alias emacs='/usr/local/Cellar/emacs/24.5/bin/emacsclient --alternate-editor="" -c $@'`
I start emacs using `emacs -n`

*Observed behaviour:* :eyes: :broken_heart:
Taken to the `*scratch*` buffer

*Expected behaviour:* :heart: :smile:
Taken to the `*spacemacs*` buffer

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 77a4c4a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp elm erlang elixir html
            (javascript :variables javascript-disable-tern-port-files nil)
            markdown racket ruby rust sql yaml ruby-on-rails auto-completion better-defaults git github org colors restclient dash erc dockerfile spell-checking syntax-checking nixos intero)
```

**Comment by TheBB** [comment]
Right. How about this? It's a really hacky fix but the only thing I can think of.

    --- a/core/core-spacemacs.el
    +++ b/core/core-spacemacs.el
    @@ -120,7 +120,9 @@ the final step of executing code in `emacs-startup-hook'.")
         (spacemacs|do-after-display-system-init
          (kill-buffer (get-buffer spacemacs-buffer-name))
          (spacemacs-buffer/goto-buffer)))
    -  (setq initial-buffer-choice nil)
    +  (setq initial-buffer-choice
    +        (when (= 1 (length command-line-args))
    +          (lambda () (get-buffer spacemacs-buffer-name))))
       (setq inhibit-startup-screen t)
       (require 'core-keybindings)
       ;; for convenience and user support

**Comment by TheBB** [comment]
FWIW I use a custom script that explicitly opens the home buffer if there are no file arguments.

**Comment by ankhers** [comment]
That does seem to work.
