### ISSUE TITLE
Ensime colours with Scala layer

### ISSUE THREAD

**Issue by kubaracek** [syl20bnr/spacemacs#4746]
#### Description

Hello I am having some odd color issues with Ensime for Scala.

When I open a scala file the syntax is coloured just right but then when Ensime starts it brakes the colours and adds some odd underlines which in my monokai theme is basically a yellow background.
Here's a screenshot

![screen shot 2016-01-22 at 11 27 12](https://cloud.githubusercontent.com/assets/16261998/12509599/7b060efe-c0fb-11e5-85a4-299dd12ed566.png)

This works just fine on my colleague's emacs (not spacemacs)
#### Reproduction guide
- Open a scala file
- Start ensime with `:ensime`
- Wait until ensime starts
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.9
- Spacemacs branch: master (rev. 0562f05)
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
  `elisp
  (auto-completion better-defaults emacs-lisp ruby
  (scala :variables scala-enable-eldoc-mode t)
  markdown javascript shell-scripts yaml html dockerfile ruby-on-rails
  (shell :variables shell-default-height 30 shell-default-position 'bottom)
  (syntax-checking :variables flycheck-scalastylerc "scalastyle_config.xml" scala-enable-eldoc-mode t)
  git github themes-megapack colors tmux chat erc)
  `

**Comment by robbyoconnor** [comment]
What theme? This isn't something we can fix -- it should probably be fixed in your theme ;)

**Comment by JacobJakub** [comment]
Any theme is screwed. Just tried to remove all my layers except scala and the issue still persist

**Comment by JacobJakub** [comment]
Ok, just tried gui version of emacs and this is result:

<img width="915" alt="screen shot 2016-01-22 at 11 43 01" src="https://cloud.githubusercontent.com/assets/16261998/12509840/65514d2e-c0fd-11e5-9021-b1a609801cde.png">

Seems like that the green dots causing this issue, does anyone know what they are and how can I disable them?

**Comment by robbyoconnor** [comment]
What layers are enabled in this screenshot?

**Comment by JacobJakub** [comment]
Only Scala. Just found out that this is an indication of `implicit conversion`

**Comment by JacobJakub** [comment]
I must say that the issue is only present in Terminal version of emacs. Gui is just fine

**Comment by robbyoconnor** [comment]
It's probably your theme

**Comment by chrisbarrett** [comment]
The snippet below should stop ensime from trying to highlight implicit conversions in terminal emacs. Try putting it in your config and see if it helps:
```lisp
(unless (display-graphic-p)
  (setq ensime-sem-high-faces
        (assq-delete-all 'implicitConversion ensime-sem-high-faces)))
```

**Comment by cloudbring** [comment]
@chrisbarrett Thanks for the code snippet. This issue has annoyed me for quite a while.

**Comment by diego-alvarez-hs** [comment]
Hi

That's is a feature of Ensime called: semantic highlighting

Take a look at this to configure the preferred colors https://github.com/ensime/ensime-server/issues/1036

Or you can disabled it putting this into your's ```(defun dotspacemacs/user-config ()```
```
  (setq ensime-sem-high-faces
        '(ensime-sem-high-enabled-p nil ;; disable semantic highlighting))
```

And to disable the green dots, just disable on Ensime ```implicitParams and implicitConversion```

This is my currrent configuration, I'm using ```zenburn```:
```
  (setq ensime-sem-high-faces
        '(
           (implicitConversion nil)
           (var . (:foreground "#ff2222"))
           (varField . (:foreground "#ff3333"))
           (functionCall . (:foreground "#dc9157"))
           (object . (:foreground "#D884E3"))
           (operator . (:foreground "#cc7832"))
           (object . (:foreground "#6897bb" :slant italic))
           (package . (:foreground "yellow"))
           (deprecated . (:strike-through "#a9b7c6"))
           (implicitParams nil)
         )
        ;; ensime-completion-style 'company
        ;; ensime-sem-high-enabled-p nil ;; disable semantic highlighting
        ensime-tooltip-hints t ;; disable type-inspecting tooltips
        ensime-tooltip-type-hints t ;; disable typeinspecting tooltips
  )
```

**Comment by JacobJakub** [comment]
Hi @diego-alvarez-hs your code snipped works just fine!Thank you very much for explaining why this happens.

**Comment by TheBB** [comment]
I think we can treat this as a documentation issue, then?

**Comment by JacobJakub** [comment]
I suppose it is

**Comment by chessman** [comment]
Add 'ensime-implicit-gutter-icons nil' to disable green dots. But there still be one space offset anyway.
