### ISSUE TITLE
Spotify Layer Failing to Build 

### ISSUE THREAD

**Issue by mckeankylej** [syl20bnr/spacemacs#4848]
When I try to install the spotify layer and complie it I get this error message
`spotify.el:66:1:Error: Symbol's function definition is void: spotify-p-dbus`
I went to `spotify.el` and the function is defined. What is the problem?

**Comment by StreakyCobra** [comment]
@syohex It will be fixed upstream by your PR if I understand it correctly?

**Comment by syohex** [comment]
Yes.

**Comment by remvee** [comment]
I've merged the PR, let me know if it helps.

**Comment by StreakyCobra** [comment]
@mckeankylej Can you try in a couple of hours when the package will have been update on MELPA and tell us if it works?

**Comment by mckeankylej** [comment]
So this fixed the compilation bug! 
Unfortunately, when I try to search a song using `SPC a m s g` it doesn’t search anything. On top of this when I run `C-z` in the helm buffer it returns `No Actions Available`. Am I missing a dependency to make spotify play and search? Also here is the warning I get when compiling maybe its relevant:
`y.el:198:1:Warning: the following functions are not known to be defined:
    dbus-call-method-asynchronously, dbus-get-property, dbus-register-signal,
    dbus-unregister-object`

**Comment by nwolfe** [comment]
I believe you will also need to compile your emacs installation with d-bus support.

For example, if you're using emacs from Homebrew:
`brew install emacs --with-d-bus`

**Comment by mckeankylej** [comment]
I am on Ubuntu 15.04. I did some googling and it looks like I have dbus on my machine `libdbus-1-dev is already the newest version.` Shouldn’t my emacs already have dbus support? How can I rebuild it with dbus support?

**Comment by robbyoconnor** [comment]
@mckeankylej it should just work(tm) -- wait a bit -- generally you should report these things upstream and not here :)

**Comment by StreakyCobra** [comment]
@mckeankylej No you're right to report it here first, we have to check if it is not a bug on our side :-)

**Comment by StreakyCobra** [comment]
Having the libdbus installed doesn't mean emacs has been compiled with it :-)

**Comment by JAremko** [comment]
I think you can determine whether you have proper libdbus bindings or not by running  
 ```:(describe-variable  `dbus-compiled-version)```
 ```:(describe-variable  `dbus-runtime-version)```

**Comment by mckeankylej** [comment]
`dbus-compiled-version` is void 
`dbus-runtime-version` returns 
`dbus-runtime-version is a variable defined in `C source code'.
Its value is "1.8.12"

Documentation:
The version of D-Bus Emacs runs with.` 
What should I do to rebuild my emacs? 
Also should I close this issue and open a new one elsewhere? It seems there is disagreement if these posts are okay.

**Comment by JAremko** [comment]
@mckeankylej  http://lmgtfy.com/?q=Building+Emacs+from+source

**Comment by StreakyCobra** [comment]
As the original issue has been fixed, I'll tag it as `Fixed upstream`, but nothing prevent you to continue the discussion for the other problem here. You may also try to get help from people in [the gitter room](https://gitter.im/syl20bnr/spacemacs) :-)

**Comment by mckeankylej** [comment]
So I built emacs-24.5 from the git mirrors. I am still having the same issues. Is there a way to make sure that emacs is built with dbus?

**Comment by robbyoconnor** [comment]
https://www.gnu.org/software/emacs/manual/html_mono/dbus.html

**Comment by JAremko** [comment]
@mckeankylej   Emacs'es build configuration report includes this information:

```
  Where should the build process find the source code?    .
  What compiler should emacs be built with?               gcc -g -O2 -Wformat -Werror=format-security -Wall
  Should Emacs use the GNU version of malloc?             yes
      (Using Doug Lea's new malloc from the GNU C Library.)
  Should Emacs use a relocating allocator for buffers?    no
  Should Emacs use mmap(2) for buffer allocation?         no
  What window system should Emacs use?                    x11
  What toolkit should Emacs use?                          GTK3
  Where do we find X Windows header files?                Standard dirs
  Where do we find X Windows libraries?                   Standard dirs
  Does Emacs use -lXaw3d?                                 no
  Does Emacs use -lXpm?                                   yes
  Does Emacs use -ljpeg?                                  yes
  Does Emacs use -ltiff?                                  yes
  Does Emacs use a gif library?                           yes -lgif
  Does Emacs use a png library?                           yes -lpng12 -lz -lm
  Does Emacs use -lrsvg-2?                                yes
  Does Emacs use imagemagick?                             yes
  Does Emacs support sound?                               yes
  Does Emacs use -lgpm?                                   yes
```
```
  Does Emacs use -ldbus?                                  yes
``` 
``` 
  Does Emacs use -lgconf?                                 yes 
  Does Emacs use GSettings?                               yes
  Does Emacs use a file notification library?             yes -lgio (gfile)
  Does Emacs use access control lists?                    yes -lacl
  Does Emacs use -lselinux?                               yes
  Does Emacs use -lgnutls?                                yes
  Does Emacs use -lxml2?                                  yes
  Does Emacs use -lfreetype?                              yes
  Does Emacs use -lm17n-flt?                              yes
  Does Emacs use -lotf?                                   yes
  Does Emacs use -lxft?                                   yes
  Does Emacs directly use zlib?                           yes
  Does Emacs use toolkit scroll bars?                     yes
```

**Comment by JAremko** [comment]
For example [Debian's emacs24 package build log](https://buildd.debian.org/status/fetch.php?pkg=emacs24&arch=alpha&ver=24.5%2B1-6%2Bb1&stamp=1453748262)

**Comment by mckeankylej** [comment]
@JAremko where can I find my report?

**Comment by robbyoconnor** [comment]
@mckeankylej, this is something you can google. Odds are you will need to build it yourself. This is not hard.

**Comment by mckeankylej** [comment]
I ran `./config.status --recheck | grep dbus` and found `  Does Emacs use -ldbus?                                  yes` so is this still the issue? Could it be something else?

**Comment by JAremko** [comment]
@mckeankylej   and  `dbus-compiled-version` ?

**Comment by mckeankylej** [comment]
@JAremko same as above still void.

**Comment by robbyoconnor** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Robert

Confirm that you know Robert: https://www.linkedin.com/e/v2?e=0-ini67og8-v3&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=EvU0OSAG&invitationId=6130896965363388416








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini67og8-v3&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFzNFguCh87oQAAAVRVSbj4sn6T6YPi_W_YWkD5XeCTuYVUAnJRbRj7lDJRB3q97YX3Axw7DHgZTb0QrD80xZXaZq_yRwICpc9D8HO96Mznzxvri-g9bp-EAei8qfhMbVvEgkrj_qOjfRl3iFpt_yKRknr0PeAv200SxvCPGoJNKwq4omLK3iDW6PI6Qy_rBJF3&eid=0-ini67og8-v3


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini67og8-v3&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
