### ISSUE TITLE
dotspacemacs-remap-Y-to-y$ not working in develop

### ISSUE THREAD

**Issue by e-matteson** [syl20bnr/spacemacs#5689]
#### Description

When `dotspacemacs-remap-Y-to-y$`  is set to `t` in `dotspacemacs/init`,  `Y` still behaves like `yy` and copies the whole line.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.16
- Spacemacs branch: develop (rev. 0ec385c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spacemacs-helm emacs-lisp)
```

**Comment by TheBB** [comment]
Fixed https://github.com/syl20bnr/spacemacs/commit/7a0328929c9bd4e4b6afe6c7a3fd866a5dd857b2

**Comment by e-matteson** [comment]
This doesn't appear to fix the issue for me. But, with the weirdness going on with hydra rollbacks (I'd already deleted .emacs.d), I'll wait until I'm more confident that my config is not horribly broken in some way.

**Comment by joehillen** [comment]
Not fixed for me either.

**Comment by joehillen** [comment]
It's working for me now.

I noticed that `'(evil-want-Y-yank-to-eol t)` just showed up in my `custom-set-variables` after I clicked "Apply and Save" for a different customization. 

After restarting emacs, it works!

**Comment by e-matteson** [comment]
I was also able to get it to work by customizing `evil-want-Y-yank-to-eol`. Before that, the variable was void. There's still some issue here, because setting `dotspacemacs-remap-Y-to-y$` *should* be sufficient to enable this feature.

**Comment by phinicota** [comment]
Can confirm setting '(evil-want-Y-yank-to-eol t) and SPC f e R is working, maybe someone changed the variable name and forgot to modify the .spacemacs template?

**Comment by darkfeline** [comment]
Fix? https://github.com/syl20bnr/spacemacs/pull/5766

**Comment by e-matteson** [comment]
Works for me, thanks for the fix! I can understand the confusion between those 2 function names... 
 
Closing.
