### ISSUE TITLE
Menuitems is clipped rather than moved to new pages

### ISSUE THREAD

**Issue by simendsjo** [syl20bnr/spacemacs#5866]
#### Description

Spacemacs menus are clipped rather than displayed over several pages

#### Reproduction guide
- Start Emacs
- Press space

*Observed behaviour:*

Menu items are clipped instead of shown moved to new pages. See screenshots.

![Image 1](http://postimg.org/image/73op3o587/)
![Image 2](http://postimg.org/image/wnqza3qlz/)

*Expected behaviour:*

Items that doesn't fit are moved to new pages (as used to be the case)

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: master (rev. 5f26b82)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion better-defaults emacs-lisp git fsharp markdown org mu4e rust spell-checking syntax-checking version-control)
```

#### Backtrace
```
```

**Comment by NJBS** [comment]
I'm unable to see your images, could you try reuploading them or hosting them on an external site?

**Comment by simendsjo** [comment]
Strange. New location:
[Image 1](https://simendsjo.me/files/simendsjo/tmp/img/spacemacs_bug_1.png)
[Image 2](https://simendsjo.me/files/simendsjo/tmp/img/spacemacs_bug_2.png)

**Comment by TheBB** [comment]
Is there any reason this shouldn't be reported to which-key?

**Comment by simendsjo** [comment]
@TheBB I don't know a thing about the Emacs ecosystem, so everything is a Spacemacs issue in my eyes :)

**Comment by TheBB** [comment]
Labeling this as fixed in develop since it seems the clipping is caused by line numbers, which should not be enabled in which-key buffers any more.

**Comment by simendsjo** [comment]
I still have the issue, but I'm inclined to think it's related to i3wm. When I open emacs, the items are clipped, but if I then set the window as fullscreen and back, the items are no longer clipped.

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200. Let us know if you still have any problems with this issue.

**Comment by simendsjo** [comment]
I can verify that the issue is still present in 0.200.1 on emacs 25.1.1 and i3 4.12.
