### ISSUE TITLE
cscope and gtags keybindings tramping on each other

### ISSUE THREAD

**Issue by dubnde** [syl20bnr/spacemacs#5891]
#### Description

I find myself using `cscope` and `gtags` layers depending on the demands of particular projects I am working on. However, the two layers share some of the same keybindings. I am wondering if the `cscope` layer could be remapped to some other keybinding so the `SPC m g` is left for `gtags`. That way, one can use both layers with no keybindings tramping on each other. Currently had to remap `cscope` to `SPC o c` to work with both `cscope` and `gtags` layers
#### Reproduction guide
- Start Emacs
- Add `gtags` layer and add `cscope` layers
- open a C/C++ file
- Try to run `SPC m g`

_Observed behaviour:_
`cscope` ang `gtags` keybindings are mixed.

_Expected behaviour:_
To use `gtags` and `cscope` without the keybindings getting into each other's way.
#### System Info
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.105.19
- Spacemacs branch: develop (rev. b21c717)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:

``` elisp
((auto-completion :variables auto-completion-enable-help-tooltip t auto-completion-enable-snippets-in-popup t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle :disabled-for shell)
 better-defaults
 (colors :variables colors-enable-rainbow-identifiers nil)
 cscope
 (c-c   :variables c-c  -enable-clang-support t c-c  -default-mode-for-headers 'c  -mode)
 emacs-lisp evil-cleverparens evil-commentary
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 (go :variables go-tab-width 4)
 git github gtags haskell html ibuffer javascript markdown
 (org :variables org-enable-github-support t)
 osx plantuml python ruby rust semantic
 (shell :variables shell-enable-smart-eshell t shell-default-position 'right)
 shell-scripts spacemacs-helm spell-checking syntax-checking ruby version-control windows-scripts yaml)
```

**Comment by dubnde** [comment]
I am thinking binding `cscope` to `SPC m c` should fix this. It would not interfere with other bindings since the bindings are done per major mode. In this case for C/C++ mode only. I will go ahead and create a pull request.

**Comment by eullerborges** [comment]
This is still happening to me on develop. `helm-gtags-create-tags` is set instead of `helm-cscope-find-calling-this-function` on `SPC-m-g-c`. 

The keybindings for gtags and cscope are always a mess. They should be put separatedly. You should really consider #5949.
