### ISSUE TITLE
ruby-test-mode package not loading with rest of ruby package

### ISSUE THREAD

**Issue by kofno** [syl20bnr/spacemacs#613]
In order to get the ruby-test behavior/keys, I need to manually turn on ruby-test-mode.

**Comment by kofno** [comment]
Locally, I've made a change to the ruby-test init function: https://github.com/syl20bnr/spacemacs/blob/master/contrib/lang/ruby/packages.el#L148

```elisp
(defun ruby/init-ruby-test-mode ()
  "Define keybindings for ruby test mode"
  (use-package ruby-test-mode
    :defer t
    :init (add-hook 'ruby-mode-hook 'ruby-test-mode)
    :config (progn (evil-leader/set-key "mtb" 'ruby-test-run)
                   (evil-leader/set-key "mtt" 'ruby-test-run-at-point))))
```

This seems to work for me. I can open a PR later, if that will help.

**Comment by syl20bnr** [comment]
Fixed by 91b8731b87ce888c8355b8aabcca368e423ac149

**Comment by carlosgaldino** [comment]
I installed spacemacs yesterday and this issue still persists. I'm completely new so I don't know how I could help.
