### ISSUE TITLE
Erlang-Elixir layer adds duplicate `end`s in Ruby code with both layers active

### ISSUE THREAD

**Issue by shanesveller** [syl20bnr/spacemacs#644]
I'm fairly confident this is due to the `ruby-end` package/mode, which seems to be intended for use only on elixir files as similar functionality is already part of the `ruby` layer.

I'm using emacs-mac-port as recommended, version 24.4.1 on OSX 10.10.2. Spacemacs is version 0.62.1, and I'm testing with a stock `.spacemacs` file except that the `erlang-elixir` and `ruby` configuration layers are enabled. 

Demo GIF:
![spacemacs1](https://cloud.githubusercontent.com/assets/831/6288816/3803edec-b8e1-11e4-8ec6-16c5af6fde29.gif)

It looks like `ruby-end` used to be included in the `ruby` layer based on #106 but was dropped sometime later on.

I will be on Gitter chat most of today, so please @ me if some real-time conversation would be helpful.

I'm not very strong with elisp yet but I would like to keep both of these layers active. I have excluded the `ruby-end` package from being installed in my real `.spacemacs` file for now, but would like to find out if there's a way I can prevent `ruby-end` from activating in Ruby file buffers, or something similar. Since this may trip up or annoy other users that use both layers, it would also be nice to get it fixed upstream if possible.

**Comment by syl20bnr** [comment]
Thank you for the impressive issue, this is the most complete repro step I've seen.

Seems that `ruby-end` wants to be too smart, in its code we can find these wonderful autoloads:

```elisp
;;;###autoload
(add-hook 'ruby-mode-hook 'ruby-end-mode)
;;;###autoload
(add-hook 'enh-ruby-mode-hook 'ruby-end-mode)
```

**Comment by syl20bnr** [comment]
I pushed a fix in the `develop` branch.

**Comment by shanesveller** [comment]
I've tried with the same minimally-configured `.spacemacs` file on SHA 50f230f27f2b0c22db46d9ed5da25ece405aeab4, and I still get the same bad behavior (`ruby-end` minor mode active on a Ruby file). If I also borrow your two `remove-hook` lines from that commit and put them in my `dotspacemacs/config` function, it does prevent the auto-loading and give the desired behavior. I will stick to this technique for now, so please feel free to close this issue if you like, and thanks for your time!

**Comment by aaronjensen** [comment]
This still repros in _spec files on latest develop
