### ISSUE TITLE
Org Mode - Line Number is hidden for top level headings

### ISSUE THREAD

**Issue by pawandubey** [syl20bnr/spacemacs#6568]
#### Description

Line numbers for Top level blocks are not displayed properly in `Org` mode.
![org](https://cloud.githubusercontent.com/assets/2499863/16804490/c60a4012-4929-11e6-999a-219c5bb66ab9.png)
#### Reproduction guide
- Start Emacs
- `C-x C-f` new `org` file.
- Create a top level heading by prepending it with `*`

_Observed behaviour:_
The line number is not visible. On closer inspection it seems like the line number is also made to be the size of the formatted heading, but the line number section does not increase in width to accomodate the increased size of the font.

_Expected behaviour:_
Line number should be displayed and not hidden. The line number bar should increase in width to accomodate the largest sized number.
#### System Info
- OS: gnu/linux
- Emacs: 24.5.2
- Spacemacs: 0.105.21
- Spacemacs branch: master (rev. 0283f64)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:

``` elisp
(auto-completion emacs-lisp git markdown org version-control clojure html ruby ruby-on-rails restclient pandoc)
```

**Comment by Compro-Prasad** [comment]
@pawandubey This should be fixed as of Emacs 26

**Comment by pawandubey** [comment]
I actually don't know if it's fixed since I can't get `line-number-mode` to work with Org mode. Enabling it does nothing even after removing `org-mode` from `:disabled-for-modes` in `dotspacemacs-line-numbers`.

**Comment by pawandubey** [comment]
This is actually not fixed. I'm on Emacs 27 and this is what I see:

<img width="138" alt="screen shot 2018-07-13 at 1 49 54 pm" src="https://user-images.githubusercontent.com/2499863/42706112-b61bc0a4-86a3-11e8-9a8a-19582e8a7588.png">

**Comment by Compro-Prasad** [comment]
That might be `linum-mode`. You can disable it using `M-x linum-mode` then use `M-x display-line-numbers-mode`.

**Comment by thecountoftuscany** [comment]
> This is actually not fixed. I'm on Emacs 27 and this is what I see:
> 
> <img alt="screen shot 2018-07-13 at 1 49 54 pm" width="138" src="https://user-images.githubusercontent.com/2499863/42706112-b61bc0a4-86a3-11e8-9a8a-19582e8a7588.png">

Yes, I see the same too. 

> That might be `linum-mode`. You can disable it using `M-x linum-mode` then use `M-x display-line-numbers-mode`.

There is no match for `display-line-numbers-mode` in my `M-x` listing.

**Comment by Compro-Prasad** [comment]
@thecountoftuscany Your Emacs version?

**Comment by thecountoftuscany** [comment]
@Compro-Prasad Spacemacs 0.300.0 @ emacs 25.3.1

**Comment by Compro-Prasad** [comment]
@thecountoftuscany Then you would need at least version 26 to get `display-line-numbers-mode`
