### ISSUE TITLE
emacs25 with xwidgets

### ISSUE THREAD

**Issue by jvillasante** [syl20bnr/spacemacs#6587]
Has anybody have tried Emacs25 branch with xwidget support?
Compiles perfectly and can be used with mu4e and everything, but I'm having a hard time configuring for evil mode.

Anyone?

**Comment by robbyoconnor** [comment]
Does spacemacs even work there? Part of me wants to spin up a docker container to test this...

**Comment by d12frosted** [comment]
I was gonna try it on weekends.

**Comment by cpaulik** [comment]
I've tried it and spacemacs worked fine. But the xwidgets did not really work for me. Glitches and no way to input anything into e.g. the google search field. Also tried with `emacs -Q` with little luck. I'm on  Arch so that might be a reason.

**Comment by tuhdo** [comment]
At the moment, it's best to use xwidget browser to read things. That is, read only. For interacting with web pages, it needs time. This is pretest, after all.

You can enter text into text box, but it's a bit more complicated:

- First, put cursor in the text box.
- Press `RET`.
- You will see a prompt in minibuffer. Enter whatever you want.
- Press `RET`. Now, text appears in text box.

At the moment, it does not support many Emacs key bindings. However, you can change the mappings in `xwidget-webkit-mode-map` to make it more Vim-like. Here's mine:

```elisp
;; make these keys behave like normal browser
(define-key xwidget-webkit-mode-map [mouse-4] 'xwidget-webkit-scroll-down)
(define-key xwidget-webkit-mode-map [mouse-5] 'xwidget-webkit-scroll-up)
(define-key xwidget-webkit-mode-map (kbd "<up>") 'xwidget-webkit-scroll-down)
(define-key xwidget-webkit-mode-map (kbd "<down>") 'xwidget-webkit-scroll-up)
(define-key xwidget-webkit-mode-map (kbd "M-w") 'xwidget-webkit-copy-selection-as-kill)
(define-key xwidget-webkit-mode-map (kbd "C-c") 'xwidget-webkit-copy-selection-as-kill)

;; adapt webkit according to window configuration chagne automatically
;; without this hook, every time you change your window configuration,
;; you must press 'a' to adapt webkit content to new window size
(add-hook 'window-configuration-change-hook (lambda ()
               (when (equal major-mode 'xwidget-webkit-mode)
                 (xwidget-webkit-adjust-size-dispatch))))

;; by default, xwidget reuses previous xwidget window,
;; thus overriding your current website, unless a prefix argument
;; is supplied
;;
;; This function always opens a new website in a new window
(defun xwidget-browse-url-no-reuse (url &optional sessoin)
  (interactive (progn
                 (require 'browse-url)
                 (browse-url-interactive-arg "xwidget-webkit URL: "
                                             )))
  (xwidget-webkit-browse-url url t))

;; make xwidget default browser
(setq browse-url-browser-function (lambda (url session)
                    (other-window 1)
                    (xwidget-webkit-browse-url url)))
```

**Comment by tuhdo** [comment]
You should bind the mouse buttons as I suggested, so it won't switch to command buffer whenever you scroll up/down with middle button. The same goes for arrow keys. If you want `j` and `k`, add it.

Press `h` in xwidget buffer for list of default bindings.

**Comment by JAremko** [comment]
> Does spacemacs even work there? Part of me wants to spin up a docker container to test this...  

@robbyoconnor  I'm planning to migrate all my stuff to Emacs 25 on Ubuntu(should be less pain than Debian). And make it modular.  I'll try to at least get it up and running this weekend.

**Comment by jvillasante** [comment]
This seems like a neat idea but... At work, when I have to run emacs on a Linux Virtual Machine, it becomes unresponsive, scrolling is so bad that I had to revert back. At home it seems to work, but I'm still worried about the performance imposed when compiling emacs with gtk3.

Also, it is really difficult to interact with the webkit browser. I'll keep trying but ultimately it is a feature that would be nice to have but only if it dosn't get on the way of everyday emacs usage.

Really looking into what other people feel about this!!!

**Comment by tuhdo** [comment]
> This seems like a neat idea but... At work, when I have to run emacs on a Linux Virtual Machine, it becomes unresponsive, scrolling is so bad that I had to revert back. At home it seems to work, but I'm still worried about the performance imposed when compiling emacs with gtk3.

Have you tried setting scrolling to this?

```elisp
(define-key xwidget-webkit-mode-map [mouse-4] 'xwidget-webkit-scroll-down)
(define-key xwidget-webkit-mode-map [mouse-5] 'xwidget-webkit-scroll-up)
```

About gtk3, why do you think there's performance impact when compiled with it? I had no problem even when using on low-end machine or virtual machine. I think it's the default when you install Emacs with a package manager in Linux.

**Comment by tuhdo** [comment]
The interaction with the web browser is a bit rough now. However, in the future I expect that we will have something like `xwidget-webkit-self-insert-command` and `xwidget-webkit-isearch` and `avy-xwidget-jump-char/link` etc... It's easy to retrieve a character in xwidget browser and update the appropriate xwidget textbox at point with JS. I can already do that with this code:

```elisp
(defun xwidget-webkit-self-insert-command-a ()
  (interactive)
  (let* ((xww (xwidget-webkit-current-session))
         (field-value
          (progn
            (xwidget-webkit-execute-script-rv
             xww
             "findactiveelement(document).value;")))
         (field-type (xwidget-webkit-execute-script-rv
                      xww
                      "findactiveelement(document).type;")))
    (xwidget-webkit-execute-script
     xww
     (format "findactiveelement(document).value='%s'"
             (concat field-value "a")))))

(define-key xwidget-webkit-mode-map (kbd "a") 'xwidget-webkit-self-insert-command-a)
```

The above code assign key `a` to `xwidget-webkit-self-insert-command-a`, so whenever you press/hold `a` in a textbox, it inserts `a` continuously. Now that I have this function, it's easy to create a macro that generate a function for each key, from `a` to `z`.

Demo:

![emacs_xwidget_insert_char](https://cloud.githubusercontent.com/assets/4818719/16894333/243bd51a-4b7d-11e6-8e45-9493efc7745b.gif)

With that, it's also easy to create something like `xwidget-webkit-beginning-of-line` and so on.

**Comment by jvillasante** [comment]
> About gtk3, why do you think there's performance impact when compiled with it? I had no problem even when using on low-end machine or virtual machine. I think it's the default when you install Emacs with a package manager in Linux.

When I talk about gtk3 and scrolling problems it is not about xwidget-webkit buffer. At work when I compiled emacs with gtk3 and xwidgets all other buffers became a pain to scroll and emacs keep crashing on me, I reverted back to compiling without xwidgets and that solved the problem.

**Comment by jvillasante** [comment]
Here's my complete configuration thanks to Tuhdo. Notice that for now I have to disable evil on xwidget. Please, share your configurations too!!!

```
(evil-set-initial-state 'xwidget-webkit-mode 'emacs)
(add-hook 'xwidget-webkit-mode-hook
          (lambda ()
            (define-key xwidget-webkit-mode-map [mouse-4] 'xwidget-webkit-scroll-down)
            (define-key xwidget-webkit-mode-map [mouse-5] 'xwidget-webkit-scroll-up)
            (define-key xwidget-webkit-mode-map (kbd "<up>") 'xwidget-webkit-scroll-down)
            (define-key xwidget-webkit-mode-map (kbd "<down>") 'xwidget-webkit-scroll-up)
            (define-key xwidget-webkit-mode-map (kbd "M-w") 'xwidget-webkit-copy-selection-as-kill)
            (define-key xwidget-webkit-mode-map (kbd "C-c") 'xwidget-webkit-copy-selection-as-kill)

            ;; make xwidget default browser (not for now... maybe in the future!)
            ;; (setq browse-url-browser-function (lambda (url session)
            ;;                                     (other-window 1)
            ;;                                     (xwidget-browse-url-no-reuse url)))

            ;; adapt webkit according to window configuration change automatically
            ;; without this hook, every time you change your window configuration,
            ;; you must press 'a' to adapt webkit content to new window size
            (add-hook 'window-configuration-change-hook (lambda ()
                                                          (when (equal major-mode 'xwidget-webkit-mode)
                                                            (xwidget-webkit-adjust-size-dispatch))))

            ;; by default, xwidget reuses previous xwidget window,
            ;; thus overriding your current website, unless a prefix argument
            ;; is supplied
            ;;
            ;; This function always opens a new website in a new window
            (defun xwidget-browse-url-no-reuse (url &optional sessoin)
              (interactive (progn
                             (require 'browse-url)
                             (browse-url-interactive-arg "xwidget-webkit URL: "
                                                         )))
              (xwidget-webkit-browse-url url t))))
```

**Comment by JAremko** [comment]
@jvillasante  It would be cool if someone make some kind of package or Spacemacs layer out of it. 
Just saying. :wink:

**Comment by tuhdo** [comment]
I completed the macro that generate a function for each key. Initially, I used `(interactive "c")` to get a character to insert into a textbox, but this approach always needs 2 steps for inserting a character:

- Press a key to activate the command. The command is now wait for a character.
- You have to press a key again.

So, for every character two key presses are required. That's why I created a macro for each key with its character:

```elisp
(defmacro xwidget-webkit-define-self-insert-command (c)
  `(let* ((function-name (quote ,(intern (concat "xwidget-webkit-self-insert-command-" c)))))
     (defun ,(intern (concat "xwidget-webkit-self-insert-command-" c)) (xw value c)
       (interactive
        (let* ((xww (xwidget-webkit-current-session))
               (field-value
                (progn
                  (xwidget-webkit-execute-script xww xwidget-webkit-activeelement-js)
                  (xwidget-webkit-execute-script-rv
                   xww
                   "findactiveelement(document).value;")))
               (field-type (xwidget-webkit-execute-script-rv
                            xww
                            "findactiveelement(document).type;")))
          (list xww field-value ,c)))
       (xwidget-webkit-execute-script
        xw
        (format "findactiveelement(document).value='%s'"
                (concat value ,c)))
       )
     (define-key xwidget-webkit-mode-map (kbd ,c) function-name)))

(defun xwidget-webkit-define-keys ()
  (mapcar (lambda (l)
            (message "l is %s" l)
            (eval l))
          (mapcar (lambda (c)
                    `(xwidget-webkit-define-self-insert-command ,(char-to-string c)))
                  (number-sequence 41 176 1))))


(xwidget-webkit-define-keys)
```

The effect of this is that now you can pretty much enter anything in a textbox:

![emacs_xwidget_insert_chars](https://cloud.githubusercontent.com/assets/4818719/16895457/1738117a-4ba1-11e6-8b50-484bdad6f187.gif)

**Comment by JAremko** [comment]
Chrome has [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb) I hope one day we'll integrate something like this into Spacemacs.

**Comment by tuhdo** [comment]
I'm making a layer out of it.

**Comment by jvillasante** [comment]
> I'm making a layer out of it.

Great!!! Let us know when is ready, and please, make webkit the default browser configurable!
On another thread, I'm starting to worry about security. Running a webkit enable browser inside emacs without a sandbox could be super dangerous. Also, browsers can be updated when security risks are found but the emacs update could potentially take forever. That means that we will be running a complete unsecure full webkit enable old browser inside emas. Right now I see myself using it to read mu4e emails and for helm-dash documentation, but still worry about any security risks.

**Comment by tuhdo** [comment]
Done: https://github.com/syl20bnr/spacemacs/pull/6604

> Great!!! Let us know when is ready, and please, make webkit the default browser configurable!
> On another thread, I'm starting to worry about security. Running a webkit enable browser inside emacs without a sandbox could be super dangerous. Also, browsers can be updated when security risks are found but the emacs update could potentially take forever. That means that we will be running a complete unsecure full webkit enable old browser inside emas. Right now I see myself using it to read mu4e emails and for helm-dash documentation, but still worry about any security risks. I don't know, but it feels that it should be running on a sandbox or something!

Yes, it's best to use for reading HTML doc, trusted HTML website and viewing HTML emails. `helm-dash` is offline, so it looks fine to me.

**Comment by benyomin** [comment]
Here's the 2 commands I tried, but I don't have it working yet.  I think I'm still missing some kind of gtk-dev library.
`brew install --build-from-source at-spi2-core at-spi2-atk cairo harfbuzz pango gtk+3 gtk+ librsvg gnome-icon-theme --without-x --without-x11 --with-gtk+3
brew reinstall emacs-plus --with-cocoa --without-gnutls --with-librsvg --with-imagemagick --with-x-toolkit=gtk3 --with-xwidgets --HEAD --use-git-head`

**Comment by d12frosted** [comment]
@benyomin you have to build without cocoa, but with x. Otherwise xwidgets will not work

**Comment by benyomin** [comment]
@d12frosted thanks, I may make emacs-plus with xwidgets then and emacs-mac with cocoa then to have one of each.
