### ISSUE TITLE
Fail to install evil-unimpaired

### ISSUE THREAD

**Issue by chengyi** [syl20bnr/spacemacs#6933]
#### Description :octocat:
Fail to install evil-unimpaired

#### Reproduction guide :beetle:
- Start Emacs
- install evil-unimpaired

*Observed behaviour:* :eyes: :broken_heart:
--> refreshing package archive: gnu-cn... [3/3]
--> installing package: evil-unimpaired@spacemacs-evil... [1/1]
An error occurred while installing evil-unimpaired (error: (wrong-type-argument arrayp nil))

*Expected behaviour:* :heart: :smile:
install evil-unimpaired successfully

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: develop (rev. 185fb67)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(ivy better-defaults emacs-lisp markdown org lua python colors git spacemacs-layouts ranger
     (c-c   :variables c-c  -default-mode-for-headers 'c  -mode)
     ycmd auto-completion)
```

#### Backtrace :paw_prints:
```
Saving file /home/prow/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20160824.03648.el...
Wrote /home/prow/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20160824.03648.el
Wrote /home/prow/.emacs.d/.cache/quelpa/packages/evil-unimpaired-readme.txt
Error getting PACKAGE-DESC: (file-error Opening input file No Such file or directory /home/prow/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20160824.3648.el)
```

**Comment by d12frosted** [comment]
@chengyi could you please try removing `~/.emacs.d/.cache` and starting emacs again?

**Comment by chengyi** [comment]
I delete the cache, it doesn't happen again. Seems the melpa-repo's problem.

**Comment by houli** [comment]
Also having (the same?) similar issue
```
(Spacemacs) --> installing package: evil-unimpaired@spacemacs-evil... [1/1]
Fetcher: file
Source: nil

Saving file /Users/eoinhoulihan/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20160831.00141.el...
Wrote /Users/eoinhoulihan/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20160831.00141.el
Wrote /Users/eoinhoulihan/.emacs.d/.cache/quelpa/packages/evil-unimpaired-readme.txt
Error getting PACKAGE-DESC: (file-error Opening input file No such file or directory /Users/eoinhoulihan/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20160831.141.el)
```
Notice the file it's looking for is 141.el vs 00141.el

**Comment by d12frosted** [comment]
@houli just in case, did you clear `~/.emacs.d/.cache/quelpa`? Also it would be helpful to know a little more about what you did to run into this issue. For example, what version of Spacemacs you were using when everything worked fine and what version you are using now. 👍

**Comment by houli** [comment]
```
From https://github.com/syl20bnr/spacemacs
   64a0cc2..4e7d80b  develop    -> origin/develop
```
Went to latest develop this evening and Emacs started fine. It broke when I updated my packages.
Deleting the quelpa cache folder is not helping either.

**Comment by d12frosted** [comment]
@houli hm... not sure what's the problem then. It's really strange that it's looking for wrong file. This might be upstream problem. What version of `quelpa` are you using?

**Comment by d12frosted** [comment]
Also I wonder, if clearing `~/.emacs.d/.cache` helps. Because originally I asked @chengyi to wipe not only `quelpa` cache, but all cache. Not sure why though.

**Comment by houli** [comment]
I was on `quelpa-20160325.629` seems kind of very old. Not sure why Spacemacs never offered to update it. Anyway I deleted it from the elpa directory and got 20160818 which didn't help. Deleting the whole cache directory was also no good.

**Comment by chengyi** [comment]
@houli the file downloaded with name `evil-unimpaired-0.1pre0.20160824.03648.el` but getting package desc with name `evil-unimpaired-0.1pre0.20160824.3648.el`. It seems somewhere cutoff the zero.  this will not happen on every version of `evil-unimpaired`.@TheBB

**Comment by Softsapiens** [comment]
@d12frosted  fixed for me deleting .../.cache
Thanks!

**Comment by goofansu** [comment]
Same after upgraded to most recent evil-unimpaired

```
Skipping rebuild of /Users/suyejun/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20161002.03002.el
Error getting PACKAGE-DESC: (file-error Opening input file No such file or directory /Users/suyejun/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20161002.3002.el)
Cannot load evil-unimpaired
```

**Comment by adamczykm** [comment]
Bump. The same story for me.

**Comment by d12frosted** [comment]
Related: #7274

**Comment by net** [comment]
Same issue here. Emacs 25.1.1.

**Comment by MRFaria** [comment]
Happens to me running 25.1 
Cloning https://github.com/melpa/melpa.git to /home/user011/.emacs.d/.cache/quelpa/melpa
Cannot load evil-unimpaired

**Comment by d12frosted** [comment]
I don't get the relation between issues with loading `evil-unimpaired` and `melpa.git`.

**Comment by iamitava** [comment]
@MRFaria do you get any error from running `git clone https://github.com/melpa/melpa.git /home/user011/.emacs.d/.cache/quelpa/melpa`?

@d12frosted I had the exact same issue. I guess `evil-unimpaired` is in the picture since this is the only package that is fetched from melpa (others being fetched via url)? Once I fixed the git issue (required an SSL cert for work), the package installation proceeded smoothly.

**Comment by d12frosted** [comment]
@iamitava `evil-unimpaired` is the only package that is fetched using `local` fetcher. All other 'local' packages are staying under `local` directories of layers and loaded just by modifying load path. Other packages (non-local) are installed from elpa or github.

**Comment by sindikat** [comment]
I have this problem on 2 different machines. Just today I installed fresh Spacemacs, master branch, and got this (part of my `*Messages*` buffer):

    ...
    Loading /home/mi134/.emacs.d/layers/auto-layer.el (source)...done
    (Spacemacs) --> refreshing package archive: melpa... [1/3]
    Contacting host: melpa.org:443
    Importing package-keyring.gpg...done
    Contacting host: melpa.org:443
    (Spacemacs) --> refreshing package archive: org... [2/3]
    Contacting host: orgmode.org:80
    Importing package-keyring.gpg...done
    (Spacemacs) --> refreshing package archive: gnu... [3/3]
    Importing package-keyring.gpg...done
    Contacting host: elpa.gnu.org:443
    (Spacemacs) --> installing package: evil-unimpaired@spacemacs-evil... [1/1]
    Fetcher: file
    Source: nil
    
    Cannot load evil-unimpaired
    Loading /home/mi134/.emacs.d/layers/+distributions/spacemacs-base/keybindings.el (source)...done
    Loading /home/mi134/.emacs.d/layers/+emacs/better-defaults/keybindings.el (source)...done
    Loading /home/mi134/.emacs.d/layers/+source-control/version-control/keybindings.el (source)...done
    Loading /home/mi134/.emacs.d/.cache/spacemacs-buffer.el (source)...done
    ...

`emacs-version` returns: `GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-17 on lgw01-04, modified by Debian`

**Comment by eeach** [comment]
I'm having this problem on Arch Linux. A completely fresh account. Emacs 25.1.1

I get this in the message buffer: 

```
(Spacemacs) --> installing package: evil-unimpaired@spacemacs-evil... [1/1]
Cloning https://github.com/melpa/melpa.git to /home/alex2/.emacs.d/.cache/quelpa/melpa
Fetcher: file
Source: nil

File: /home/alex2/.emacs.d/.cache/quelpa/build/evil-unimpaired/evil-unimpaired.stamp
Saving file /home/alex2/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20161201.02153.el...
Wrote /home/alex2/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20161201.02153.el
Wrote /home/alex2/.emacs.d/.cache/quelpa/packages/evil-unimpaired-readme.txt
Error getting PACKAGE-DESC: (file-error Opening input file No such file or directory /home/alex2/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20161201.2153.el)
Cannot load evil-unimpaired
Loading /home/alex2/.emacs.d/layers/+distributions/spacemacs-base/keybindings.el (source)...done
Spacemacs is ready.
```

So, I copied evil-unimpaired-0.1pre0.20161201.**02153**.el to evil-unimpaired-0.1pre0.20161201.**2153**.el and restarted emacs. Everything seemed okay after that. :-)

**Comment by zarzen** [comment]
It seems always produce a redundant 0.
In my situation:
```
~/.emacs.d/.cache/quelpa/packages$ mv evil-unimpaired-0.1pre0.20161213.05040.el evil-unimpaired-0.1pre0.20161213.5040.el
```
Thanks @eeach for pointing out this.

**Comment by sethbc** [comment]
@eeach fixed it the same way on my windows box, thanks

**Comment by motecshine** [comment]
remove `~/.emacs.d/.cache` work for me

**Comment by DoaneAS** [comment]
same pattern here with redundant 0. 
Fix for me was:
`mv evil-unimpaired-0.1pre0.20161226.03105.el evil-unimpaired-0.1pre0.20161226.3105.el`

**Comment by Ch4s3** [comment]
I tried @DoaneAS's solution and it didn't work for me

**Comment by byumov** [comment]
Same issue, clean install:
--> installing package: evil-unimpaired@spacemacs-evil... [1/1]
An error occurred while installing evil-unimpaired (error: (wrong-type-argument arrayp nil))

**Comment by praduca** [comment]
One week with the problem, and @DoaneAS  solved the issue... 
strangely enough, trying to reproduce the bug with a clean reinstall (only spacemacs, not emacs) didn't fail.
It is possible that those version number are being generated at more than one place? I mean, more than one build script or something like that are being used?

**Comment by motecshine** [comment]
@Ch4s3  attention your  `evil-unimpaired-0.1pre***` version

**Comment by schuylermaclay** [comment]
+1 for @DoaneAS's solution, just to clarify, your renaming the file with the last leading 0, so the exact command you want to run will be slightly different: 
`mv ~/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.********.0****.el ~/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.********.****.el`

**Comment by jkw** [comment]
How come this issue is closed when the issue still occurs? I just encountered it. Tried cleaning cache, same error.

**Comment by mjin955** [comment]
@jkw try the fix from @DoaneAS 

~/.emacs.d/.cache/quelpa/packages$ mv evil-unimpaired-0.1pre0.20161226.03105.el evil-unimpaired-0.1pre0.20161226.3105.el

**Comment by SteveJobzniak** [comment]
This is still a bug.

Fixed by:

```
cd ~/.emacs.d/.cache/quelpa/packages
mv evil-unimpaired-20170601.00304.el evil-unimpaired-20170601.304.el
```

Geeze. Just fix whatever is making it download as 00304, or whatever is making it look for 304 (without 00).

**Comment by epsilon-0** [comment]
I am on windows and this bug is still there.
I have a fresh install running on the master branch and I do **_not_** have a folder called **packages** in `%HOME%\.emacs.d\.cache\quelpha `

**Comment by dschrempf** [comment]
I can confirm that this is still an issue. As reported, the following works:

    cd ~/.emacs.d/.cache/quelpa/packages
    mv evil-unimpaired-20170601.00304.el evil-unimpaired-20170601.304.el

**Comment by Ron89** [comment]
At this moment, the command to fix it is `mv evil-unimpaired-0.1pre0.20170629.04242.el evil-unimpaired-0.1pre0.20170629.4242.el`
It appears to be a pattern issue. the last version field should be formatted as `%05d`.

**Comment by houli** [comment]
@Ron89 does that format string appear in the code somewhere of quelpa? Would be worth submitting an issue/PR if you've found the root cause

**Comment by Ron89** [comment]
It doesn't. All I can tell so far is that the number is part of the time stamp, and it's in seconds rather than HMS like a normal time stamp. And somehow the file name format string (`%05d` from the looks of it) is different from some routine which expect it to be named by `%d` format.

Maybe I can spend some more time on this on weekends.

**Comment by joaopaulo23** [comment]
I just disabled it. I prefeer emacs sintax. To disable you just need to go on the file 
/layers/+spacemacs/spacemacs-evil/packages.el and comment the lines
241 and line 243.

**Comment by barischrooneyj** [comment]
Just to show it's still an issue. On an almost new install of Sierra with vanilla Spacemacs config.

Tried install packages once, then `SPC q r`, tried again, \*messages\*:
```
(Spacemacs) --> installing package: evil-unimpaired@spacemacs-evil... [1/1]
Fetcher: file
Source: nil

Skipping rebuild of /Users/jeremy/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20170818.00556.el
Error getting PACKAGE-DESC: (file-error Opening input file No such file or directory /Users/jeremy/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20170818.556.el)
Cannot load evil-unimpaired
```

`SPC h d s`:
```
#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
` ``elisp
(helm emacs-lisp)
` ``
- System configuration features: NOTIFY ACL LIBXML2 ZLIB
```

**Comment by duianto** [comment]
marienz might have found the cause: https://github.com/syl20bnr/spacemacs/issues/8901#issuecomment-304492105

When evil-unimpared is installed between midnight and 1AM, then the time stamp has two leading 0's, but only one of them gets removed.

**Comment by aprasadh** [comment]
Deleting the `~/.emacs.d/.cache` directory solved the problem for me. Thanks.

**Comment by samhains** [comment]
I had another solution for this. I realized that this install was not completing as I had github installed on Windows Linux Subsystem, but not on Windows itself.

**Comment by tbsvttr** [comment]
Still an issue. Just installed first time on macOS.

**Comment by soloradish** [comment]
@eeach 's soluthion really helped

**Comment by codygman** [comment]
It is fixed it [looks like](https://github.com/quelpa/quelpa/issues/132). When will spacemacs sync quelpa again? Can we force it?

**Comment by SteveJobzniak** [comment]
@codygman Yep!

https://github.com/syl20bnr/spacemacs/issues/8901#issuecomment-340371744
https://github.com/quelpa/quelpa/issues/132#issuecomment-343659712

The issue was that if we were working at the computer between midnight and 1 at night, the packages were named "001022" as their filename time component in memory. Then it stripped one zero as 01022" pn the in-memory filename string. But the file on disk was named 1022. So the fix was to make the regex eat all leading zeroes.

I guess quelpa is not a normal package since it is a package manager.

Therefore @d12frosted @syl20bnr - Please sync the quelpa sources? ;)

**Comment by jrmiller82** [comment]
Still a bug and shouldn't be closed. I updated packages at 12:05 ish local time, and ran into the extra `00` in front of the numbers. This needs to be fixed. 

The below fixed it (getting rid of the `00` on my local file). 

> This is still a bug.
> 
> Fixed by:
> 
> cd ~/.emacs.d/.cache/quelpa/packages
> mv evil-unimpaired-20170601.00304.el evil-unimpaired-20170601.304.el
> 
> Geeze. Just fix whatever is making it download as 00304, or whatever is making it look for 304 (without 00).

**Comment by SteveJobzniak** [comment]
@jrmiller82 because spacemacs has not yet fixed this line by updating quelpa sources:

https://github.com/syl20bnr/spacemacs/blob/4bb4cb46968e5bbb98fffd480c8c822269fced4f/core/libs/quelpa.el#L345

**Comment by jrmiller82** [comment]
Then why is the issue marked closed?

**Comment by SteveJobzniak** [comment]
"Chengyi closed this on Aug 27, 2016".

**Comment by SteveJobzniak** [comment]
Since this is closed and getting lost in the swarm of other discussions, I made a new one for this quick and easy fix:

https://github.com/syl20bnr/spacemacs/issues/9961

**Comment by dl-wuhee** [comment]
I also met this problem on Win10. 

According to the warning information, I run Emacs by administrator account, and this problem is solved.

**Comment by marekyggdrasil** [comment]
I had same problem on OSX 10.15.7 (19H2) Catalina. If I run spacemacs by clicking the icon on the dock that was exactly the problem I encounter, however if instead I run spacemacs by running `emacs` in the terminal then update is passing correctly and no problem with `evil-unimpaired`.
