### ISSUE TITLE
Layouts refuse to auto save

### ISSUE THREAD

**Issue by gilbertw1** [syl20bnr/spacemacs#7105]
#### Description
Layouts refuse to auto save on when closing Spacemacs or on the defined auto save interval.

#### Reproduction guide
- Start Emacs
- Create new perspective
- Close Emacs
- Start Emacs
- Layout was not auto saved.

*Observed behaviour:*
Any modifications to an existing layout are lost on restarting spacemacs.

*Expected behaviour:*
Any modifications to an existing layout should be saved automatically when closing the app or on the defined auto save interval, and should be visible on starting spacemacs.

#### System Info
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(emacs-lisp
 (spacemacs-layouts :variables layouts-enable-autosave t layouts-autosave-delay 300)
 git markdown
 (org :variables org-enable-github-support t)
 games dash restclient
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control xkcd auto-completion rust javascript
 (scala :variables scala-auto-start-ensime nil)
 haskell scheme
 (ranger :variables ranger-show-preview t ranger-cleanup-on-disable t)
 (clojure :variables clojure-enable-fancify-symbols t)
 themes-megapack github
 (evil-snipe :variables evil-snipe-enable-alternate-f-and-t-behaviors t)
 sql format-sql)
```

#### Backtrace
No Bactrace

Layouts have saved properly in the past, however after recently updating Spacemacs and packages I cannot get layouts to auto save anymore. 

I've tried removing and creating a completely clean emacs.d directory as well as switching to the 'develop' branch to no avail. I can place an old 'persp-auto-save' file (from the an old emacs.d directory) in the layouts cache directory and it properly loads the layouts on startup, but refuses to save any changes to the layouts. I can also manually save layouts with no problem. 

You can find my current .spacemacs config file [here.](https://gist.github.com/gilbertw1/e2582ab1bc17b0ec3530df49b49c72da) Any assistance or workarounds would be greatly appreciate as this is a rather large pain for me at the moment.

Thanks!

**Comment by gilbertw1** [comment]
Looking throught the persp-mode github I found the following commit:

https://github.com/Bad-ptr/persp-mode.el/commit/f6f24750132883b3fac377c93edbec4c437be872

Reverting this change solved the problem for me and auto saving on exit is again working properly.

**Comment by TheBB** [comment]
We're sidestepping that hook by calling `(kill-emacs)` instead of `(save-buffers-kill-emacs)`. We should probably use the latter?

**Comment by TheBB** [comment]
https://github.com/syl20bnr/spacemacs/pull/7110

**Comment by gilbertw1** [comment]
Thanks for the quick turnaround! :+1:

**Comment by jluttine** [comment]
Is this fixed upstream? I'm still having this issue with the latest develop branch at point @cf951a511400dd8c4b69bd69d807a09220761ccb.

**Comment by gilbertw1** [comment]
Yep, It's currently working properly for me in master. The issue I originally reported affected both master and develop, and was fixed upstream in the persp-mode package. It's possible that your encountering a separate issue that's been introduced in the develop branch.

**Comment by jluttine** [comment]
Ok, thanks. However, I now tried master @9f9faa404e3dec3e08cc73cf7b5a0439fc309800 but it doesn't work either.. Should I make a separate bug report or is there some information I could provide here?

**Comment by jluttine** [comment]
Ah, now I got it working with master. Just needed to delete my layout file and save it again. However, develop is still broken for me.

**Comment by gilbertw1** [comment]
Yea, I've noticed updates to the persp-mode package occasionally causes problems with existing saved layout files requiring them to be deleted. However, if it is working correctly in master then your probably experiencing a different problem and not the one I outlined above.

**Comment by d12frosted** [comment]
@jluttine `Fixed upstream` means that it was fixed in 3rd party package. In order to get fix you have to update that package and not Spacemacs (but better to do both).
