### ISSUE TITLE
React framework layer keybindings incorrect?

### ISSUE THREAD

**Issue by TheAncientGoat** [syl20bnr/spacemacs#7175]
#### Description
Using the keybindings defined in https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bframeworks/react/README.org results in "$keybinding is undefined" for most of the listed keybindings - is this a misconfiguration on my part, or is the documentation out-of-date?

e.g. SPC m g g should find the definition of the symbol under the cursor, but is undefined, the keybinding according to Descbinds is C-M-. (which doesn't feed the symbol under the cursor either, requiring manual entry)

#### Reproduction guide
- Start Emacs
- add react later to .spacemacs
- open any .jsx or .react.js file
- try keybindings defined in the react layer documentation

*Observed behaviour:*
Undefined keybindings

*Expected behaviour:*
Keybindings to work as described in documentation

#### System Info
- OS: gnu/linux
- Emacs: 25.1.1
- Spacemacs: 0.105.22
- Spacemacs branch: master (rev. 9f9faa4)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(auto-completion emacs-lisp git markdown org spell-checking syntax-checking version-control react)
```

**Comment by d12frosted** [comment]
I don't see those key bindings configured. This is fixed in `develop` branch. Try enabling `html` and `javascript` layers along with `react`. At least this is how it's configured on `develop`.

**Comment by TheAncientGoat** [comment]
Installing the extra layers in stable did not fix - but switching to develop seems to have done the trick - thanks; should the bug stay open until the fix is in master?

**Comment by d12frosted** [comment]
Fixed with released of Spacemacs v0.200.
