### ISSUE TITLE
exec-path-from-shell seems to run _late_ on macOS

### ISSUE THREAD

**Issue by swaroopch** [syl20bnr/spacemacs#7452]
#### Description :octocat:

exec-path-from-shell seems to run _late_ on macOS...

#### Reproduction guide :beetle:

- Set GOPATH in shell config file
- Enable go layer
- Start Emacs

*Observed behaviour:* :eyes: :broken_heart:
- During startup, I see warning: `Warning: GOPATH variable not found, go-guru configuration skipped.`
- After startup, If I run `M-: (getenv "GOPATH")`, it shows the correct path.

*Expected behaviour:* :heart: :smile:
No warnings. Guru configured.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.2
- Spacemacs branch: develop (rev. 5771484)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults clojure django emacs-lisp git github
      (go :variables go-use-gometalinter t)
      html javascript markdown
      (org :variables org-enable-github-support t org-enable-bootstrap-support t)
      osx python rust
      (shell :variables shell-default-shell 'eshell shell-default-height 30 shell-default-position 'bottom)
      sql syntax-checking version-control yaml)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:

N/A

**Comment by NJBS** [comment]
> Set GOPATH in shell config file

Which shell and which config file?

**Comment by swaroopch** [comment]
I use default shell on macOS... `$SHELL` shows `/bin/bash`.

I have `export GOPATH="$HOME/code/golang"` in `~/.bash_profile`.

**Comment by agzam** [comment]
maybe if you try to run `getenv` in `with-eval-after-load` block?

**Comment by swaroopch** [comment]
> @agzam wrote: maybe if you try to run getenv in with-eval-after-load block?

I'm not sure I follow. The getenv is being run in the go layer - https://github.com/syl20bnr/spacemacs/blob/5771484668c4764b8cd970836ffe7e4900572513/layers/%2Blang/go/packages.el#L116

**Comment by swaroopch** [comment]
To elaborate, this issue I'm facing is not specific to the go layer, I also see `(Spacemacs) Warning: tern binary not found!`, but after startup, `(executable-find "tern")` shows `"/usr/local/bin/tern"`.

**Comment by agzam** [comment]
@swaroopch `(with-eval-after-load 'go-mode ...`

**Comment by TheBB** [comment]
This is fixed in develop, in any case. https://github.com/syl20bnr/spacemacs/pull/7457

**Comment by swaroopch** [comment]
@TheBB Nice, but I still get `(Spacemacs) Warning: tern binary not found!`, and after startup, `(executable-find "tern")` shows `"/usr/local/bin/tern"`

**Comment by AndreaOrru** [comment]
I can confirm I'm getting the same warning. However, Tern works fine in Javascript mode.

**Comment by liujoey** [comment]
I got the same warning `(Spacemacs) Warning: tern binary not found!`, it feels like during the startup, the function `spacemacs//tern-detect ()` was run before `exec-path` was set.

**Comment by TheBB** [comment]
It shouldn't be, the exec-path-from-shell package is in the pre step.

In any case, this issue is not about tern but go-guru and the code that issues this warning was removed, thus fixed.

**Comment by TheBB** [comment]
Should be fixed on master.

**Comment by cjohansson** [comment]
Same issue here, I have the latest stable version of Spacemacs `0.200.5@25.1.1`
