### ISSUE TITLE
emacs 26.0 version has not the insert-string function

### ISSUE THREAD

**Issue by linux-xhyang** [syl20bnr/spacemacs#7790]
(defun spacemacs-buffer/insert-ascii-banner-centered (file)
  (insert-string
   (with-temp-buffer
     (insert-file-contents file)
     (let ((banner-width 0))
       (while (not (eobp))
         (let ((line-length (- (line-end-position) (line-beginning-position))))
           (if (< banner-width line-length)
               (setq banner-width line-length)))
         (forward-line 1))
       (goto-char 0)
       (let ((margin (max 0 (floor (/ (- spacemacs-buffer--banner-length banner-width) 2)))))
         (while (not (eobp))
           (insert (make-string margin ?\ ))
           (forward-line 1))))
     (buffer-string))))

**Comment by bmag** [comment]
Already fixed in develop by #7676

**Comment by bmag** [comment]
duplicate of #7727, by the way, but I'm leaving this one open so we have a "Fixed in develop" marker.

**Comment by schaary** [comment]
I still get the error message with emacs version 26.0.50 and spacemacs v0.200.7

+++ snip +++
Loading /Users/nmaef/.emacs.d/core/core-load-paths.el (source)...done
Warning (initialization): An error occurred while loading ‘/Users/nmaef/.emacs.d/init.el’:

Symbol's function definition is void: insert-string

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
+++ snap +++

I run spacemacs at version:
```
* c2774bc0 - (HEAD -> master, tag: v0.200.7, origin/release-0.200, origin/master, origin/HEAD) Bump version to 0.200.7 and update CHANGELOG.org (8 weeks ago) <syl20bnr>
```

My emacs version:
```
GNU Emacs 26.0.50
Copyright (C) 2017 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

I run macOS Sierra 10.12.3

**Comment by schleumer** [comment]
I'm getting this error `Symbol's function definition is void: insert-string` in a fresh spacemacs install on Emacs Snapshot for Ubuntu 16.04.

**Comment by kedare** [comment]
Same for me

**Comment by bmag** [comment]
Workaround for those who use master branch (stable release): add to your `.spacemacs` the following:
```elisp
(defalias 'insert-string 'insert)
```
If putting it in `user-init` doesn't work, try putting it in the beginning of `.spacemacs`, and if that doesn't work either then put it in the beginning of `~/.emacs.d/init.el`.
