### ISSUE TITLE
Problem with multiple project layouts and SPC p f

### ISSUE THREAD

**Issue by artukrap** [syl20bnr/spacemacs#8248]
#### Description :octocat:
I have now two layouts for each project. Created them using `SPC p l`.
However, when I switch between them with `SPC l 2` or `SPC l 3` and try to do `SPC p f` it searches only in project 2, nevertheless I am currently in project layout 3.

#### Reproduction guide :beetle:
- Start Emacs
- `SPC p l` choose project called apples
- `SPC l` to verify it's on layout 2, because 1 is layout 1
- `SPC p f` try to search for file User.ex which is found and I can open it
- `SPC p l` choose project cars
- `SPC l 2` choose project apples
- `SPC p f` open file from project apples mix.exs
- `SPC l 3` choose project cars
- `SPC p f` Search for file Car.ex and it can't find, because it search in project apples, however I just did `SPC l 3` which should switch project root to project cars

*Observed behaviour:* :eyes: :broken_heart:
Just can't open cars project file and switching between projects hurts my heart.

*Expected behaviour:* :heart: :smile:
I expect flawless transition between projects and ability to `SPC p f` search in current project, not in previous project root

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 9ac779a)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(php helm auto-completion better-defaults emacs-lisp git markdown
     (shell :variables shell-default-shell 'eshell)
     spell-checking syntax-checking version-control elixir javascript html ruby ruby-on-rails)
```

**Comment by kRITZCREEK** [comment]
I've got a similar issue without using layouts. The first project I open gets used as the project root for  all subsequent projects. So if I open file a in project A in `/projects/A/src/a` and then try to open file b in project B spacemacs tries to open `/projects/A/src/b`.

This means I currently have to restart spacemacs whenever I need to switch projects... :D

**Comment by deathmaz** [comment]
I have exactly the same issue as @kRITZCREEK

**Comment by artukrap** [comment]
@kRITZCREEK Yes, always when I get this situation, I do `SPC q R` which is annoying. :D

**Comment by deathmaz** [comment]
Because of this i had to switch to ivy

**Comment by artukrap** [comment]
@deathmaz You switch from helm to ivy?

**Comment by deathmaz** [comment]
Yes, i need to jump from project to project very often, and ivy doesn't has the issue, why?

**Comment by bleggett** [comment]
It's helm change that broke helm-projectile.

https://github.com/bbatsov/helm-projectile/issues/64

**Comment by deathmaz** [comment]
It seems that the bug is fixed https://github.com/bbatsov/helm-projectile/issues/64#issuecomment-275292001 , in my case everything works fine now

**Comment by artukrap** [comment]
@deathmaz Just pull the latest version of spacemacs develop, and the bug still is there. I guess spacemacs need to merge in master of helm-projectile

**Comment by deathmaz** [comment]
You need to update packages

**Comment by kRITZCREEK** [comment]
@artukrap on the home buffer hit the `Update Packages` button

**Comment by artukrap** [comment]
@deathmaz @kRITZCREEK Yes, now everything works. :+1: Closeing this issue. Fixed by: https://github.com/bbatsov/helm-projectile/issues/64#issuecomment-275292001

**Comment by svarlet** [comment]
Hi, I have this issue today. I tried with master and develop (after a git pull), I `rm -rf ~/.emacs.d/elpa` a couple of times too. It seems this issue is back. I'm not sure if I should also comment on https://github.com/bbatsov/helm-projectile/issues/64 to report this regression.
