### ISSUE TITLE
Search Highlight does not clear

### ISSUE THREAD

**Issue by LukeXuan** [syl20bnr/spacemacs#8336]
#### Description :octocat:
`SPC s c` no longer clears the highlight of search in `isearch`.

#### Reproduction guide :beetle:
- Start Emacs
- Search something.
- `SPC s c`

*Observed behaviour:* :eyes: :broken_heart:
The highlight preserves.

*Expected behaviour:* :heart: :smile:
They should be cleared.

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: nil (rev. cfcdb4d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: helm
- Layers:
```elisp
(yaml
 (auto-completion :variables auto-completion-enable-sort-by-usage t auto-completion-tab-key-behavior 'complete :disabled-for shell)
 emacs-lisp
 (latex :variables latex-build-command "LaTeX" latex-enable-auto-fill t latex-enable-folding t)
 (shell :variables shell-default-shell 'eshell shell-default-position 'bottom shell-default-height 30 shell-default-term-shell "/bin/zsh")
 (javascript :variables javascript-disable-tern-port-files nil)
 html git markdown org cscope
 (c-c   :variables c-c  -default-mode-for-headers 'c  -mode c-c  -enable-clang-support t)
 (python :variables python-enable-yapf-format-on-save t)
 better-defaults
 (spell-checking :variables spell-checking-enable-by-default nil)
 (syntax-checking :variables syntax-checking-enable-by-default t syntax-checking-enable-tooltips t)
 dash php react asm coq semantic)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by LukeXuan** [comment]
Closed. Fixed by updating packages. Seems like problem caused by evil mode.

**Comment by LukeXuan** [comment]
Seems that the key `/` is binded to the `evil-ex-search-forward` instead of `evil-search-forward`. I'm not familiar with the evil options. Seems like @syl20bnr your most recent commit introduce a invalid configuration. :(

**Comment by zzjjzzgggg** [comment]
`:noh` is also not working anymore in evil. Now I have to use 'evil-ex-nohighlight' to remove highlights after a search. Spacemacs harmed me a lot recently. Each time I hope old bugs are fixed, but only meet new bugs.

**Comment by LukeXuan** [comment]
closed as the newest develop branch fixes the bug.

**Comment by agzam** [comment]
it is still not clearing the highlighted symbol after `g d` `jump-to-definition`. 
Try it yourself: `g d` and then `SPC s c`

**Comment by gtklocker** [comment]
Also having this issue here.

**Comment by raventid** [comment]
I see this in develop and master branches. Is there any open issue about this?

**Comment by agzam** [comment]
@raventid it doesn't work for all the cases... sometimes it fails to clear. You can try for example to jump to a definition `g d` - it suppose to highlight the item. But then `SPC s c` may or may not clear the highlight. You'd have to use `:nohlsearch` ex-command. Now, one would expect this to work either way, but guess what? it doesn't. Try for example select a region and find occurrences: `SPC v` and then `#` and try clearing highlight with `:nohlsearch`. Alas, it won't work (or maybe will, you never know). It's a really annoying.

**Comment by raventid** [comment]
@agzam Well, I'm just starting to use spacemacs/emacs so I was lucky and it worked for me. I'm trying to reproduce it with `SPC v #` right now. `:nohlsearch` and `SPC s c` works fine. But I believe that it might not work for you, perhaps it's plugins fault?

**Comment by agzam** [comment]
@raventid here, out of curiosity I removed all the layers. I'm on latest develop. Started Emacs. Right there on the homepage, I moved cursor to the first occurrence of word "Spacemacs", `SPC v` to select it, `#` - to select all occurrences. Then `:hohlsearch`, and... nothing. It should clear the highlight but it didn't. `SPC s c` works. In this particular case. What I'm saying is: both these things should do the same thing. They should just work consistently. But that's not the case: sometimes one works, other doesn't. Sometimes none of them work and thing stays highlighted. Have you ever tried to work with indirect buffers? That's where things get so crazy -  you'd almost doubt your own reasoning for using Emacs.

**Comment by raventid** [comment]
@agzam I've repeated your actions and both functions worked fine for me (I'm on darwin). It would be really nice to see a new issue from you, with your operating system, emacs version and other stuff 😄

(I've never heard about indirect buffers, It's my third day in spacemacs, so I'm just starting here.)

**Comment by duianto** [comment]
There seems to be two types of search highlighting going on here:
- `C-s` search highlights can be cleared with `:noh`
- `/` search highlights can be cleared with `SPC s c`

Both can be visible at the same time in the messages buffer. They can be cleared individually.

>evil-search-module is a variable defined in ‘evil-search.el’.
Its value is ‘evil-search’
Original value was isearch

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.2
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 11356be1)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion emacs-lisp git markdown
      (org :variables org-agenda-files
           '("c:/Users/Username/Documents/"))
      version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES
