### ISSUE TITLE
org-mode fontification error with org src blocks

### ISSUE THREAD

**Issue by aaronjensen** [syl20bnr/spacemacs#8455]
#### Description :octocat:
When opening org files with src blocks, I see:

`org-mode fontification error in #<buffer spacemacs.org> at 13`

This reproduces with a base config on develop

#### Reproduction guide :beetle:
- Start Emacs
- Save a test.org file containing:

```org
#+TITLE: Spacemacs

* Debugging/reproing

#+begin_src emacs-lisp :tangle yes
(let ((default-directory  "~/.emacs.d/elpa/"))
  (normal-top-level-add-subdirs-to-load-path))
#+end_src
```
- Kill the buffer
- Find file test.org

*Observed behaviour:* :eyes: :broken_heart:
`org-mode fontification error in #<buffer spacemacs.org> at XX` appears in `*Messages*`

*Expected behaviour:* :heart: :smile:
No error

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 0c8af96)
- Graphic display: t
- Distribution: spacemacs
- Editing style: hybrid
- Completion: ivy
- Layers:
```elisp
(better-defaults spacemacs-layouts ivy
                 (markdown :variables markdown-live-preview-engine 'vmd)
                 (syntax-checking :variables syntax-checking-enable-tooltips nil)
                 (auto-completion :variables auto-completion-enable-sort-by-usage nil auto-completion-enable-snippets-in-popup nil auto-completion-private-snippets-directory
                                  (expand-file-name "snippets" dotspacemacs-directory))
                 git dash pdf-tools html clojure
                 (org :variables org-enable-github-support t org-enable-reveal-js-support t)
                 colors osx github ruby
                 (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'bottom)
                 (spell-checking :variables spell-checking-enable-by-default nil)
                 ranger version-control rcirc tmux yaml docker elm restclient typescript evil-little-word aj-deft aj-elixir aj-emacs-lisp aj-javascript auto-correct cleverparens-lispy contextual-menubar editorconfig fix-git-autorevert flow frame-geometry match-indent shift-number)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

**Comment by elandx** [comment]
i don't have this error. But i always do after installing of new org:
1) cd to org-plus-contrib-XXXXXX and remove all *.elc files
2) in running spacemacs (not emacs -Q) do `SPC SPC byte-recompile-directory` `path-to-org-plus-contrib`

**Comment by aaronjensen** [comment]
@elandx That didn't help... I deleted the elc and when I `byte-recompile-directory` on that dir, it says 0 compiled  187 skipped. I still get the fontification error.

**Comment by elandx** [comment]
@aaronjensen `0 compiled` means that compilation failed, probably You don't point to the directory correctly.  And another possible reason can be extra org-XXXXX directory (not org-plus-contrib). If so You can delete it safely.

**Comment by aaronjensen** [comment]
@elandx no extra org dir. 

I see this in messages:

```
Checking /Users/aaronjensen/.emacs.d/elpa/25.2/org-plus-contrib-20170210/... [188 times]
Checking /Users/aaronjensen/.emacs.d/elpa/25.2/org-plus-contrib-20170210/etc...
Checking /Users/aaronjensen/.emacs.d/elpa/25.2/org-plus-contrib-20170210/etc/styles...
Done (Total of 0 files compiled, 187 skipped)
```

If I delete the org-plus-contrib dir it gets reinstalled and elc files appear. I still see the fontification error, however.

**Comment by aaronjensen** [comment]
Read the docs, need prefix 0, `C-0 SPC SPC byte-recompile-directory`. I was able to recompile, but I still get the fontification error.

**Comment by elandx** [comment]
@aaronjensen 
Sorry, mea culpa, you are right i forgot about the prefix 0. Last thought: are you *close* Spacemacs after recompilation? I am on develop too and have fontification OK.

**Comment by aaronjensen** [comment]
Yep, even after a restart, no luck.

**Comment by aaronjensen** [comment]
Here's the stacktrace for the error that occurs:

```
Debugger entered--Lisp error: (args-out-of-range 86 127)
  put-text-property(86 127 ws-butler-chg chg)
  ws-butler-after-change(86 127 41)
  put-text-property(86 127 face nil #<buffer test.org>)
  org-src-font-lock-fontify-block("emacs-lisp" 35 130)
  org-fontify-meta-lines-and-blocks-1(140)
  org-fontify-meta-lines-and-blocks(140)
  font-lock-fontify-keywords-region(1 140 nil)
  font-lock-default-fontify-region(1 140 nil)
  font-lock-fontify-region(1 140 nil)
  font-lock-default-fontify-buffer()
  font-lock-fontify-buffer()
  org-bullets-mode()
  run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
  run-mode-hooks(org-mode-hook)
  org-mode()
  set-auto-mode-0(org-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer test.org> "~/Dropbox (Personal)/Notes/test.org" nil nil "~/Dropbox (Personal)/Notes/test.org" (213415716 16777220))
  find-file-noselect("/Users/aaronjensen/Dropbox (Personal)/Notes/test.org" nil nil nil)
  find-file("/Users/aaronjensen/Dropbox (Personal)/Notes/test.org")
  ivy--switch-buffer-action(#("test.org" 0 8 (face ivy-virtual)))
  ivy-call()
  ivy-read("Switch to buffer: " internal-complete-buffer :matcher ivy--switch-buffer-matcher :preselect "*scratch*" :action ivy--switch-buffer-action :keymap (keymap) :caller ivy-switch-buffer)
  ivy-switch-buffer()
  funcall-interactively(ivy-switch-buffer)
  call-interactively(ivy-switch-buffer nil nil)
  command-execute(ivy-switch-buffer)
```

**Comment by elandx** [comment]
@aaronjensen in your example seems that code block is misspelled
Should be `#+`, not just `# `

**Comment by aaronjensen** [comment]
@elandx thanks, that's what they actually were in the real file, not sure where they got stripped.

**Comment by aaronjensen** [comment]
If I exclude the `org-bullets` the problem goes away.

**Comment by aaronjensen** [comment]
Possibly related: https://github.com/sabof/org-bullets/issues/18

**Comment by laduke** [comment]
@aaronjensen  is it still working for you? It works for me once, but if I restart emacs, `fontification error` comes back, even with org-bullets disabled. 

I'm trying a fresh .spacemacs 
```
   dotspacemacs-configuration-layers
   '(
     ivy
     emacs-lisp
     org 
)
```

I if delete all the org-* stuff from ./elpa, it works the first time I start emacs, but never again.

**Comment by aaronjensen** [comment]
@laduke I can't get it to work... it doesn't seem to actually be related to org-bullets. I'm glad that someone else is getting the error as well. It's not clear that it actually effects anything--babel blocks still have syntax highlighting. I don't really know what the error is telling me 😕

**Comment by laduke** [comment]
Oh my fontification isn't working either. 
I saw on the org mailing list to try `(setq org-src-fontify-natively nil)` which turns off the error (and highlighting!) 

http://lists.gnu.org/archive/html/emacs-orgmode/2017-02/msg00280.html

**Comment by elandx** [comment]
I can't provide any valuable information on the topic besides that now, after my experiments with org-bullets, i have the error message too.  But i think too that it is completely unrelated with org-bullets per se.  Seems that error is harmless.

**Comment by edwinhu** [comment]
Could be related to #8448. The suggested work-around solved my problem.

Also, I tried to replicate the bug using @aaronjensen test.org, and was unable to replicate. I also tried turning off `org-bullets` but that didn't work.

**Comment by aaronjensen** [comment]
@edwinhu I don't have the `ess` enabled, so that work around won't help me, unfortunately. I don't know why you can't repro, but elandx could not repro either until after some experimenting, so it could be a specific package version issue.

**Comment by dangom** [comment]
Same issue here.

**Comment by voobscout** [comment]
same issue, none of the workarounds help.

**Comment by braham-snyder** [comment]
also seeing this on OS X, no `ess` either--first noticed it within the last month or two, not sure exactly when it first appeared

I haven't looked into it much since it seems relatively benign, but it's not related to the conflicting `org-mode` packages, right? i.e., as mentioned [in Spacemacs' docs](http://spacemacs.org/layers/+emacs/org/README.html#important-note):

> Since version 0.104, spacemacs uses the org version from the org ELPA repository instead of the one shipped with emacs. Then, any org related code should not be loaded before dotspacemacs/user-config, otherwise both versions will be loaded and will conflict.

**Comment by aaronjensen** [comment]
This is the commit in org where it started:

```
f2a5104e45b6f44a08960ae49ba20c124a8fa9d8 is the first bad commit
commit f2a5104e45b6f44a08960ae49ba20c124a8fa9d8
Author: Noam Postavsky <npostavs@gmail.com>
Date:   Sat Jan 7 16:05:19 2017 -0500

    Backport commit ae8264c5cc from Emacs

    * lisp/org-src.el (org-src-font-lock-fontify-block): Let-bind
    `inhibit-modification-hooks' to nil, since this function can be called
    from jit-lock-function which binds that variable to t (Bug#25132).

    Call modification hooks in org-src fontify buffers
    ae8264c5cccf19d5b25a340a605bf2f07de1577e
    Noam Postavsky
    Sun Jan 29 11:01:32 2017 -0500
```

**Comment by aaronjensen** [comment]
Fixed upstream: http://lists.gnu.org/archive/html/emacs-orgmode/2017-03/msg00423.html

**Comment by voobscout** [comment]
it didn't fix it for me. same behaviour, but no error message.... sad

**Comment by aaronjensen** [comment]
@voobscout there was no issue for me, just the error message. What is the issue you're seeing?

**Comment by voobscout** [comment]
No fontification in org-mode babel, neither does it recognize different modes, here's a screenie:
![22 03 2017_03 25 48](https://cloud.githubusercontent.com/assets/1203212/24179436/5de2c3be-0eaf-11e7-8ed9-63a0a5f272bf.png)

I know it worked before, with some version of org or other....

**Comment by aaronjensen** [comment]
Your elisp is working, so fontification *is* working, just not w/ those particular modes. Could you open another issue w/ repro steps? This one is resolved.

**Comment by mandarvaze** [comment]
@aaronjensen If this is fixed upstream, how do I get the fix ?

I'm relatively noob.

How do I check the version of org-mode ?

How do I get the updated version of org-mode ? (I'm using spacemacs)

**Comment by aaronjensen** [comment]
@mandarvaze `SPC b h` to get to the home buffer. Then tab over to or click "Update packages" hit `y` when prompted and restart emacs. You'll probably want to restart emacs one more time after the new packages install so that the new version of org will load.

**Comment by aaronjensen** [comment]
Closing since this is fixed upstream
