### ISSUE TITLE
In common lisp layer, slime not auto complete symbol or parentheses stuff

### ISSUE THREAD

**Issue by sledon** [syl20bnr/spacemacs#8796]
i am new to common lisp , and add common-lisp layer in dontspacemacs file.
after use M-x slime start slime buff. not auto complete occur after i typed an (.
i found things done when major mode is lis( in slime buff , i type M-x common-lisp-mode)

then, i tryed to add (add-hook 'slime-mode-hook 'common-lisp-mode) in config file. 
not work.

i am not sure this was a bug or my config was wrong. 

here was info:
System Info :computer:

Windoes7
Emacs: 25.1.1
Spacemacs: 0.200.9
Spacemacs branch: master (rev. 8e1af14)
Graphic display: t
Distribution: spacemacs
Editing style: emacs
Completion: helm
Layers:
   '(
   
     helm
     common-lisp
     auto-completion
     emacs-lisp
     git
     org
  
     )

**Comment by LdBeth** [comment]
I get the same problem in develop branch (rev: 177da959). I think this is a bug of the packages rather than spacemacs because it can get to work before.

**Comment by LdBeth** [comment]
A fix slime-company PR is proposed, but I think parentheses won't be auto completed in slime buffer.

**Comment by syl20bnr** [comment]
Should be fixed in develop, please verify.

**Comment by sledon** [comment]
today, i update my develop branch and common-lisp layer to latest. but still occurs of the problem.

**Comment by sledon** [comment]
i've verify. it's ok. thanks.
