### ISSUE TITLE
error: (wrong-type-argument package-desc nil)

### ISSUE THREAD

**Issue by michaelkjin** [syl20bnr/spacemacs#8901]
I am receiving this error message on start up.

--> installing package: evil-unimpaired@spacemacs-evil... [1/1]
An error occurred while installing evil-unimpaired (error: (wrong-type-argument package-desc nil))

I have tried:
-deleting .cache
-deleting archive

Fix: (as described by @marienz below)
change the file 
`evil-unimpaired-20170528.01741.el` to `evil-unimpaired-20170528.1741.el`
notice the `0` is taken out of  `.01741.el`

**Comment by marienz** [comment]
I ran into this one, and blowing away `~/.emacs.d/.cache/quelpa` a day later fixed it.

I suspect something goes awry when updating a package with `:location (recipe :fetcher local))` between midnight and 1AM. Was that roughly when you updated, and when you deleted .cache? Deleting .cache/quelpa again at some other time of day to help (it did here).

On my system, it was failing to load `evil-unimpaired-20170528.1741.el`, while the file that existed was `evil-unimpaired-20170528.01741.el` (and that version was also in `evil-unimpaired.stamp`).

Those look like timestamps with one or more leading zeroes stripped from the time. There's this code in `quelpa-check-hash`:

```
         (time-stamp
          (replace-regexp-in-string "\\.0" "." (format-time-string "%Y%m%d.%H%M%S")))
```

which strips one leading zero. It looks like some other code I did not track down gets confused if there's still a leading zero left (treating the timestamp as a version number?), which happens when the hour is 00.

I suspect changing that regexp to "\\.0+" will fix it (by consistently removing all leading zeroes).

**Comment by marienz** [comment]
Looks like the suspicious regexp was introduced in https://github.com/quelpa/quelpa/commit/6e127408cc82693155642c6791bc5ee59ce7c8f1 and still exists there.

I don't know how to use quelpa, so I don't know how to confirm it's a problem there (and not just producing quirky version numbers that should work...).

**Comment by x-ji** [comment]
@marienz Thanks for digging up the cause of the bug! Maybe something will need to be fixed on quelpa, or some configuration in Spacemacs is wrong?

**Comment by BanditsKZ** [comment]
In my computer , if it boot up with the termial, it won't show this error message .

**Comment by aphistic** [comment]
Just wanted to add my input to this to confirm it looks like what @marienz mentioned is the problem.

I'm having a problem installing right now (at 00:48). When I start up with --debug-init it shows the following error:

`(file-error "Opening input file" "No such file or directory" "/home/aphistic/.emacs.d/.cache/quelpa/packages/evil-unimpaired-0.1pre0.20170804.4829.el")`

If I look in that directory I have a file named `evil-unimpaired-0.1pre0.20170804.04829.el`, so it does look like it's an issue with the way the 0's are being processed.

Once I renamed the file to `evil-unimpaired-0.1pre0.20170804.4829.el` the install completed successfully.

**Comment by quicknir** [comment]
@marienz Did you bring this to the attention of the quelpa people?

**Comment by marienz** [comment]
I don't know how to use quelpa directly, so I couldn't confirm it's a problem there.

However, someone else helpfully did, and got it fixed. See https://github.com/quelpa/quelpa/issues/132.

So the next time Spacemacs syncs its copy of quelpa,el, this should get fixed.

**Comment by duianto** [comment]
Spacemacs has updated quelpa, so this issue should be fixed now.
https://github.com/syl20bnr/spacemacs/commit/fe6441316bc0a4a6b0be3c52d8fc08f6f42f3909#diff-e6248c0ac439806ae6fae6769afe329dR355

**Comment by fleimgruber** [comment]
This still happens for me on latest develop. Tried removing `.cache` to no avail.

**Comment by mjin955** [comment]
@fleimgruber 
you want to do this:
rename ```evil-unimpaired-20170528.01741.el``` to ```evil-unimpaired-20170528.1741.el```

**Comment by x-ji** [comment]
@fleimgruber You shall probably try to update packages or if everything fails nuke the `elpa` folder in `.emacs.d` and let Spacemacs install all packages again.

**Comment by fleimgruber** [comment]
@mjin955 it is `evil-unimpaired-20180513.235423` already.

**Comment by mjin955** [comment]
@fleimgruber 
have you tried going into your .emacs.d/init.el and delete the line that requires 'lsp-javascript-typescript?

**Comment by fleimgruber** [comment]
There is no lsp-javascript-typescript in there. It gets pulled in by the javascript layer

**Comment by mjin955** [comment]
@fleimgruber 
Pretty sure that's a package. You think you should be able to turn off any packages, This one looks like your package?
https://github.com/emacs-lsp/lsp-javascript

So in your .emacs.d grep for the files for this:
`(require 'lsp-javascript-typescript)`
and possibly this
`(add-hook 'js-mode-hook #'lsp-javascript-typescript-enable)`
if you find them then delete those two lines from the file.

**Comment by fleimgruber** [comment]
While that would probably work for the lsp-javascript-typescript package, it is not the right fix IMHO. E.g. another package I want to install is:

`(sunrise-commander :location (recipe :fetcher github :repo "escherdragon/sunrise-commander"))`

which fails with the same error

`An error occurred while installing sunrise-commander (error: (wrong-type-argument package-desc nil))`

because that one uses quelpa as well and I still suspect the problem lies with quelpa.

**Comment by fleimgruber** [comment]
Ok, actually I should have been even more explicit, the full traceback reads

```
(Spacemacs) --> installing package: sunrise-commander@user... [2/2]
Fetcher: github
Source: escherdragon/sunrise-commander

Updating c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/
c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/sunrise-commander.el -> c:/Users/USER~1/AppData/Local/Temp/sunrise-commanderlcE7AU/sunrise-commander-20171217.2009/sunrise-commander.el
c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/sunrise-x-buttons.el -> c:/Users/USER~1/AppData/Local/Temp/sunrise-commanderlcE7AU/sunrise-commander-20171217.2009/sunrise-x-buttons.el
c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/sunrise-x-checkpoints.el -> c:/Users/USER~1/AppData/Local/Temp/sunrise-commanderlcE7AU/sunrise-commander-20171217.2009/sunrise-x-checkpoints.el
c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/sunrise-x-loop.el -> c:/Users/USER~1/AppData/Local/Temp/sunrise-commanderlcE7AU/sunrise-commander-20171217.2009/sunrise-x-loop.el
c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/sunrise-x-mirror.el -> c:/Users/USER~1/AppData/Local/Temp/sunrise-commanderlcE7AU/sunrise-commander-20171217.2009/sunrise-x-mirror.el
c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/sunrise-x-modeline.el -> c:/Users/USER~1/AppData/Local/Temp/sunrise-commanderlcE7AU/sunrise-commander-20171217.2009/sunrise-x-modeline.el
c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/sunrise-x-old-checkpoints.el -> c:/Users/USER~1/AppData/Local/Temp/sunrise-commanderlcE7AU/sunrise-commander-20171217.2009/sunrise-x-old-checkpoints.el
c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/sunrise-x-popviewer.el -> c:/Users/USER~1/AppData/Local/Temp/sunrise-commanderlcE7AU/sunrise-commander-20171217.2009/sunrise-x-popviewer.el
c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/sunrise-x-tabs.el -> c:/Users/USER~1/AppData/Local/Temp/sunrise-commanderlcE7AU/sunrise-commander-20171217.2009/sunrise-x-tabs.el
c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/sunrise-x-tree.el -> c:/Users/USER~1/AppData/Local/Temp/sunrise-commanderlcE7AU/sunrise-commander-20171217.2009/sunrise-x-tree.el
c:/Users/user/.emacs.d/.cache/quelpa/build/sunrise-commander/sunrise-x-w32-addons.el -> c:/Users/USER~1/AppData/Local/Temp/sunrise-commanderlcE7AU/sunrise-commander-20171217.2009/sunrise-x-w32-addons.el
Wrote c:/Users/user/.emacs.d/.cache/quelpa/packages/sunrise-commander-readme.txt
Error getting PACKAGE-DESC: (file-missing Opening input file No such file or directory c:/Users/user/.emacs.d/.cache/quelpa/packages/sunrise-commander-20171217.2009.tar)
(Spacemacs) Error: 
An error occurred while installing sunrise-commander (error: (wrong-type-argument package-desc nil))
```

so it seems nothing gets put to `c:/Users/user/.emacs.d/.cache/quelpa/packages`. Any Windows users around?

**Comment by fleimgruber** [comment]
Just for completeness, there was a stray BSD tar creeping around in my PATH, fixed it via specifying the MinGW tar
```
(setq-default quelpa-build-tar-executable "C:/Users/user/opt/msys64/usr/bin/tar.exe")
```
sorry for all the noise.

**Comment by oxyum** [comment]
MacOS

Install GNU tar via Homebrew:
```
$ brew install gnu-tar
```

Activate it via user-init:
```elisp
(setq-default quelpa-build-tar-executable "/usr/local/bin/gtar")
```

**Comment by Skaneel** [comment]
> Just for completeness, there was a stray BSD tar creeping around in my PATH, fixed it via specifying the MinGW tar
> 
> ```
> (setq-default quelpa-build-tar-executable "C:/Users/user/opt/msys64/usr/bin/tar.exe")
> ```
> 
> sorry for all the noise.

Error getting PACKAGE-DESC: (file-missing Opening input file No such file or directory d:/programs/emacs/.emacs.d/.cache/quelpa/packages/php-extras-20160518.1816.tar)

what does it all mean?  (setq-default quelpa-build-tar-executable "C:/Users/user/opt/msys64/usr/bin/tar.exe") I have this problem. I'm new to what things to put in to solve this. thanks in advance

**Comment by michaelkjin** [comment]
@Skaneel the comment you quoted is setting which tar binary to use. I think the more important question here is, what problem are you facing. Are you getting the exact same error message?

**Comment by Skaneel** [comment]
> @Skaneel the comment you quoted is setting which tar binary to use. I think the more important question here is, what problem are you facing. Are you getting the exact same error message?

I am getting this error. 
An error occurred while installing php-extras (error: (wrong-type-argument package-desc nil))
Error getting PACKAGE-DESC: (file-missing Opening input file No such file or directory d:/programs/emacs/.emacs.d/.cache/quelpa/packages/php-extras-20160518.1816.tar)

What should I do? I started to learn Emacs and now I need to solve this error. I will be glad for any help

**Comment by duianto** [comment]
@Skaneel There's a separate issue related to the `php-extras` bug here:
[BUG] php layer error while installing php-extras #10566

I just tested suggestion by zendo: https://github.com/syl20bnr/spacemacs/issues/10566#issuecomment-451968501
and it worked, there's more info in my comment below that one.

**Comment by aneeshsathe** [comment]
hello, I was trying out the suggestion from @duianto i.e. adding 
`(setq-default quelpa-build-tar-executable "C:/Users/user/opt/msys64/usr/bin/tar.exe")`
to user-init
however i get a malformed arglist error for my code in the image below. 

I'm brand new to the emacs and spacemacs world, so not entirely sure of what I'm doing

![image](https://user-images.githubusercontent.com/9650672/74958003-49727000-5443-11ea-92dc-69e256325e21.png)

i'm trying to get the org-roam package installed and the tar file seems to be missing
ref: https://github.com/jethrokuan/org-roam/pull/133#issuecomment-588996927

**Comment by duianto** [comment]
The parentheses where you added the setq-default line, should be left empty. They used for any parameters that a function expects to receive (more info below).

Move down the line:
```elisp
(setq-default quelpa-build-tar-executable "C:/Users/user/opt/msys64/usr/bin/tar.exe")
```
before the `dotspacemacs/user-init` functions close parenthesis, it's on it's own line after the docstring that starts with: `"Initialization functions for user code.`

Resulting in the following:
```
(defun dotspacemacs/user-init ()
"Initialization functions for user code.
...
`dotspacemacs/user-config' first."
  (setq-default quelpa-build-tar-executable "C:/Users/user/opt/msys64/usr/bin/tar.exe")
  )

(defun dotspacemacs/user-config ()
  "Configuration functions for user code.
```

#### Continued from above
Here's an example of how the parentheses after a function name can be used.

If we want to define a function that adds 5 to a number, then we would write:
```elisp
(defun add5 (nr)
  (+ nr 5))
```
`nr` in the parentheses will contain the value we provide when the function is called.

The function can be called like this:
```elisp
(add5 2)
```
When both the function and the call to it are evaluated, then `(add5 2)` will return: 7

You can try it yourself by:
- Opening a new buffer by pressing: `SPC b N` 
It will open a buffer with the name `untitled`
Or you can press: `C-x C-f` (which means hold down `ctrl` and press `x` then `f`, a prompt appears asking for `Find files or url:`
- Type: `test` and press `Enter`
Don't worry about the path, the file isn't saved until you try to save it with: `SPC f s` or `C-x C-s`, you can close the buffer `SPC b d` or `C-x k` when your done and nothing will be saved.
- Paste or type the function definition for the add5 function.
```elisp
(defun add5 (nr)
  (+ nr 5))
```
- Evaluate the function to make Spacemacs recognize it as a function, by moving the cursor to the last close parenthesis on the line `(+ nr 5))` and press: `C-x C-e`, the function name `add5` is shown in the minibuffer at the bottom of the Spacemacs window.
- Now type: `(add5 2)` and move the cursor to it's close parenthesis and evaluate it with: `C-x C-e`

The minibuffer shows: `7 (#o7, #x7, ?\C-g)`
The first number is the result.
The numbers in the parentheses are the octa decimal, hexa decimal and (possibly) the ascii character representations of number: 7

**Comment by aneeshsathe** [comment]
@duianto thanks a ton for the detailed explanation and the mini-tutorial on the syntax :)

I've fixed the code and ran a few different combinations (clearing cache, fresth install of spacemacs etc) to get quelpa to work.

Unfortunately, quelpa in spacemacs seems to still not be able to generate tar files. Is there any way to test if quelpa can access tar.exe?

**Comment by duianto** [comment]
You can check if Emacs is able to find `tar`:
- Open the `Eval:` prompt by pressing: `S-M-;` (that's `Shift + Alt + ;`)
- Then type or copy and paste (`C-y`) the following:
```elisp
(executable-find "tar")
``` 

When you see `M-` in key bindings, then it stands for Meta. It was a key on the keyboards when Emacs was created. But now it means the `Alt` key.

**Comment by aneeshsathe** [comment]
I had tried that. On trying again now, I get the same result:
`"c:/WINDOWS/system32/tar.exe" `

Not sure if quelpa would use the same version of tar with the above setting.

**Comment by duianto** [comment]
Your right, when setting the `quelpa-build-tar-executable` path to a tar executable, then it won't use the version that Emacs sees with executable-find.

Have you tried with the path to the Git tar that's in your screenshot:
`(setq-default quelpa-build-tar-executable "C:/Program Files/Git/usr/bin/tar")`

That one fixed this issue for me:
[BUG] php layer error while installing php-extras #10566

It also fixed a similar issue in the `mercury` layer, where the `metal-mercury-mode` package wouldn't install.
