### ISSUE TITLE
C-d in shell-mode + evil-normal-state should do evil-scroll-down

### ISSUE THREAD

**Issue by kini** [syl20bnr/spacemacs#914]
As title. comint-mode has something called `comint-delchar-or-maybe-eof`, which is bound to `C-d` in shell-mode (and probably other modes based on comint-mode).

The idea is that `C-d` usually signifies the EOF character when typing in a shell, so comint detects whether point is at the input prompt in the buffer. If so, then `C-d` should send an EOF character.

Unfortunately, it is implemented in such a way that if you are not at the input prompt, then it is hard-coded to fall back to `delete-char`, which is the function that is bound to `C-d` by default in Emacs. Instead, it should fall back to whatever `C-d` was bound to by the user's settings. In this case, that would mean `evil-scroll-down`.

It seems like this is probably a comint-mode bug rather than a spacemacs bug, but it would be nice to at least have a workaround in spacemacs of some kind since comint-mode is part of the main Emacs distribution and probably won't change fast.

**Comment by razzmatazz** [comment]
I use a simple workaround for this:
```
(add-hook 'comint-mode-hook
  	  (function (lambda ()
  		      (local-set-key (kbd "C-d") 'evil-scroll-down))))
```

which probably breaks something, but so far-so-good. I use C-c C-d for the '^D' functionality

**Comment by kini** [comment]
Thanks, I guess I'll try this:

```elisp
  (defun comint-esd-or-maybe-eof (arg)
    "Like `comint-delchar-or-maybe-eof' except not terrible.  Or
maybe terrible, but in a different way."
    (interactive "p")
    (let ((proc (get-buffer-process (current-buffer))))
      (if (and (eobp)
               proc
               (= (point)
                  (marker-position (process-mark proc))))
          (comint-send-eof)
        (evil-scroll-down arg))))

  (add-hook 'comint-mode-hook
            (function (lambda ()
                        (local-set-key (kbd "C-d") 'comint-esd-or-maybe-eof))))
```

That function is just a modification of `comint-delchar-or-maybe-eof`. Maybe it would be better to bind it in normal state in particular, instead of just across the board...

**Comment by kini** [comment]
I found a better solution:

```elisp
(with-eval-after-load 'comint
    (define-key comint-mode-map "\C-d" nil))
```

This actually gives you back all the different bindings for `C-b` in all the different evil states. I think this should be default in spacemacs.

**Comment by syl20bnr** [comment]
This is fixed in `develop`.

**Comment by kini** [comment]
Just out of curiosity, how did you fix this? I don't find any reference to comint mode or C-d in the recent commit messages or commit diffs...

**Comment by abernardes** [comment]
Hey I'm sorry but I just pulled the lastest `develop` and I'm still seeing this issue when running tests in Ruby.

**Comment by abernardes** [comment]
I think it's worth mentioning that @kini's solution did the trick for me. But it would be nice if this was the default Spacemacs behaviour.

**Comment by syl20bnr** [comment]
I reopen it since it seems that it has not been fixed.

**Comment by kini** [comment]
Since it seemed like this was originally closed without any particular commit being responsible, maybe it was "fixed" because some package's new version happened to contain a fix for this. @abernardes, if you upgrade all your ELPA packages do you still see this? (i.e. click `[Update]` in the spacemacs startup buffer)

**Comment by abernardes** [comment]
Updated the packages, still having the same issue.

I wish I wasn't such a n00b so I could provide a fix for this :(

**Comment by kini** [comment]
I think taking the blurb I posted earlier and dumping it into `spacemacs/config.el` should solve this. I made #2107 just now fwiw.

**Comment by abernardes** [comment]
:+1:
