### ISSUE TITLE
Use Emacs 26's native line numbers

### ISSUE THREAD

**Issue by barischrooneyj** [syl20bnr/spacemacs#9362]
When `dotspacemacs-line-numbers` is true then if available use Emacs 26's `display-line-numbers-mode` instead of `linum-mode`.

According to [emacs/NEWS](https://github.com/emacs-mirror/emacs/blob/ff49d86b6419f88205ff9a5d8b1cc46fcda8371c/etc/NEWS#L493) it is "much faster and doesn't usurp the display margin for the line numbers."

**Comment by CeleritasCelery** [comment]
we can use that feature when Emacs 26 is released. Good to note however.

**Comment by bmag** [comment]
Actually, if the feature is stable (not too buggy, work on API is finished) then we can add support for it, as long as there aren't any problems for users of currently supported versions. I think this feature will be a high priority once Emacs 26 is released, anyway.

**Comment by LdBeth** [comment]
Emacs 26 pretest is out and we can start working on that.

**Comment by jsoo1** [comment]
What's the status on this?  I had a private branch with some work done but I didn't really know what I was doing or the best way to do it.

**Comment by bmag** [comment]
@jsoo1 AFAIK no one has been working on it. I'm not familiar with native line numbers API yet, so I can't tell you what the best way to configure it.

As for supporting both old and new Emacs versions simultaneously, a good way to do it is for both linum and native-line-numbers to be listed in the packages list (of `spacemacs-base/packages.el`) with a toggle that depends on the Emacs version. There are also some global bindings in `spacemacs-base/keybindings.el` (for code selection by mouse-clicking the line number) that might have a connection with linum. If they really depend on linum, then they will need to become conditional as well (and preferably something equivalent can be written for native-line-numbers).

**Comment by sdwolf** [comment]
Just to let people know, I'm interested in this feature and I might take a swing at it over the winter holidays, but I would like emacs 26 to actually be released first.

**Comment by bmag** [comment]
Just for general information, the first pretest for Emacs 26 was released ~2 months ago, so there's still some time to go before the final release. Usually there are a few pretest releases, followed by a few release candidates, and only then Emacs 26 will be officially released. Judging by past releases, this could take more than a few months.

I'd expect the API for native-line-numbers to  be stable by the 1st RC, possibly even before.

**Comment by kommen** [comment]
`linum-relative`, which comes with Spacemacs, has already added support for, `display-line-numbers-modes` as a backend: https://github.com/coldnew/linum-relative/commit/9fd6c7a75d5d5d0f4e4ceb42c8b9d5c769d30372

Permalink to the news section for Emacs 26 announcing `display-line-numbers-mode` as the link in the original issue comment is broken: https://github.com/emacs-mirror/emacs/blob/d42bd3a512dadd853d7fb828072a531d7f1d78b6/etc/NEWS.26#L492-L515

**Comment by azzamsa** [comment]
@barischrooneyj I think the link for your citation is [here](https://github.com/emacs-mirror/emacs/blob/ff49d86b6419f88205ff9a5d8b1cc46fcda8371c/etc/NEWS#L493) :)

> Emacs now supports optional display of line numbers in the buffer.
This is similar to what 'linum-mode' provides, but much faster and
doesn't usurp the display margin for the line numbers

**Comment by syvanpera** [comment]
Has there been any new development on this? I just recently switched to spacemacs and I had a hell of a time trying to get relative line numbering and git-gutter working. Then I switched to using the native line numbering and everything works like a charm and it feels a bit snappier to boot.

**Comment by syvanpera** [comment]
At least for me, yes. Couldn't get the line numbers working properly with git-gutter. So far they've been working really well. Only difference to the old way is that the git-gutter markers are on the left side of the line numbers. I think they were the other way around in the old implementation, but at least for me, that's not an issue

**Comment by jsoo1** [comment]
Native line numbers are definitely a game changer. I think anyone who has more experience than I writing layers should start working on one.

**Comment by syvanpera** [comment]
I suppose writing a layer for it would be the simplest solution. But I feel this is really something that should be added to the core. If not to replace linum-mode (if spacemacs needs to support older Emacs than 26), then at least as an option by its side

**Comment by bmag** [comment]
I added support for native line numbers in https://github.com/syl20bnr/spacemacs/pull/10675, but it might have some rough edges still. Could some of you please test the PR in normal usage and report any problems it has? If you run Emacs 26, the PR doesn't require any changes to your user configuration, it should use native line numbers automatically (unless you enabled `nlinum` layer, in this case you need to disable it).

Also, I'm not sure what the best behavior for `SPC t n` and `SPC t r` toggles, so if anyone has feedback or preferences, please share it on the PR page. The PR page has more details about the toggles situation.

**Comment by bmag** [comment]
Develop branch now supports native line numbers for Emacs 26, which was released today. Details at https://github.com/syl20bnr/spacemacs/commit/8f82486154f828d3b805c5c349e41b82c801d2c8. For nlinum users, be aware that we are planning to deprecate the layer for Emacs 26 so it does not override the native line numbers.

**Comment by brandonwillard** [comment]
Are the modes set in `:enabled-for-modes` supposed to be exclusive (i.e. only line numbering for modes specified there and also not present in `:disabled-for-modes`)?  The documentation `dotspacemacs-line-numbers` seems to imply that, but that's not how [spacemacs//linum-enabled-for-current-major-mode](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bspacemacs/spacemacs-defaults/funcs.el#L1233) appears to work.

**Comment by bmag** [comment]
@brandonwillard Yes, they are supposed to be exclusive. There's a bug in the function. The following patch should fix it, can you confirm?

```diff
1 file changed, 6 insertions(+), 4 deletions(-)
layers/+spacemacs/spacemacs-defaults/funcs.el | 10 ++++++----

modified   layers/+spacemacs/spacemacs-defaults/funcs.el
@@ -1235,9 +1235,9 @@ Decision is based on `dotspacemacs-line-numbers'."
   ;; default `enabled-for-modes' to '(prog-mode text-mode), because it is a more
   ;; sensible default than enabling in all buffers - including Magit buffers,
   ;; terminal buffers, etc.
-  (let* ((enabled-for-modes (or (spacemacs/mplist-get dotspacemacs-line-numbers
-                                                      :enabled-for-modes)
-                                '(prog-mode text-mode)))
+  (let* ((user-enabled-for-modes (spacemacs/mplist-get dotspacemacs-line-numbers
+                                                       :enabled-for-modes))
+         (enabled-for-modes (or user-enabled-for-modes '(prog-mode text-mode)))
          (disabled-for-modes (spacemacs/mplist-get dotspacemacs-line-numbers
                                                    :disabled-for-modes))
          (enabled-for-parent (or (and (eq enabled-for-modes 'all) 'all)
@@ -1255,4 +1255,6 @@ Decision is based on `dotspacemacs-line-numbers'."
           ;; from disabled-for-parent)
           (not (spacemacs/derived-mode-p enabled-for-parent disabled-for-parent)))
      ;; current mode (or parent) not explicitly disabled
-     (not disabled-for-parent))))
+     (and (null user-enabled-for-modes)
+          disabled-for-modes
+          (not disabled-for-parent)))))
```

**Comment by brandonwillard** [comment]
Should the following pass?
```elisp
(ert-deftest spacemacs//linum-enabled-for-current-major-mode--disabled-and-enabled ()
  (let ((dotspacemacs-line-numbers '(:enabled-for-modes emacs-lisp-mode
                                     :disabled-for-modes prog-mode)))
    (let ((major-mode 'emacs-lisp-mode))
      (should (equal t (spacemacs//linum-enabled-for-current-major-mode))))))

(ert-deftest spacemacs//linum-enabled-for-current-major-mode--disabled-for-only ()
  (let ((dotspacemacs-line-numbers '(:disabled-for-modes prog-mode)))
    (let ((major-mode 'term-mode))
      (should (equal nil (spacemacs//linum-enabled-for-current-major-mode))))))
```

Regardless, the patch appears to fix the original problem.

**Comment by bmag** [comment]
The first should pass, the second should fail, and the test call should be just:
```elisp
(should (spacemacs//linum-enabled-for-current-major-mode))
```

I'm writing relevant tests right now.

**Comment by bmag** [comment]
Sorry, the second should also pass, I missed that it's a `nil` there and not a `t`.

**Comment by bmag** [comment]
`spacemacs//linum-enabled-for-current-major-mode` should be fixed now

**Comment by sdwolfz** [comment]
@bmag Line numbers work well for me :+1: .

The only inconvenience I have right now is that the line number "sidebar" is way to wide by default and I need to do:
```emacs-lisp
(setq-default display-line-numbers-width nil)
```
in my `dotspacemacs/user-config` to get it back to normal.

I would preffer if we did not configure the width in the package init:
```diff
diff --git a/layers/+spacemacs/spacemacs-defaults/packages.el b/layers/+spacemacs/spacemacs-defaults/packages.el
index 0aad40b76..9e03522c7 100644
--- a/layers/+spacemacs/spacemacs-defaults/packages.el
+++ b/layers/+spacemacs/spacemacs-defaults/packages.el
@@ -186,7 +186,6 @@
     :defer t
     :init
     (progn
-      (setq-default display-line-numbers-width 4)
       (if (spacemacs/relative-line-numbers-p)
           (setq display-line-numbers-type 'relative)
         (setq display-line-numbers-type t))
```

**Comment by bmag** [comment]
@sdwolfz I changed it to match the setting for `linum-format`, but you're right it's a bit too big.

**Comment by sdwolfz** [comment]
@bmag :+1: I've pushed the patch above to develop.

**Comment by mmcnl** [comment]
@bmag @sdwolfz Thanks for your work on this! Is there any way to add some padding to the right of the numbers?  With `linum-mode` I was doing something like this `linum-relative-format "%2s "` to get some visual space between the numbers and the beginning of the code.

**Comment by darkbaby123** [comment]
@mmcnl I also set the line number with left/right margin. With new native line number I can solve left margin with `display-line-numbers-width` , but seems right margin is not supported?

**Comment by mmcnl** [comment]
Does anyone (e.g. @bmag or others) know how to increase the space to the *right* of the line numbers?

**Comment by bmag** [comment]
@mmcnl I couldn't find a way to increase the margin to the right of the line numbers: no variable, function or customize option that lets you change it. I also searched for a way to swap places between regular margin and line number margin and didn't find anything.

AFAICT it is a limitation of the line numbers implementation in Emacs 26, so I suggest opening an issue upstream at Emacs. (`M-x report-emacs-bug`)

**Comment by mmcnl** [comment]
@bmag Thanks so much for the research, much appreciated!

**Comment by Isimoro** [comment]
Adding `text-mode` or `prog-mode` to `:disabled-for-modes` does nothing on my system. For other modes it works fine. Tested with default configuration. Can you reproduce this?

**Comment by bmag** [comment]
@Isimoro thanks, I was able to reproduce it. Fixed by https://github.com/syl20bnr/spacemacs/commit/b54ea8ef900e876a8715d54eed0f577fe93b38f4

**Comment by aaronchall** [comment]
Spacemacs still doesn't use Emacs 26's native line numbers.

I turned on relative line numbers permanently in my .spacemacs file with this in my dotspacemacs/init

```
global-display-line-numbers-mode 'relative
display-line-numbers 'relative
```
I commented out dotspacemacs-line-numbers.

Would be nice to have a single entry, but IDK if it makes even makes sense to have spacemacs handle this anymore.

**Comment by hunterboerner** [comment]
++ @aaronchall 

I put this slightly modified version in my `dotspacemacs/user-init`
```emacs-lisp
(global-display-line-numbers-mode t)
(setq-default display-line-numbers t)
```
Only issue is that line numbers now show up on the `*spacemacs*` buffer.

**Comment by duianto** [comment]
The `develop` branch has native Emacs 26 line numbers support.

It's the recommended branch until the next version is released.

#### To try the `develop` branch:
Backup your current setup and make sure that there isn't a `.emacs.d` directory or a `.spacemacs` file in your home directory. Then navigate to your home directory in a terminal (or command prompt) and clone directly to the `develop` branch with:
```
git clone -b develop https://github.com/syl20bnr/spacemacs .emacs.d
```

**Comment by hunterboerner** [comment]
@duianto does the develop branch need any special configuration to use native line numbers?

**Comment by duianto** [comment]
As long as your using Emacs 26 or greater, then it will use the native line numbers.

They can be enabled with the key bindings:
- `SPC t n` (`spacemacs/toggle-line-numbers`)
- `SPC t r` (`spacemacs/toggle-relative-line-numbers`)
- `SPC t V` (`spacemacs/toggle-visual-line-numbers`)

or with the `.spacemacs` variable: `dotspacemacs-line-numbers`

This is what the comment above the variable says:
```
   ;; Control line numbers activation.
   ;; If set to `t', `relative' or `visual' then line numbers are enabled in all
   ;; `prog-mode' and `text-mode' derivatives. If set to `relative', line
   ;; numbers are relative. If set to `visual', line numbers are also relative,
   ;; but lines are only visual lines are counted. For example, folded lines
   ;; will not be counted and wrapped lines are counted as multiple lines.
   ;; This variable can also be set to a property list for finer control:
   ;; '(:relative nil
   ;;   :visual nil
   ;;   :disabled-for-modes dired-mode
   ;;                       doc-view-mode
   ;;                       markdown-mode
   ;;                       org-mode
   ;;                       pdf-view-mode
   ;;                       text-mode
   ;;   :size-limit-kb 1000)
   ;; When used in a plist, `visual' takes precedence over `relative'.
   ;; (default nil)
   dotspacemacs-line-numbers nil
```
