### ISSUE TITLE
org-projectile capture/open todo not working 

### ISSUE THREAD

**Issue by hliebert** [syl20bnr/spacemacs#9408]
#### Description :octocat:
I am getting the message `Wrong number of arguments: (1 . 1), 2` after `SPC p o` and `Invalid function: org-babel-header-args-safe-fn` after `SPC a o p`. After deleting the `elpa/org-plus-contrib` folder (as suggested in some older issue as a fix for the latter message, something about ESS using an older org version iirc) and restarting spacemacs, the messsage following `SPC a o p` changes to `Wrong type argument: stringp, nil`. I am using the `develop` branch.

#### Reproduction guide :beetle:
- Start Emacs
- Open any file in a project. 
- Press `SPC p o` or  `SPC a o p`.

*Observed behaviour:* :eyes: :broken_heart:
Following `SPC p o`:  `Wrong number of arguments: (1 . 1), 2`.
Following `SPC a o p`:  `Invalid function: org-babel-header-args-safe-fn`.
Following `SPC a o p`, after reinstalling org: `Wrong type argument: stringp, nil`.

*Expected behaviour:* :heart: :smile:
Capture or open project-specific todos.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: develop (rev. 0fb17fa9)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp git markdown
      (org :variables org-projectile-file "todo.org" org-enable-reveal-js-support t)
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking syntax-checking version-control ess
      (latex :variables latex-enable-auto-fill t)
      bibtex python shell-scripts html pdf-tools pandoc vimscript evil-snipe vim-powerline)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES

#### Backtrace :paw_prints:
- After `SPC p o`.
```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  #[257 "\301\302\"\207" [projectile-known-projects mapcar #[257 "\300!B\207" [org-projectile-get-category-from-project-todo-file] 3 "\n\n(fn PATH)"]] 4 "\n\n(fn _)"]([eieio-class-tag--org-projectile-per-project-strategy] "Documents")
  apply(#[257 "\301\302\"\207" [projectile-known-projects mapcar #[257 "\300!B\207" [org-projectile-get-category-from-project-todo-file] 3 "\n\n(fn PATH)"]] 4 "\n\n(fn _)"] [eieio-class-tag--org-projectile-per-project-strategy] "Documents")
  org-projectile-category-to-project-path([eieio-class-tag--org-projectile-per-project-strategy] "Documents")
  org-projectile-location-for-project("Documents")
  org-projectile/goto-todos()
  funcall-interactively(org-projectile/goto-todos)
  call-interactively(org-projectile/goto-todos nil nil)
  command-execute(org-projectile/goto-todos)
```

- After `SPC a o p`, before deleting org folder.
```
<Debugger entered--Lisp error: (invalid-function org-babel-header-args-safe-fn)
  org-babel-header-args-safe-fn((:cache :colnames :comments :exports :epilogue :hlines :noeval :noweb :noweb-ref :noweb-sep :padline :prologue :rownames :sep :session :tangle :wrap (:eval "never" "query") (:results lambda (str) (not (string-match "file" str))) :width :height :bg :units :pointsize :antialias :quality :compression :res :type :family :title :fonts :version :paper :encoding :pagecentre :colormodel :useDingbats :horizontal))
  byte-code("\301\302\303\304!#\210\305\306\307\310\311DD\312\313\314\315\316\317\320&	\207" [ob-R-safe-header-args put org-babel-default-header-args:R safe-local-variable org-babel-header-args-safe-fn custom-declare-variable org-babel-R-command funcall function #[0 "\300\207" ["R --slave --no-save"] 1 "R --slave --no-save"] "Name of command to use for executing R code." :group org-babel :version "24.1" :type string] 10)
  require(ob-R)
  org-babel-do-load-languages(org-babel-load-languages ((python . t) (R . t) (shell . t) (emacs-lisp . t)))
  spacemacs//org-babel-do-load-languages()
  run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
  run-mode-hooks(org-mode-hook)
  org-mode()
  org-capture-fill-template("* TODO %?\n")
  #[257 "\211\304\305!!\210p\306\300!\203\203\307	\310\"\202&\3111$\312\313!0\202&\210\313\314\315\316\317!\206=\320\321!\205=\322\n\"@\323\317!\205K\324\317	!!\310\325\326\327\330 \331\206Z\332 &\210\314\333\334\335\336\"!\"\210\337\340\341\342\343\344\345\n!\346\"\347$D!\210\314\350\351\335\352\"\"\"\210\353 \266\202\207" [org-capture-link-is-already-stored org-store-link-plist dired-buffers org-overriding-default-time org-capture-set-plist occ-build-capture-template boundp plist-get :annotation (error) org-store-link nil org-capture-put :original-buffer :original-file buffer-file-name featurep dired rassq :original-file-nondirectory file-name-nondirectory :initial "" :return-to-wconf current-window-configuration :default-time org-current-time :template org-capture-fill-template slot-value template org-capture-set-target-location function make-byte-code 0 "\301\300!\207" vconcat vector [occ-capture-goto-marker] 2 :target-entry-p occ-target-entry-p strategy org-capture-place-template] 19 "\n\n(fn CONTEXT)"]([eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]])
  apply(#[257 "\211\304\305!!\210p\306\300!\203\203\307	\310\"\202&\3111$\312\313!0\202&\210\313\314\315\316\317!\206=\320\321!\205=\322\n\"@\323\317!\205K\324\317	!!\310\325\326\327\330 \331\206Z\332 &\210\314\333\334\335\336\"!\"\210\337\340\341\342\343\344\345\n!\346\"\347$D!\210\314\350\351\335\352\"\"\"\210\353 \266\202\207" [org-capture-link-is-already-stored org-store-link-plist dired-buffers org-overriding-default-time org-capture-set-plist occ-build-capture-template boundp plist-get :annotation (error) org-store-link nil org-capture-put :original-buffer :original-file buffer-file-name featurep dired rassq :original-file-nondirectory file-name-nondirectory :initial "" :return-to-wconf current-window-configuration :default-time org-current-time :template org-capture-fill-template slot-value template org-capture-set-target-location function make-byte-code 0 "\301\300!\207" vconcat vector [occ-capture-goto-marker] 2 :target-entry-p occ-target-entry-p strategy org-capture-place-template] 19 "\n\n(fn CONTEXT)"] [eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]] nil)
  occ-capture([eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]])
  org-projectile-capture-for-current-project(nil :empty-lines 1)
  (if arg (org-projectile-project-todo-completing-read nil :empty-lines 1) (org-projectile-capture-for-current-project nil :empty-lines 1))
  org-projectile/capture(nil)
  funcall-interactively(org-projectile/capture nil)
  call-interactively(org-projectile/capture nil nil)
  command-execute(org-projectile/capture)
```

- After `SPC a o p`, after reinstalling org.
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-as-directory(nil)
  org-projectile-get-project-todo-file(nil)
  #[514 "\300\301!\"A\302!\207" [assoc org-projectile-category-to-project-path org-projectile-get-project-todo-file] 6 "\n\n(fn S CATEGORY)"]([eieio-class-tag--org-projectile-per-project-strategy] "Documents")
  apply(#[514 "\300\301!\"A\302!\207" [assoc org-projectile-category-to-project-path org-projectile-get-project-todo-file] 6 "\n\n(fn S CATEGORY)"] [eieio-class-tag--org-projectile-per-project-strategy] "Documents")
  occ-get-capture-file([eieio-class-tag--org-projectile-per-project-strategy] "Documents")
  #[514 "\211\300\301\302\"\"r\303!q\210\304 )\262\207" [occ-get-capture-file slot-value category find-file-noselect point-max-marker] 8 "\n\n(fn STRATEGY CONTEXT)"]([eieio-class-tag--org-projectile-per-project-strategy] [eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]])
  apply(#[514 "\211\300\301\302\"\"r\303!q\210\304 )\262\207" [occ-get-capture-file slot-value category find-file-noselect point-max-marker] 8 "\n\n(fn STRATEGY CONTEXT)"] [eieio-class-tag--org-projectile-per-project-strategy] [eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]])
  occ-get-capture-marker([eieio-class-tag--org-projectile-per-project-strategy] [eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]])
  #[257 "\300\301\302\"\"\207" [occ-get-capture-marker eieio-oref strategy] 5 "\n\n(fn CONTEXT)"]([eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]])
  apply(#[257 "\300\301\302\"\"\207" [occ-get-capture-marker eieio-oref strategy] 5 "\n\n(fn CONTEXT)"] [eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]] nil)
  occ-get-capture-marker([eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]])
  occ-capture-goto-marker([eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]])
  #[0 "\301\300!\207" [[eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]] occ-capture-goto-marker] 2]()
  org-capture-set-target-location((function #[0 "\301\300!\207" [[eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]] occ-capture-goto-marker] 2]))
  #[257 "\211\304\305!!\210p\306\300!\203\203\307	\310\"\202&\3111$\312\313!0\202&\210\313\314\315\316\317!\206=\320\321!\205=\322\n\"@\323\317!\205K\324\317	!!\310\325\326\327\330 \331\206Z\332 &\210\314\333\334\335\336\"!\"\210\337\340\341\342\343\344\345\n!\346\"\347$D!\210\314\350\351\335\352\"\"\"\210\353 \266\202\207" [org-capture-link-is-already-stored org-store-link-plist dired-buffers org-overriding-default-time org-capture-set-plist occ-build-capture-template boundp plist-get :annotation (error) org-store-link nil org-capture-put :original-buffer :original-file buffer-file-name featurep dired rassq :original-file-nondirectory file-name-nondirectory :initial "" :return-to-wconf current-window-configuration :default-time org-current-time :template org-capture-fill-template slot-value template org-capture-set-target-location function make-byte-code 0 "\301\300!\207" vconcat vector [occ-capture-goto-marker] 2 :target-entry-p occ-target-entry-p strategy org-capture-place-template] 19 "\n\n(fn CONTEXT)"]([eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]])
  apply(#[257 "\211\304\305!!\210p\306\300!\203\203\307	\310\"\202&\3111$\312\313!0\202&\210\313\314\315\316\317!\206=\320\321!\205=\322\n\"@\323\317!\205K\324\317	!!\310\325\326\327\330 \331\206Z\332 &\210\314\333\334\335\336\"!\"\210\337\340\341\342\343\344\345\n!\346\"\347$D!\210\314\350\351\335\352\"\"\"\210\353 \266\202\207" [org-capture-link-is-already-stored org-store-link-plist dired-buffers org-overriding-default-time org-capture-set-plist occ-build-capture-template boundp plist-get :annotation (error) org-store-link nil org-capture-put :original-buffer :original-file buffer-file-name featurep dired rassq :original-file-nondirectory file-name-nondirectory :initial "" :return-to-wconf current-window-configuration :default-time org-current-time :template org-capture-fill-template slot-value template org-capture-set-target-location function make-byte-code 0 "\301\300!\207" vconcat vector [occ-capture-goto-marker] 2 :target-entry-p occ-target-entry-p strategy org-capture-place-template] 19 "\n\n(fn CONTEXT)"] [eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]] nil)
  occ-capture([eieio-class-tag--occ-context "Documents" "* TODO %?\n" (:empty-lines 1) [eieio-class-tag--org-projectile-per-project-strategy]])
  org-projectile-capture-for-current-project(nil :empty-lines 1)
  (if arg (org-projectile-project-todo-completing-read nil :empty-lines 1) (org-projectile-capture-for-current-project nil :empty-lines 1))
  org-projectile/capture(nil)
  funcall-interactively(org-projectile/capture nil)
  call-interactively(org-projectile/capture nil nil)
  command-execute(org-projectile/capture)
```

**Comment by Awesomecase** [comment]
I'm getting the same error on develop.

**Comment by smile13241324** [comment]
Have you already tried to manually remove a possibly corrupted `ob-R.elc` file? This is what normally causes this `function: org-babel-header-args-safe-fn` error. As this is done within the org-mode-hook this can prevent other functions to be called during the loading process causing a whole bunch of nasty side effects.

If this does not work you please try below workaround from #4618.

>It usually happens in spacemacs that you end up with both org and org-plus-contrib package, making it harder to know where the broken ob-R.elc file is. Start package manager with M-x paradox, delete org and org-plus-contrib, then install only prg-plus-contrib. This usually works for me.

**Comment by aaronjensen** [comment]
This is the stacktrace when `org-projectile` is not byte compiled after `SPC p o`:

```
Debugger entered--Lisp error: (wrong-number-of-arguments ((t) (_) (progn (mapcar (function (lambda (path) (cons (org-projectile-category-from-project-root path) path))) projectile-known-projects))) 2)
  (closure (t) (_) (progn (mapcar (function (lambda (path) (cons (org-projectile-category-from-project-root path) path))) projectile-known-projects)))(#<org-projectile-single-file-strategy org-projectile-single-file-strategy> ".spacemacs.d")
  apply((closure (t) (_) (progn (mapcar (function (lambda (path) (cons (org-projectile-category-from-project-root path) path))) projectile-known-projects))) #<org-projectile-single-file-strategy org-projectile-single-file-strategy> ".spacemacs.d")
  org-projectile-category-to-project-path(#<org-projectile-single-file-strategy org-projectile-single-file-strategy> ".spacemacs.d")
  org-projectile-location-for-project(".spacemacs.d")
  org-projectile/goto-todos()
  funcall-interactively(org-projectile/goto-todos)
  call-interactively(org-projectile/goto-todos nil nil)
  command-execute(org-projectile/goto-todos)
```

I cannot reproduce the issue with `SPC a o p`, that works fine for me.

**Comment by aaronjensen** [comment]
fyi, [reported upstream](https://github.com/IvanMalison/org-projectile/issues/32)

**Comment by aaronjensen** [comment]
Fixed upstream, but requires #9422 here.

**Comment by hliebert** [comment]
After updating everything, I am getting the `function: org-babel-header-args-safe-fn` error after both commands. Deleting the org folder, the message disappears. 

However, none of the commands work. Both initialize evil-magit the first time either is executed.  `SPC p o` then does nothing. `SPC a o p` still throws `Wrong type argument: stringp, nil`. However, I just realized `SPC u SPC a o p` works. Is the `SPC u` prefix required? 

I do not have two different org versions installed and deleting and compiling ob-R.elc again doesn't change the above.

**Comment by hliebert** [comment]
Sorry, for some reason I thought the change had already made it into develop. 

After including #9422, I am still getting `Wrong type argument: stringp, nil`, now after both `SPC p o` and `SPC a o p`. When setting `org-projectile-file` to a fixed location/single file, the message changes to `Wrong type argument: number-or-marker-p, nil`.

I just realized that `SPC p o` actually opens a new todo file when there is no existing one. After saving the file, `SPC p o' in a new Emacs instance again results in the error message above.

**Comment by aaronjensen** [comment]
Can you post the full stack trace for the `number-or-marker-p` error? You may need to delete the `org-projectile.elc` file to get useful stack traces.

**Comment by aaronjensen** [comment]
I'm not sure what is causing what you're seeing. Since this looks to be coming from org-projectile, could you open an issue here: https://github.com/IvanMalison/org-projectile/issues

@IvanMalison is typically pretty fast to respond, he can probably help further.

**Comment by IvanMalison** [comment]
@hliebert are you sure that your file is an org-mode file? I suspect that `(org-current-level)` is returning nil which is causing your problem

**Comment by IvanMalison** [comment]
@hliebert can you post the backtrace for the Wrong type argument: stringp, nil error you were getting?

**Comment by hliebert** [comment]
Sure, here it is. It doesn't matter whether the file is empty or has content. The file is always named `todo.org`.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-as-directory(nil)
  (concat (file-name-as-directory project-path) org-projectile-per-project-filepath)
  org-projectile-get-project-todo-file(nil)
  (let ((project-root (cdr (assoc category (org-projectile-category-to-project-path s))))) (org-projectile-get-project-todo-file project-root))
  (progn (let ((project-root (cdr (assoc category (org-projectile-category-to-project-path s))))) (org-projectile-get-project-todo-file project-root)))
  (closure (t) (s category) (progn (let ((project-root (cdr (assoc category (org-projectile-category-to-project-path s))))) (org-projectile-get-project-todo-file project-root))))([eieio-class-tag--org-projectile-per-project-strategy] "Documents")
  apply((closure (t) (s category) (progn (let ((project-root (cdr (assoc category (org-projectile-category-to-project-path s))))) (org-projectile-get-project-todo-file project-root)))) [eieio-class-tag--org-projectile-per-project-strategy] "Documents")
  occ-get-capture-file([eieio-class-tag--org-projectile-per-project-strategy] "Documents")
  (let ((filepath (occ-get-capture-file strategy (slot-value object (quote category))))) (save-current-buffer (set-buffer (find-file-noselect filepath)) (point-max-marker)))
  (let* ((object context)) (let ((filepath (occ-get-capture-file strategy (slot-value object (quote category))))) (save-current-buffer (set-buffer (find-file-noselect filepath)) (point-max-marker))))
  (progn (let* ((object context)) (let ((filepath (occ-get-capture-file strategy (slot-value object (quote category))))) (save-current-buffer (set-buffer (find-file-noselect filepath)) (point-max-marker)))))
  (closure (t) (strategy context) (progn (let* ((object context)) (let ((filepath (occ-get-capture-file strategy (slot-value object ...)))) (save-current-buffer (set-buffer (find-file-noselect filepath)) (point-max-marker))))))([eieio-class-tag--org-projectile-per-project-strategy] [eieio-class-tag--occ-context "Documents" "* TODO %?\n" nil [eieio-class-tag--org-projectile-per-project-strategy]])
  apply((closure (t) (strategy context) (progn (let* ((object context)) (let ((filepath (occ-get-capture-file strategy (slot-value object ...)))) (save-current-buffer (set-buffer (find-file-noselect filepath)) (point-max-marker)))))) [eieio-class-tag--org-projectile-per-project-strategy] [eieio-class-tag--occ-context "Documents" "* TODO %?\n" nil [eieio-class-tag--org-projectile-per-project-strategy]])
  occ-get-capture-marker([eieio-class-tag--org-projectile-per-project-strategy] [eieio-class-tag--occ-context "Documents" "* TODO %?\n" nil [eieio-class-tag--org-projectile-per-project-strategy]])
  #[257 "\300\301\302\"\"\207" [occ-get-capture-marker eieio-oref strategy] 5 "\n\n(fn CONTEXT)"]([eieio-class-tag--occ-context "Documents" "* TODO %?\n" nil [eieio-class-tag--org-projectile-per-project-strategy]])
  apply(#[257 "\300\301\302\"\"\207" [occ-get-capture-marker eieio-oref strategy] 5 "\n\n(fn CONTEXT)"] [eieio-class-tag--occ-context "Documents" "* TODO %?\n" nil [eieio-class-tag--org-projectile-per-project-strategy]] nil)
  occ-get-capture-marker([eieio-class-tag--occ-context "Documents" "* TODO %?\n" nil [eieio-class-tag--org-projectile-per-project-strategy]])
  occ-capture-goto-marker([eieio-class-tag--occ-context "Documents" "* TODO %?\n" nil [eieio-class-tag--org-projectile-per-project-strategy]])
  org-projectile-goto-location-for-project("Documents")
  org-projectile/goto-todos()
  funcall-interactively(org-projectile/goto-todos)
  call-interactively(org-projectile/goto-todos nil nil)
  command-execute(org-projectile/goto-todos)
```

**Comment by IvanMalison** [comment]
@hliebert can you try org-projectile/24e5a69fd83fa6958d78327e91722264d4b517ec to see if that fixes things for you?

**Comment by hliebert** [comment]
Just updated and that seems to fix it! Both `SPC p o` and `SPC a o p` are working as expected now.

**Comment by IvanMalison** [comment]
@hliebert great to hear. Can this issue be closed?

**Comment by aaronjensen** [comment]
Probably not until https://github.com/syl20bnr/spacemacs/pull/9422 is merged, and then it'd get marked as "fixed in develop". Thanks for your help @IvanMalison.

**Comment by syl20bnr** [comment]
Thank you, should be fixed in develop.

**Comment by roychoo** [comment]
hmm after updating to the latest develop and plugins, i am seeing this error when i 
```SPC a o p```

```
org-projectile-capture-for-current-project: Keyword argument nil not one of (:capture-template)
```

**Comment by duianto** [comment]
@roychoo This PR:
Fix org-projectile capture-template keyword argument #9770
seems to be related to your issue, it removes the `nil` argument when:
`org-projectile-capture-for-current-project` is called.

**Comment by leezu** [comment]
@roychoo @duianto that is related to a bug introduced upstream in https://github.com/IvanMalison/org-projectile/commit/d57062569e59f598fcad1107f463691ec5d07e5f

Until https://github.com/syl20bnr/spacemacs/pull/9770 is merged it won't work. (Not sure why its not merged though)

**Comment by duianto** [comment]
@leezu I would guess that it hasn't come to the attention of the collaborators yet.

### Here's what happens when the key bindings mentioned above are pressed:
#### Outside a project, for example when the `.spacemacs` file is open:
Pressing `SPC a o p` shows the following line in the messages buffer:
`org-projectile-capture-for-current-project: - is not a recognized projectile project.`

Pressing `SPC p o` shows:
`org-projectile-get-project-todo-file: Wrong type argument: stringp, nil`

#### In a project, for example with the `.emacs.d` directory open in a dired buffer:
`SPC a o p` shows:
`org-capture-put: Wrong type argument: listp, (nil :empty-lines 1)`
This is fixed by the PR #9770.

`SPC p o` opens an existing `TODOs.org` file in the `.emacs.d` directory, or if `TODOs.org` doesn't exist then a new buffer with the same name opens.

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0ea72bcd)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(spell-checking syntax-checking
                (auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t)
                helm org treemacs git version-control autohotkey emacs-lisp haskell markdown)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS MODULES

**Comment by bmag** [comment]
#9770 is merged now in develop, so should be good once again.

**Comment by phha** [comment]
Any reason why this is not being merged to master?
