### ISSUE TITLE
org mode layer is stepping on my customized value for `org-default-notes-file` 

### ISSUE THREAD

**Issue by twillis** [syl20bnr/spacemacs#9748]
<<REPLACE ALL UPPERCASE EXPRESSIONS AND DELETE THIS LINE, `C-c C-c` TO SUBMIT>>
#### Description :octocat:
<<DESCRIPTION OF THE PROBLEM>>
org mode layer is stepping on my customized value for `org-default-notes-file` leading to notes.org files all over my hd that are not added to my agendas
#### Reproduction guide :beetle:
- Start Emacs
- <<REPRODUCTION STEPS>>
customize variable `org-default-notes-file` to something other than the default and save for future sessions

note that the value you set is in your `.spacemacs`

*Observed behaviour:* :eyes: :broken_heart:
<<DESCRIPTION OF THE OBSERVED BEHAVIOUR>>
restart spacemacs navigate to `.spacemacs` to where the variable was set by customize

`SPC hdv <enter>` note that the value is "notes.org" and not what was set in customize

*Expected behaviour:* :heart: :smile:
<<DESCRIPTION OF THE EXPECTED BEHAVIOUR>>
dont step on my customized variable or if you do, make it something actually useful. 

source of the problem https://github.com/syl20bnr/spacemacs/blob/bd7ef98e4c35fd87538dd2a81356cc83f5fd02f3/layers/%2Bemacs/org/packages.el#L297
#### System Info :computer:
- OS: darwin
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(scheme helm csv sql auto-completion clojure common-lisp
        (ruby :variables ruby-test-runner 'rspec ruby-version-manager 'rbenv)
        python javascript emacs-lisp markdown
        (org :variables org-enable-reveal-js-support t org-enable-org-journal-support t)
        nim syntax-checking version-control git osx shell ibuffer yaml html colors erc)
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by CeleritasCelery** [comment]
#9750 should fix this. In the mean time you could try wrapping your code in a `(with-eval-after-load 'org <code>)` block.

**Comment by bmag** [comment]
Should be fixed now.

**Comment by twillis** [comment]
@bmag on master?

**Comment by CeleritasCelery** [comment]
Eventually

**Comment by bmag** [comment]
@twillis fixed in develop. Master won't be fixed until the next major-version release of Spacemacs. Until then you can use `with-eval-after-load` as @CeleritasCelery suggested.

**Comment by dkrieger** [comment]
What is the typical release cycle? Surprised this is still an issue in master 1.5 years later
